<?php
use Interferencia\Modules\Organization\ContractContent;
$editing=is_array($template);
$variables=['{{razao_social}}'=>'Razão social','{{cnpj}}'=>'CNPJ','{{endereco_completo}}'=>'Endereço completo','{{gestor_nome}}'=>'Nome do gestor','{{nome_franquia}}'=>'Nome da franquia','{{condicoes_comerciais}}'=>'Condições comerciais','{{vigencia}}'=>'Vigência','{{cidade}}'=>'Cidade','{{data_extenso}}'=>'Data'];
$initialBody=ContractContent::toHtml((string)($template['body']??''));
?>
<div class="page-header contract-template-heading"><div><p class="eyebrow">Franquias · Contratos</p><h1><?= $editing?'Editar modelo':'Novo modelo' ?></h1><p>Monte o documento visualmente e use variáveis para preencher os dados de cada franquia.</p></div><a class="button button-secondary" href="<?= $escape($basePath) ?>/admin/franchise-contract-templates"><i class="fa-solid fa-arrow-left"></i> Voltar</a></div>
<?php if(!empty($error)):?><div class="alert alert-danger"><?= $escape($error) ?></div><?php endif;?>
<form class="card contract-template-form" method="post" action="<?= $escape($basePath) ?>/admin/franchise-contract-templates<?= $editing?'/'.(int)$template['id']:'' ?>" data-contract-rich-editor><?= $csrfField ?>
<div class="contract-template-meta-grid"><label class="contract-template-title">Título *<input name="title" required maxlength="180" value="<?= $escape($template['title']??'') ?>" placeholder="Ex.: Contrato de prestação de serviços"></label><label>Versão *<input name="version" required maxlength="30" value="<?= $escape($template['version']??'1.0') ?>"></label><label class="contract-template-toggle"><input type="checkbox" name="is_active" value="1" <?= !$editing||(int)$template['is_active']===1?'checked':'' ?>><span><strong>Modelo ativo</strong><small>Pode ser usado em novos contratos</small></span></label></div>
<div class="contract-editor-workspace"><section class="contract-editor-column"><div class="contract-editor-label"><div><strong>Conteúdo do contrato *</strong><small>Use a barra de ferramentas para formatar o documento.</small></div><span><i class="fa-solid fa-shield-halved"></i> Formatação segura</span></div><div class="contract-editor-toolbar" role="toolbar" aria-label="Formatação do contrato"><button type="button" data-editor-command="bold" title="Negrito"><i class="fa-solid fa-bold"></i></button><button type="button" data-editor-command="italic" title="Itálico"><i class="fa-solid fa-italic"></i></button><button type="button" data-editor-command="underline" title="Sublinhado"><i class="fa-solid fa-underline"></i></button><span></span><button type="button" data-editor-command="formatBlock" data-editor-value="p" title="Parágrafo"><i class="fa-solid fa-paragraph"></i></button><button type="button" data-editor-command="formatBlock" data-editor-value="h2" title="Título"><i class="fa-solid fa-heading"></i></button><button type="button" data-editor-command="formatBlock" data-editor-value="h3" title="Subtítulo"><i class="fa-solid fa-text-height"></i></button><span></span><button type="button" data-editor-command="insertUnorderedList" title="Lista com marcadores"><i class="fa-solid fa-list-ul"></i></button><button type="button" data-editor-command="insertOrderedList" title="Lista numerada"><i class="fa-solid fa-list-ol"></i></button><button type="button" data-editor-command="formatBlock" data-editor-value="blockquote" title="Citação"><i class="fa-solid fa-quote-left"></i></button><span></span><button type="button" data-editor-command="undo" title="Desfazer"><i class="fa-solid fa-rotate-left"></i></button><button type="button" data-editor-command="redo" title="Refazer"><i class="fa-solid fa-rotate-right"></i></button></div><div class="contract-rich-editor" contenteditable="true" role="textbox" aria-multiline="true" data-contract-editor data-placeholder="Digite o conteúdo completo do contrato..."><?= $initialBody ?></div><textarea name="body" required data-contract-editor-input hidden><?= $escape($template['body']??'') ?></textarea></section>
<aside class="contract-editor-sidebar"><section><h2><i class="fa-solid fa-wand-magic-sparkles"></i> Variáveis</h2><p>Clique para inserir no ponto atual do texto.</p><div class="contract-variable-list"><?php foreach($variables as$code=>$label):?><button type="button" data-contract-variable="<?= $escape($code) ?>"><span><?= $escape($label) ?></span><code><?= $escape($code) ?></code></button><?php endforeach;?></div></section><section class="contract-editor-tip"><i class="fa-regular fa-lightbulb"></i><div><strong>Dica</strong><p>Os dados são substituídos somente quando o contrato é gerado para uma franquia.</p></div></section></aside></div>
<section class="contract-preview-card"><header><div><span>Prévia</span><h2>Visualização do documento</h2></div><i class="fa-regular fa-file-lines"></i></header><article data-contract-preview><?= $initialBody ?></article></section>
<div class="contract-template-footer"><div><i class="fa-solid fa-circle-info"></i><span>O conteúdo é higienizado antes de ser salvo para proteger os contratos.</span></div><button class="button button-primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Salvar modelo</button></div>
</form>
