<div class="page-header"><div><p class="eyebrow">Franquias · Contratos</p><h1>Modelos</h1><p>Crie, organize e reutilize os textos-base dos contratos da rede.</p></div><a class="button button-primary" href="<?= $escape($basePath) ?>/admin/franchise-contract-templates/create"><i class="fa-solid fa-plus"></i> Novo modelo</a></div>
<?php if(!empty($message)):?><div class="alert alert-success"><?= $escape($message) ?></div><?php endif;?>
<?php if(!empty($error)):?><div class="alert alert-danger"><?= $escape($error) ?></div><?php endif;?>
<div class="table-card contract-template-list"><table><thead><tr><th>Modelo</th><th>Versão</th><th>Situação</th><th>Uso</th><th>Atualizado</th><th>Ações</th></tr></thead><tbody>
<?php foreach($templates as$item):$usage=(int)($item['usage_count']??0);$versionCount=(int)($item['version_count']??1);$active=(int)$item['is_active']===1;?><tr>
<td><span class="table-cell-stack"><strong><?= $escape($item['title']) ?></strong><small><?= $active?'Disponível para novos contratos':'Mantido somente para histórico' ?></small></span></td>
<td><span class="table-cell-stack"><strong>v<?= $escape($item['version']) ?></strong><small><?= $versionCount ?> vers<?= $versionCount===1?'ão':'ões' ?> no histórico</small></span></td>
<td><span class="status <?= $active?'status-active':'status-muted' ?>"><?= $active?'Ativo':'Arquivado' ?></span></td>
<td><span class="contract-usage"><i class="fa-solid fa-file-signature"></i> <?= $usage ?> contrato<?= $usage===1?'':'s' ?></span></td>
<td><?= $escape(date('d/m/Y H:i',strtotime((string)$item['updated_at']))) ?></td>
<td><div class="contract-template-actions"><a class="button button-secondary button-icon" title="Editar modelo" aria-label="Editar modelo" href="<?= $escape($basePath) ?>/admin/franchise-contract-templates/<?= (int)$item['id'] ?>/edit"><i class="fa-solid fa-pen"></i></a><?php if($versionCount>1):?><a class="button button-secondary button-icon" title="Comparar versões" aria-label="Comparar versões" href="<?= $escape($basePath) ?>/admin/franchise-contract-templates/<?= (int)$item['id'] ?>/compare"><i class="fa-solid fa-code-compare"></i></a><?php endif;?><form method="post" action="<?= $escape($basePath) ?>/admin/franchise-contract-templates/<?= (int)$item['id'] ?>/duplicate"><?= $csrfField ?><button class="button button-secondary button-icon" type="submit" title="Criar nova versão" aria-label="Criar nova versão"><i class="fa-solid fa-code-branch"></i></button></form><form method="post" action="<?= $escape($basePath) ?>/admin/franchise-contract-templates/<?= (int)$item['id'] ?>/delete" data-confirm-submit="<?= $escape($usage>0||$versionCount>1?'Este modelo possui histórico. Ele será arquivado e os documentos serão preservados. Continuar?':'Excluir definitivamente este modelo?') ?>"><?= $csrfField ?><button class="button-danger button-icon" type="submit" title="<?= $usage>0||$versionCount>1?'Arquivar modelo':'Excluir modelo' ?>" aria-label="<?= $usage>0||$versionCount>1?'Arquivar modelo':'Excluir modelo' ?>"><i class="fa-solid <?= $usage>0||$versionCount>1?'fa-box-archive':'fa-trash' ?>"></i></button></form></div></td>
</tr><?php endforeach;?>
<?php if($templates===[]):?><tr><td colspan="6"><div class="empty-state"><i class="fa-regular fa-file-lines"></i><strong>Nenhum modelo cadastrado</strong><p>Crie o primeiro modelo para começar.</p></div></td></tr><?php endif;?>
</tbody></table></div>
