<?php
$scope=$organization===null?'central':'franchise';$titleLabel=$organization===null?'Documentos do ADM Central':'Documentos da franquia';$prefix=$organization===null?$basePath.'/admin/documents':$basePath.'/admin/organizations/'.(int)$organization['id'].'/documents';
$grouped=[];foreach($documents as$document){$grouped[$document['document_group']][]=$document;}
?>
<div class="page-header"><div><p class="eyebrow"><?= $organization===null?'ADM Central':'ADM Central · Franquia' ?></p><h1><?= $escape($titleLabel) ?><?= $organization!==null?' — '.$escape((string)$organization['display_name']):'' ?></h1><p>Arquivos privados, organizados por categoria e com histórico de versões.</p></div><div class="page-actions"><?php if($organization!==null):?><a class="button button-secondary" href="<?= $escape($basePath) ?>/admin/organizations/<?= (int)$organization['id'] ?>"><i class="fa-solid fa-arrow-left"></i> Voltar à franquia</a><?php endif;?></div></div>
<?php if(!empty($message)):?><div class="alert alert-success"><?= $escape($message) ?></div><?php endif;?><?php if(!empty($error)):?><div class="alert alert-danger"><?= $escape($error) ?></div><?php endif;?>

<section class="card mb-4"><div class="card-header"><div><h2><i class="fa-solid fa-cloud-arrow-up"></i> <?= $versionOf?'Enviar nova versão':'Adicionar documento' ?></h2><p class="meta">O arquivo ficará privado no DigitalOcean Spaces e só poderá ser aberto por usuários autorizados.</p></div></div>
 <form class="form-grid" method="post" action="<?= $escape($prefix) ?>" enctype="multipart/form-data"><?= $csrfField ?>
  <?php if($versionOf):?><input type="hidden" name="replace_id" value="<?= (int)$versionOf['id'] ?>"><div class="form-span-2 alert alert-success mb-0"><strong>Nova versão de:</strong> <?= $escape((string)$versionOf['title']) ?> · versão atual <?= (int)$versionOf['version_number'] ?></div><?php endif;?>
  <label>Título <span class="required-mark">*</span><input required maxlength="180" name="title" value="<?= $escape((string)($versionOf['title']??'')) ?>" placeholder="Ex.: Contrato social atualizado"></label>
  <label>Categoria <span class="required-mark">*</span><select required name="category"><option value="">Selecione</option><?php foreach($categories as$value=>$label):?><option value="<?= $escape($value) ?>" <?= ($versionOf['category']??'')===$value?'selected':'' ?>><?= $escape($label) ?></option><?php endforeach;?></select></label>
  <label class="form-span-2">Descrição<textarea maxlength="1000" rows="2" name="description" placeholder="Contexto ou observações internas"><?= $escape((string)($versionOf['description']??'')) ?></textarea></label>
  <label class="form-span-2">Arquivo <span class="required-mark">*</span><input required type="file" name="document" accept=".pdf,.jpg,.jpeg,.png,.webp,.doc,.docx,.xls,.xlsx,.csv,.txt"><small>PDF, imagens, Word, Excel, CSV ou texto · máximo 25 MB.</small></label>
  <div class="form-actions form-span-2"><button class="button button-primary" type="submit"><i class="fa-solid fa-cloud-arrow-up"></i> <?= $versionOf?'Salvar nova versão':'Enviar documento' ?></button><?php if($versionOf):?><a class="button button-secondary" href="<?= $escape($prefix) ?>">Cancelar</a><?php endif;?></div>
 </form>
</section>

<section class="card"><div class="card-header"><div><h2>Arquivos</h2><p class="meta">A versão mais recente aparece primeiro; o histórico permanece disponível.</p></div><form method="get"><select name="category" onchange="this.form.submit()"><option value="">Todas as categorias</option><?php foreach($categories as$value=>$label):?><option value="<?= $escape($value) ?>" <?= $selectedCategory===$value?'selected':'' ?>><?= $escape($label) ?></option><?php endforeach;?></select></form></div>
<?php if($grouped===[]):?><div class="empty-state"><i class="fa-regular fa-folder-open"></i><strong>Nenhum documento cadastrado</strong><span>Envie o primeiro arquivo usando o formulário acima.</span></div><?php else:?><div class="table-responsive"><table><thead><tr><th>Documento</th><th>Categoria</th><th>Versão</th><th>Tamanho</th><th>Enviado por</th><th>Data</th><th>Ações</th></tr></thead><tbody><?php foreach($grouped as$versions):?><?php $current=$versions[0];?><tr><td><strong><?= $escape((string)$current['title']) ?></strong><small class="d-block meta"><?= $escape((string)$current['original_name']) ?></small><?php if($current['description']):?><small class="d-block meta"><?= $escape((string)$current['description']) ?></small><?php endif;?></td><td><?= $escape($categories[$current['category']]??(string)$current['category']) ?></td><td><span class="badge">v<?= (int)$current['version_number'] ?></span><?php if(count($versions)>1):?><details class="mt-2"><summary class="small">Ver histórico (<?= count($versions) ?>)</summary><?php foreach($versions as$old):?><a class="d-block small mt-2" href="<?= $escape($prefix) ?>/<?= (int)$old['id'] ?>/download">v<?= (int)$old['version_number'] ?> · <?= $escape(date('d/m/Y H:i',strtotime((string)$old['created_at']))) ?></a><?php endforeach;?></details><?php endif;?></td><td><?= number_format((int)$current['bytes']/1048576,2,',','.') ?> MB</td><td><?= $escape((string)($current['created_by_name']?:'Sistema')) ?></td><td><?= $escape(date('d/m/Y H:i',strtotime((string)$current['created_at']))) ?></td><td><div class="table-actions"><a class="button button-secondary button-icon" title="Baixar" href="<?= $escape($prefix) ?>/<?= (int)$current['id'] ?>/download"><i class="fa-solid fa-download"></i></a><?php if(str_starts_with((string)$current['mime_type'],'image/')||(string)$current['mime_type']==='application/pdf'):?><a class="button button-secondary button-icon" title="Visualizar" target="_blank" href="<?= $escape($prefix) ?>/<?= (int)$current['id'] ?>/download?inline=1"><i class="fa-solid fa-eye"></i></a><?php endif;?><a class="button button-secondary button-icon" title="Nova versão" href="<?= $escape($prefix) ?>?version_of=<?= (int)$current['id'] ?>"><i class="fa-solid fa-code-branch"></i></a><form method="post" action="<?= $escape($prefix) ?>/<?= (int)$current['id'] ?>/delete" onsubmit="return confirm('Arquivar esta versão? O arquivo será preservado para auditoria.')"><?= $csrfField ?><button class="button button-danger button-icon" title="Arquivar" type="submit"><i class="fa-solid fa-box-archive"></i></button></form></div></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
