<?php declare(strict_types=1); /** @var Closure(mixed):string $escape */ ?>
<div class="actions"><div><span class="status">ADM · Integrações</span><h1>Integração Asaas</h1><p class="meta">Conexão, sincronização e monitoramento financeiro exclusivos do Administrador Global.</p></div><a href="<?= $escape($basePath) ?>/finance/customers">Ver clientes financeiros</a></div>
<?php if($message):?><p class="alert alert-success"><?= $escape($message) ?></p><?php endif;?><?php if($error):?><p class="alert alert-danger"><?= $escape($error) ?></p><?php endif;?>
<?php if(!$encryptionReady):?><p class="alert alert-warning"><strong>Proteção pendente.</strong> Configure primeiro a chave-mestra no servidor. O cadastro da API permanece bloqueado.</p><?php endif;?>
<div class="dashboard-grid mb-4"><article class="metric-card"><span>Clientes locais</span><strong><?= (int)$summary['customers'] ?></strong><small><?= (int)$summary['legacy_customers'] ?> sem unidade</small></article><article class="metric-card"><span>Cobranças locais</span><strong><?= (int)$summary['payments'] ?></strong><small><?= (int)$summary['legacy_payments'] ?> sem unidade</small></article><article class="metric-card"><span>Conexão</span><strong><?= $connectionReady?'Ativa':'Pendente' ?></strong><small><?= $escape($settings['environment']==='production'?'Produção':'Sandbox') ?></small></article><article class="metric-card"><span>Webhook</span><strong><?= $webhookReady?'Protegido':'Pendente' ?></strong><small>Eventos do Asaas</small></article></div>
<section class="card mb-4"><div class="card-body"><div class="actions mb-0"><div><h2>Sincronização</h2><p class="meta mb-0">Importe clientes e cobranças em lotes seguros. A operação apenas consulta o Asaas.</p></div><form method="post" action="<?= $escape($basePath) ?>/finance/sync"><?= $csrfField ?><button class="button-primary" type="submit" <?= !$connectionReady?'disabled':'' ?>><i class="fa-solid fa-rotate"></i> Sincronizar próximo lote</button></form></div></div></section>
<section class="card"><div class="card-body"><div class="mb-4"><strong>Estado atual</strong><p class="meta mb-1"><?= $settings['configured']?'Chave cadastrada terminada em ••••'.$escape($settings['api_key_last4']):'Nenhuma chave cadastrada.' ?></p><span class="connection-badge <?= $settings['configured']&&$settings['is_active']?'connection-approved':'connection-pending' ?>"><?= $settings['configured']&&$settings['is_active']?'Ativa':'Inativa' ?></span> <?php if($settings['configured']):?><span class="connection-badge"><?= $escape($settings['environment']==='production'?'Produção':'Sandbox') ?></span><?php endif;?></div>
<form method="post" action="<?= $escape($basePath) ?>/admin/integrations/asaas"><?= $csrfField ?><div class="form-field"><label for="asaas-api-key">Nova chave da API <span class="required">*</span></label><input id="asaas-api-key" name="api_key" type="password" autocomplete="new-password" required placeholder="$aact_hmlg_... ou $aact_prod_..." <?= !$encryptionReady?'disabled':'' ?>><small>A chave atual nunca é exibida. Ao salvar uma nova chave, o token do webhook também é rotacionado.</small></div><label class="checkbox-row"><input type="checkbox" name="is_active" value="1" checked> Ativar integração após salvar</label><button class="button-primary" type="submit" <?= !$encryptionReady?'disabled':'' ?>>Salvar conexão</button></form></div></section>
<?php if($settings['configured']):?><section class="card mt-4"><div class="card-body"><h2>Webhook</h2><p class="meta">Use estes dados no cadastro do webhook dentro do Asaas. O token é exibido somente nesta área administrativa protegida.</p><div class="form-field"><label>URL do webhook</label><input type="text" readonly value="<?= $escape($webhookUrl) ?>"></div><div class="form-field"><label>Token de autenticação</label><input type="password" readonly value="<?= $escape($settings['webhook_token']) ?>" autocomplete="off"></div></div></section><?php endif;?>
