<?php declare(strict_types=1); /** @var Closure(mixed):string $escape */ ?>
<header class="section-heading"><div><span class="status">Tickets</span><h1>Novo ticket</h1><p class="meta">Abra uma demanda interna e indique quem será responsável pelo atendimento.</p></div><a class="button-secondary" href="<?= $escape($basePath) ?>/tickets">Cancelar</a></header>
<?php if($error):?><p class="alert alert-danger"><?= $escape($error) ?></p><?php endif;?>
<section class="card"><div class="card-body"><form method="post" action="<?= $escape($basePath) ?>/tickets"><?= $csrfField ?><div class="form-grid">
<div class="form-field"><label for="ticket-unit">Unidade <span class="required">*</span></label><select id="ticket-unit" name="unit_id" required><option value="">Selecione</option><?php foreach($units as$unit):?><option value="<?= (int)$unit['id'] ?>"<?= (int)$selectedUnitId===(int)$unit['id']?' selected':'' ?>><?= $escape($unit['name']) ?></option><?php endforeach;?></select></div>
<div class="form-field"><label for="ticket-assigned">Responsável pelo ticket <span class="required">*</span></label><select id="ticket-assigned" name="assigned_user_id" required><option value="">Selecione</option></select><small class="meta">Usuário que receberá e atenderá esta demanda.</small></div>
<div class="form-field form-field-wide"><label for="ticket-contact-search">Aluno/Contato vinculado</label><input id="ticket-contact-search" list="ticket-contact-options" placeholder="Digite o nome, telefone ou e-mail" autocomplete="off"><input id="ticket-contact-id" name="crm_contact_id" type="hidden" value=""><datalist id="ticket-contact-options"></datalist><small class="meta">Opcional. A busca mostra somente cadastros da unidade escolhida.</small></div>
<div class="form-field"><label for="ticket-priority">Prioridade <span class="required">*</span></label><select id="ticket-priority" name="priority" required><option value="normal">Normal</option><option value="low">Baixa</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></div>
<div class="form-field"><label for="ticket-due">Prazo</label><input id="ticket-due" name="due_at" type="datetime-local" min="<?= date('Y-m-d\TH:i') ?>"></div>
<div class="form-field form-field-wide"><label for="ticket-subject">Assunto <span class="required">*</span></label><input id="ticket-subject" name="subject" maxlength="180" required></div>
<div class="form-field form-field-wide"><label for="ticket-description">Descrição da demanda <span class="required">*</span></label><textarea id="ticket-description" name="description" rows="7" maxlength="10000" required></textarea></div>
</div><div class="form-actions"><button class="button-primary" type="submit"><i class="fa-solid fa-ticket"></i> Abrir ticket</button></div></form></div></section>
<script>document.addEventListener('DOMContentLoaded',()=>{const responsibles=<?= json_encode($responsibles,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;const contacts=<?= json_encode(array_map(static fn(array $contact):array=>['id'=>(int)$contact['id'],'unit_id'=>(int)$contact['unit_id'],'name'=>(string)$contact['name'],'phone'=>(string)($contact['phone']??''),'email'=>(string)($contact['email']??'')],$contacts),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;const unit=document.querySelector('#ticket-unit');const assigned=document.querySelector('#ticket-assigned');const search=document.querySelector('#ticket-contact-search');const contactId=document.querySelector('#ticket-contact-id');const contactList=document.querySelector('#ticket-contact-options');if(!unit||!assigned||!search||!contactId||!contactList)return;let visibleContacts=[];const rebuild=()=>{const selected=Number(unit.value||0);assigned.replaceChildren(new Option('Selecione',''));responsibles.filter(user=>Number(user.unit_id)===selected).forEach(user=>assigned.add(new Option(user.name,String(user.id))));visibleContacts=contacts.filter(contact=>Number(contact.unit_id)===selected).map(contact=>({...contact,label:[contact.name,contact.phone,contact.email].filter(Boolean).join(' · ')}));contactList.replaceChildren(...visibleContacts.map(contact=>{const option=document.createElement('option');option.value=contact.label;return option;}));search.value='';contactId.value='';};const resolveContact=()=>{const match=visibleContacts.find(contact=>contact.label===search.value.trim());contactId.value=match?String(match.id):'';};unit.addEventListener('change',rebuild);search.addEventListener('input',resolveContact);search.addEventListener('change',resolveContact);rebuild();});</script>
