<?php declare(strict_types=1); /** @var Closure(mixed):string $escape */ ?>
<header class="section-heading"><div><span class="status">Tickets</span><h1>Novo ticket</h1><p class="meta">Abra uma demanda interna para o setor que deverá atendê-la.</p></div><a class="button-secondary" href="<?= $escape($basePath) ?>/tickets">Cancelar</a></header>
<?php if($error):?><p class="alert alert-danger"><?= $escape($error) ?></p><?php endif;?>
<section class="card"><div class="card-body"><form method="post" action="<?= $escape($basePath) ?>/tickets" enctype="multipart/form-data"><?= $csrfField ?><div class="form-grid">
<div class="form-field"><label for="ticket-unit">Unidade <span class="required">*</span></label><select id="ticket-unit" name="unit_id" required><option value="">Selecione</option><?php foreach($units as$unit):?><option value="<?= (int)$unit['id'] ?>"<?= (int)$selectedUnitId===(int)$unit['id']?' selected':'' ?>><?= $escape($unit['name']) ?></option><?php endforeach;?></select></div>
<div class="form-field"><label for="ticket-department">Setor <span class="required">*</span></label><select id="ticket-department" name="department_id" required><option value="">Selecione</option><?php foreach($departments as$department):?><option value="<?= (int)$department['id'] ?>"><?= $escape($department['name']) ?></option><?php endforeach;?></select><small class="meta">Equipe que receberá e atenderá a demanda.</small></div>
<div class="form-field form-field-wide ticket-contact-picker"><label for="ticket-contact-search">Aluno/Contato vinculado <span class="required">*</span></label><input id="ticket-contact-search" placeholder="Busque por nome, telefone ou e-mail" autocomplete="off" required><input id="ticket-contact-id" name="crm_contact_id" type="hidden" required><div class="ticket-contact-results" data-ticket-contact-results hidden></div><small class="meta" data-ticket-contact-help>Comece a digitar para localizar um cadastro da unidade escolhida.</small></div>
<div class="form-field"><label for="ticket-priority">Prioridade <span class="required">*</span></label><select id="ticket-priority" name="priority" required><option value="normal">Normal</option><option value="low">Baixa</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></div>
<div class="form-field"><label for="ticket-due">Prazo</label><input id="ticket-due" name="due_at" type="datetime-local" min="<?= date('Y-m-d\TH:i') ?>"></div>
<div class="form-field form-field-wide"><label for="ticket-subject">Assunto <span class="required">*</span></label><input id="ticket-subject" name="subject" maxlength="180" required></div>
<div class="form-field form-field-wide"><label for="ticket-description">Descrição da demanda <span class="required">*</span></label><textarea id="ticket-description" name="description" rows="7" maxlength="10000" required></textarea></div>
<div class="form-field form-field-wide"><label for="ticket-attachment">Anexar arquivo</label><input id="ticket-attachment" name="attachment" type="file" accept="image/jpeg,image/png,image/webp,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,audio/mpeg,audio/ogg,audio/mp4"><small class="meta">Imagem, PDF, Word ou áudio, com até 16 MB.</small></div>
</div><div class="form-actions"><button class="button-primary" type="submit"><i class="fa-solid fa-ticket"></i> Abrir ticket</button></div></form></div></section>
<script>(()=>{const initialize=()=>{const contacts=<?= json_encode(array_map(static fn(array $contact):array=>['id'=>(int)$contact['id'],'unit_id'=>(int)$contact['unit_id'],'name'=>(string)$contact['name'],'phone'=>(string)($contact['phone']??''),'email'=>(string)($contact['email']??'')],$contacts),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES) ?>;const unit=document.querySelector('#ticket-unit');const search=document.querySelector('#ticket-contact-search');const contactId=document.querySelector('#ticket-contact-id');const results=document.querySelector('[data-ticket-contact-results]');const help=document.querySelector('[data-ticket-contact-help]');if(!unit||!search||!contactId||!results||search.dataset.pickerReady==='1')return;search.dataset.pickerReady='1';const clear=()=>{contactId.value='';search.dataset.selected='';search.setCustomValidity('');};const render=()=>{clear();const term=search.value.trim().toLocaleLowerCase('pt-BR');const selected=Number(unit.value||0);results.replaceChildren();if(term.length<2||selected<1){results.hidden=true;return;}const matches=contacts.filter(contact=>Number(contact.unit_id)===selected&&[contact.name,contact.phone,contact.email].join(' ').toLocaleLowerCase('pt-BR').includes(term)).slice(0,12);matches.forEach(contact=>{const button=document.createElement('button');button.type='button';button.className='ticket-contact-option';const title=document.createElement('strong');title.textContent=contact.name;const meta=document.createElement('small');meta.textContent=[contact.phone,contact.email].filter(Boolean).join(' · ');button.append(title,meta);button.addEventListener('click',()=>{search.value=contact.name;search.dataset.selected='1';contactId.value=String(contact.id);results.hidden=true;if(help)help.textContent='Aluno/Contato selecionado: '+contact.name;});results.append(button);});if(matches.length===0){const empty=document.createElement('p');empty.className='meta';empty.textContent='Nenhum cadastro encontrado nesta unidade.';results.append(empty);}results.hidden=false;};unit.addEventListener('change',()=>{search.value='';clear();results.hidden=true;if(help)help.textContent='Comece a digitar para localizar um cadastro da unidade escolhida.';});search.addEventListener('input',render);search.addEventListener('focus',render);search.form?.addEventListener('submit',event=>{if(!contactId.value){event.preventDefault();search.setCustomValidity('Selecione um aluno ou contato na lista de resultados.');search.reportValidity();}else search.setCustomValidity('');});document.addEventListener('click',event=>{if(!event.target.closest('.ticket-contact-picker'))results.hidden=true;});};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',initialize,{once:true});else initialize();})();</script>
