<?php declare(strict_types=1); /** @var Closure(mixed):string $escape */
$ticketStudentsJson=json_encode(array_map(static fn(array $student):array=>['id'=>(int)$student['id'],'unit_id'=>(int)$student['unit_id'],'name'=>(string)$student['name'],'phone'=>(string)($student['phone']??''),'email'=>(string)($student['email']??''),'document'=>(string)($student['cpf_cnpj']??'')],$students),JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);
?>
<header class="section-heading"><div><span class="status">Tickets</span><h1>Novo ticket</h1><p class="meta">Abra uma demanda interna para o setor que deverá atendê-la.</p></div><a class="button-secondary" href="<?= $escape($basePath) ?>/tickets">Cancelar</a></header>
<?php if($error):?><p class="alert alert-danger"><?= $escape($error) ?></p><?php endif;?>
<section class="card"><div class="card-body"><form method="post" action="<?= $escape($basePath) ?>/tickets" enctype="multipart/form-data"><?= $csrfField ?><div class="form-grid">
<div class="form-field"><label for="ticket-unit">Unidade <span class="required">*</span></label><select id="ticket-unit" name="unit_id" required><option value="">Selecione</option><?php foreach($units as$unit):?><option value="<?= (int)$unit['id'] ?>"<?= (int)$selectedUnitId===(int)$unit['id']?' selected':'' ?>><?= $escape($unit['name']) ?></option><?php endforeach;?></select></div>
<div class="form-field"><label for="ticket-department">Setor <span class="required">*</span></label><select id="ticket-department" name="department_id" required><option value="">Selecione</option><?php foreach($departments as$department):?><option value="<?= (int)$department['id'] ?>"><?= $escape($department['name']) ?></option><?php endforeach;?></select><small class="meta">Equipe que receberá e atenderá a demanda.</small></div>
<div class="form-field form-field-wide ticket-contact-picker" data-ticket-students="<?= $escape($ticketStudentsJson?:'[]') ?>"><label for="ticket-contact-search">Aluno vinculado <span class="required">*</span></label><input id="ticket-contact-search" placeholder="Busque por nome, documento, telefone ou e-mail" autocomplete="off" required><input id="ticket-contact-id" name="finance_customer_id" type="hidden" required><div class="ticket-contact-results" data-ticket-contact-results hidden></div><small class="meta" data-ticket-contact-help>Consulte os alunos ativos do Financeiro da unidade escolhida.</small></div>
<div class="form-field"><label for="ticket-priority">Prioridade <span class="required">*</span></label><select id="ticket-priority" name="priority" required><option value="normal">Normal</option><option value="low">Baixa</option><option value="high">Alta</option><option value="urgent">Urgente</option></select></div>
<div class="form-field"><label for="ticket-due">Prazo</label><input id="ticket-due" name="due_at" type="datetime-local" min="<?= date('Y-m-d\TH:i') ?>"></div>
<div class="form-field form-field-wide"><label for="ticket-subject">Assunto <span class="required">*</span></label><input id="ticket-subject" name="subject" maxlength="180" required></div>
<div class="form-field form-field-wide"><label for="ticket-description">Descrição da demanda <span class="required">*</span></label><textarea id="ticket-description" name="description" rows="7" maxlength="10000" required></textarea></div>
<div class="form-field form-field-wide"><label for="ticket-attachment">Anexar arquivo</label><input id="ticket-attachment" name="attachment" type="file" accept="image/jpeg,image/png,image/webp,application/pdf,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document,audio/mpeg,audio/ogg,audio/mp4"><small class="meta">Imagem, PDF, Word ou áudio, com até 16 MB.</small></div>
</div><div class="form-actions"><button class="button-primary" type="submit"><i class="fa-solid fa-ticket"></i> Abrir ticket</button></div></form></div></section>
