<?php declare(strict_types=1); /** @var Closure(mixed):string $escape */ $statusNames=['open'=>'Aberto','in_progress'=>'Em andamento','waiting'=>'Aguardando','resolved'=>'Resolvido','closed'=>'Fechado'];$priorityNames=['low'=>'Baixa','normal'=>'Normal','high'=>'Alta','urgent'=>'Urgente']; ?>
<header class="section-heading"><div><span class="status">Ticket #<?= (int)$ticket['id'] ?> · <?= $escape($ticket['unit_name']) ?></span><h1><?= $escape($ticket['subject']) ?></h1><p class="meta">Aberto por <?= $escape($ticket['requester_name']) ?> em <?= $escape(date('d/m/Y H:i',strtotime($ticket['created_at']))) ?></p></div><a class="button-secondary" href="<?= $escape($basePath) ?>/tickets"><i class="fa-solid fa-arrow-left"></i> Voltar</a></header>
<?php if($message):?><p class="alert alert-success"><?= $escape($message) ?></p><?php endif;?><?php if($error):?><p class="alert alert-danger"><?= $escape($error) ?></p><?php endif;?>
<div class="ticket-detail-grid"><main>
<section class="ticket-description-card"><div class="ticket-detail-meta"><span class="ticket-priority priority-<?= $escape($ticket['priority']) ?>"><?= $escape($priorityNames[$ticket['priority']]) ?></span><span class="connection-badge"><?= $escape($statusNames[$ticket['status']]) ?></span><span><i class="fa-solid fa-people-group"></i> <?= $escape($ticket['department_name']) ?></span><?php if($ticket['due_at']):?><span><i class="fa-solid fa-clock"></i> <?= $escape(date('d/m/Y H:i',strtotime($ticket['due_at']))) ?></span><?php endif;?><?php if(!empty($ticket['finance_customer_id'])):?><a class="button-secondary" href="<?= $escape($basePath) ?>/finance/customers/<?= (int)$ticket['finance_customer_id'] ?>"><i class="fa-solid fa-user-graduate"></i> <?= $escape($ticket['contact_name']) ?></a><?php elseif(!empty($ticket['crm_contact_id'])):?><a class="button-secondary" href="<?= $escape($basePath) ?>/crm/contacts/<?= (int)$ticket['crm_contact_id'] ?>"><i class="fa-solid fa-user-tag"></i> <?= $escape($ticket['contact_name']) ?></a><?php endif;?></div><p><?= nl2br($escape($ticket['description'])) ?></p></section>
<section class="ticket-conversation"><h2>Conversa</h2><?php foreach($comments as$comment):?><article class="ticket-comment"><header><strong><?= $escape($comment['user_name']) ?></strong><small><?= $escape(date('d/m/Y H:i',strtotime($comment['created_at']))) ?></small></header><p><?= nl2br($escape($comment['body'])) ?></p></article><?php endforeach;?><?php if($comments===[]):?><p class="meta">Nenhum comentário ainda.</p><?php endif;?><form method="post" action="<?= $escape($basePath) ?>/tickets/<?= (int)$ticket['id'] ?>/comments"><?= $csrfField ?><label for="ticket-comment">Adicionar comentário <span class="required">*</span></label><textarea id="ticket-comment" name="body" rows="4" maxlength="10000" required></textarea><button class="button-primary" type="submit"><i class="fa-solid fa-paper-plane"></i> Enviar comentário</button></form></section>
</main><aside>
<section class="ticket-side-card"><h2>Setor responsável</h2><strong><?= $escape($ticket['department_name']) ?></strong></section>
<?php if($canChangeStatus):?><section class="ticket-side-card"><h2>Andamento</h2><form method="post" action="<?= $escape($basePath) ?>/tickets/<?= (int)$ticket['id'] ?>/status"><?= $csrfField ?><select name="status" required><?php foreach($statusNames as$value=>$label):?><option value="<?= $value ?>"<?= $ticket['status']===$value?' selected':'' ?>><?= $label ?></option><?php endforeach;?></select><button class="button-primary" type="submit">Atualizar status</button></form></section><?php endif;?>
<section class="ticket-side-card"><h2>Anexos</h2><?php if($attachments===[]):?><p class="meta">Nenhum arquivo anexado.</p><?php endif;?><?php foreach($attachments as$attachment):?><a class="ticket-attachment" href="<?= $escape($basePath) ?>/tickets/<?= (int)$ticket['id'] ?>/attachments/<?= (int)$attachment['id'] ?>"><i class="fa-solid fa-paperclip"></i><span><strong><?= $escape($attachment['file_name']) ?></strong><small><?= $escape($attachment['user_name']) ?> · <?= number_format((int)$attachment['file_size']/1024,1,',','.') ?> KB</small></span></a><?php endforeach;?><form method="post" enctype="multipart/form-data" action="<?= $escape($basePath) ?>/tickets/<?= (int)$ticket['id'] ?>/attachments"><?= $csrfField ?><input name="attachment" type="file" required><button class="button-secondary" type="submit"><i class="fa-solid fa-paperclip"></i> Anexar</button></form></section>
<section class="ticket-side-card"><h2>Histórico</h2><ol class="ticket-timeline"><?php foreach(array_reverse($events) as$event):?><li><strong><?= $escape($event['user_name']) ?></strong><span><?= $escape($eventLabels[$event['event_type']]??$event['event_type']) ?></span><small><?= $escape(date('d/m/Y H:i',strtotime($event['created_at']))) ?></small></li><?php endforeach;?></ol></section>
</aside></div>
