<a class="nav-link" href="<?= $escape($basePath) ?>/"><i class="fa-solid fa-house fa-fw" aria-hidden="true"></i>Visão geral</a>
<?php if (!empty($isCentralContext)): ?>
  <a class="nav-link" href="<?= $escape($basePath) ?>/admin/organizations"><i class="fa-solid fa-network-wired fa-fw" aria-hidden="true"></i>Franquias</a>
  <details class="nav-group" <?= $admOpen ? 'open' : '' ?>>
    <summary><span><i class="fa-solid fa-gear fa-fw" aria-hidden="true"></i>ADM</span></summary>
    <div class="nav-submenu">
      <?php if ($navigation['users'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/users"><i class="fa-solid fa-user-tie fa-fw" aria-hidden="true"></i>Colaboradores</a><?php endif; ?>
      <?php if ($navigation['roles'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/roles"><i class="fa-solid fa-user-shield fa-fw" aria-hidden="true"></i>Perfis e permissões</a><?php endif; ?>
    </div>
  </details>
<?php else: ?>
  <?php if (($navigation['crm'] ?? false)||($navigation['whatsapp']??false)): ?><details class="nav-group" <?= $crmOpen||str_contains($currentPath,'/whatsapp') ? 'open' : '' ?>><summary><span><i class="fa-solid fa-chart-line fa-fw"></i>CRM</span></summary><div class="nav-submenu"><?php if($navigation['crm']??false):?><a class="nav-link" href="<?= $escape($basePath) ?>/crm/contacts"><i class="fa-solid fa-user-tag fa-fw"></i>Leads</a><?php endif;?><?php if($navigation['whatsapp']??false):?><a class="nav-link" href="<?= $escape($basePath) ?>/whatsapp"><i class="fa-solid fa-comments fa-fw"></i>WhatsApp<?php if((int)($whatsappAlerts['unread']??0)>0):?><span class="nav-count"><?= (int)$whatsappAlerts['unread'] ?></span><?php endif;?></a><?php endif;?></div></details><?php endif;?>
  <?php if ($navigation['finance'] ?? false): ?><details class="nav-group" <?= $studentsOpen||str_contains($currentPath,'/tickets') ? 'open' : '' ?>><summary><span><i class="fa-solid fa-graduation-cap fa-fw"></i>ALUNOS</span></summary><div class="nav-submenu"><a class="nav-link" href="<?= $escape($basePath) ?>/students"><i class="fa-solid fa-magnifying-glass fa-fw"></i>Consultar</a><a class="nav-link" href="<?= $escape($basePath) ?>/finance/customers/create"><i class="fa-solid fa-user-plus fa-fw"></i>Cadastro</a><?php if($navigation['finance_manage']??false):?><a class="nav-link" href="<?= $escape($basePath) ?>/students/enrollments"><i class="fa-solid fa-graduation-cap fa-fw"></i>Matrículas</a><?php endif;?><a class="nav-link" href="<?= $escape($basePath) ?>/students/pedagogical"><i class="fa-solid fa-chalkboard-user fa-fw"></i>Pedagógico</a><a class="nav-link" href="<?= $escape($basePath) ?>/finance/customers"><i class="fa-solid fa-wallet fa-fw"></i>Financeiro</a><?php if($navigation['tickets']??false):?><a class="nav-link" href="<?= $escape($basePath) ?>/tickets"><i class="fa-solid fa-ticket fa-fw"></i>Tickets<?php if((int)($ticketAlerts['unread']??0)>0):?><span class="nav-count"><?= (int)$ticketAlerts['unread'] ?></span><?php endif;?></a><?php endif;?></div></details><?php endif;?>
  <?php if (($navigation['users'] ?? false) || ($navigation['units'] ?? false) || ($navigation['roles'] ?? false) || ($navigation['tags'] ?? false) || ($navigation['statuses'] ?? false) || ($navigation['external_forms'] ?? false) || ($navigation['whatsapp_lines'] ?? false) || ($navigation['whatsapp_templates'] ?? false) || ($navigation['ticket_departments'] ?? false)): ?><details class="nav-group" <?= $admOpen ? 'open' : '' ?>><summary><span><i class="fa-solid fa-gear fa-fw" aria-hidden="true"></i>ADM</span></summary><div class="nav-submenu"><?php if ($navigation['users'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/users"><i class="fa-solid fa-users fa-fw" aria-hidden="true"></i>Usuários</a><?php endif; ?><?php if ($navigation['units'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/units"><i class="fa-solid fa-building fa-fw" aria-hidden="true"></i>Unidades</a><?php endif; ?><?php if ($navigation['roles'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/roles"><i class="fa-solid fa-user-shield fa-fw" aria-hidden="true"></i>Perfis e permissões</a><?php endif; ?><?php if ($navigation['tags'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/tags"><i class="fa-solid fa-tags fa-fw" aria-hidden="true"></i>Etiquetas</a><?php endif; ?><?php if ($navigation['statuses'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/statuses"><i class="fa-solid fa-list-check fa-fw" aria-hidden="true"></i>Status do CRM</a><?php endif; ?><?php if ($navigation['external_forms'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/external-forms"><i class="fa-solid fa-globe fa-fw" aria-hidden="true"></i>Sites externos</a><?php endif; ?><?php if ($navigation['whatsapp_lines'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/whatsapp/lines"><i class="fa-solid fa-sim-card fa-fw" aria-hidden="true"></i>Linhas do WhatsApp</a><?php endif; ?><?php if ($navigation['whatsapp_templates'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/whatsapp/templates"><i class="fa-solid fa-file-lines fa-fw" aria-hidden="true"></i>Modelos do WhatsApp</a><?php endif; ?><?php if ($navigation['ticket_departments'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/ticket-departments"><i class="fa-solid fa-people-group fa-fw" aria-hidden="true"></i>Setores</a><?php endif; ?></div></details><?php endif; ?>
  <div class="adm-extensions"><?php if ($navigation['finance_products'] ?? false): ?><a class="nav-link adm-extension" href="<?= $escape($basePath) ?>/admin/finance/products"><i class="fa-solid fa-book-open fa-fw"></i>Cursos e preços</a><?php endif; ?><?php if ($navigation['finance_campaigns'] ?? false): ?><a class="nav-link adm-extension" href="<?= $escape($basePath) ?>/admin/finance/campaigns"><i class="fa-solid fa-bullhorn fa-fw"></i>Campanhas</a><?php endif; ?><?php if($navigation['moodle_settings']??false):?><a class="nav-link adm-extension" href="<?= $escape($basePath) ?>/admin/ava"><i class="fa-solid fa-graduation-cap fa-fw"></i>AVA</a><?php endif;?><?php if(($navigation['finance_settings']??false)||($navigation['moodle_settings']??false)):?><a class="nav-link adm-extension" href="<?= $escape($basePath) ?>/admin/integrations"><i class="fa-solid fa-plug fa-fw"></i>Integrações</a><?php endif;?></div>
<?php endif; ?>
