<a class="nav-link" href="<?= $escape($basePath) ?>/"><i class="fa-solid fa-house fa-fw" aria-hidden="true"></i>Visão geral</a>
<?php if (!empty($isCentralContext)): ?>
  <details class="nav-group" <?= $franchisesOpen ? 'open' : '' ?>>
    <summary><span><i class="fa-solid fa-network-wired fa-fw" aria-hidden="true"></i>FRANQUIAS</span></summary>
    <div class="nav-submenu">
      <a class="nav-link" href="<?= $escape($basePath) ?>/admin/organizations"><i class="fa-solid fa-magnifying-glass fa-fw" aria-hidden="true"></i>Consultar</a>
      <a class="nav-link" href="<?= $escape($basePath) ?>/admin/organizations/create"><i class="fa-solid fa-plus fa-fw" aria-hidden="true"></i>Cadastro</a>
      <a class="nav-link" href="<?= $escape($basePath) ?>/admin/franchise-applications"><i class="fa-solid fa-file-signature fa-fw" aria-hidden="true"></i>Solicitações</a>
      <a class="nav-link" href="<?= $escape($basePath) ?>/admin/franchise-contracts"><i class="fa-solid fa-signature fa-fw" aria-hidden="true"></i>Contratos</a>
      <a class="nav-link" href="<?= $escape($basePath) ?>/admin/franchise-billing"><i class="fa-solid fa-money-bill-transfer fa-fw" aria-hidden="true"></i>Financeiro</a>
    </div>
  </details>
  <a class="nav-link" href="<?= $escape($basePath) ?>/admin/tickets"><i class="fa-solid fa-ticket fa-fw" aria-hidden="true"></i>TICKETS</a>
  <details class="nav-group" <?= $admOpen ? 'open' : '' ?>>
    <summary><span><i class="fa-solid fa-gear fa-fw" aria-hidden="true"></i>ADM</span></summary>
    <div class="nav-submenu">
      <?php if ($navigation['users'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/users"><i class="fa-solid fa-user-tie fa-fw" aria-hidden="true"></i>Colaboradores</a><?php endif; ?>
      <?php if ($navigation['roles'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/roles"><i class="fa-solid fa-user-shield fa-fw" aria-hidden="true"></i>Perfis e permissões</a><?php endif; ?>
      <a class="nav-link" href="<?= $escape($basePath) ?>/admin/platform/branding"><i class="fa-solid fa-palette fa-fw" aria-hidden="true"></i>Personalização</a>
      <a class="nav-link" href="<?= $escape($basePath) ?>/admin/document-types"><i class="fa-solid fa-folder-tree fa-fw" aria-hidden="true"></i>Documentos</a>
       <a class="nav-link" href="<?= $escape($basePath) ?>/admin/platform/integrations"><i class="fa-solid fa-plug fa-fw" aria-hidden="true"></i>Integrações</a>
    </div>
  </details>
  <?php if ($navigation['users'] ?? false): ?><details class="nav-group" <?= $portalOpen ? 'open' : '' ?>><summary><span><i class="fa-solid fa-user-graduate fa-fw"></i>PORTAL DO ALUNO</span></summary><div class="nav-submenu"><a class="nav-link" href="<?= $escape($basePath) ?>/admin/portal"><i class="fa-solid fa-bullhorn fa-fw"></i>Comunicados</a><a class="nav-link" href="<?= $escape($basePath) ?>/admin/portal/tabs"><i class="fa-solid fa-table-columns fa-fw"></i>Abas e seções</a><a class="nav-link" href="<?= $escape($basePath) ?>/admin/portal/materials"><i class="fa-solid fa-book-open fa-fw"></i>Materiais</a><a class="nav-link" href="<?= $escape($basePath) ?>/admin/portal/satisfaction"><i class="fa-solid fa-star fa-fw"></i>Satisfação</a></div></details><?php endif; ?>
<?php else: ?>
  <?php if (($navigation['crm'] ?? false)||($navigation['whatsapp']??false)): ?><details class="nav-group" <?= $crmOpen||str_contains($currentPath,'/whatsapp') ? 'open' : '' ?>><summary><span><i class="fa-solid fa-chart-line fa-fw"></i>CRM</span></summary><div class="nav-submenu"><?php if($navigation['crm']??false):?><a class="nav-link" href="<?= $escape($basePath) ?>/crm/contacts"><i class="fa-solid fa-user-tag fa-fw"></i>Leads</a><?php endif;?><?php if($navigation['whatsapp']??false):?><a class="nav-link" href="<?= $escape($basePath) ?>/whatsapp"><i class="fa-solid fa-comments fa-fw"></i>WhatsApp<?php if((int)($whatsappAlerts['unread']??0)>0):?><span class="nav-count"><?= (int)$whatsappAlerts['unread'] ?></span><?php endif;?></a><?php endif;?></div></details><?php endif;?>
  <?php if ($navigation['finance'] ?? false): ?><details class="nav-group" <?= $studentsOpen||str_contains($currentPath,'/tickets') ? 'open' : '' ?>><summary><span><i class="fa-solid fa-graduation-cap fa-fw"></i>ALUNOS</span></summary><div class="nav-submenu"><a class="nav-link" href="<?= $escape($basePath) ?>/students"><i class="fa-solid fa-magnifying-glass fa-fw"></i>Consultar</a><a class="nav-link" href="<?= $escape($basePath) ?>/finance/customers/create"><i class="fa-solid fa-user-plus fa-fw"></i>Cadastro</a><?php if($navigation['finance_manage']??false):?><a class="nav-link" href="<?= $escape($basePath) ?>/students/enrollments"><i class="fa-solid fa-graduation-cap fa-fw"></i>Matrículas</a><?php endif;?><a class="nav-link" href="<?= $escape($basePath) ?>/students/pedagogical"><i class="fa-solid fa-chalkboard-user fa-fw"></i>Pedagógico</a><a class="nav-link" href="<?= $escape($basePath) ?>/finance/customers"><i class="fa-solid fa-wallet fa-fw"></i>Financeiro</a><?php if($navigation['tickets']??false):?><a class="nav-link" href="<?= $escape($basePath) ?>/tickets"><i class="fa-solid fa-ticket fa-fw"></i>Tickets<?php if((int)($ticketAlerts['unread']??0)>0):?><span class="nav-count"><?= (int)$ticketAlerts['unread'] ?></span><?php endif;?></a><?php endif;?></div></details><?php endif;?>
  <?php if ($navigation['users'] ?? false): ?><details class="nav-group" <?= $portalOpen ? 'open' : '' ?>><summary><span><i class="fa-solid fa-user-graduate fa-fw"></i>PORTAL DO ALUNO</span></summary><div class="nav-submenu"><a class="nav-link" href="<?= $escape($basePath) ?>/admin/portal"><i class="fa-solid fa-bullhorn fa-fw"></i>Comunicados</a><a class="nav-link" href="<?= $escape($basePath) ?>/admin/portal/tabs"><i class="fa-solid fa-table-columns fa-fw"></i>Abas e seções</a><a class="nav-link" href="<?= $escape($basePath) ?>/admin/portal/materials"><i class="fa-solid fa-book-open fa-fw"></i>Materiais</a><a class="nav-link" href="<?= $escape($basePath) ?>/admin/portal/satisfaction"><i class="fa-solid fa-star fa-fw"></i>Satisfação</a></div></details><?php endif; ?>
  <?php if (($navigation['users'] ?? false) || ($navigation['roles'] ?? false) || ($navigation['tags'] ?? false) || ($navigation['statuses'] ?? false) || ($navigation['external_forms'] ?? false) || ($navigation['whatsapp_lines'] ?? false) || ($navigation['whatsapp_templates'] ?? false) || ($navigation['ticket_departments'] ?? false) || ($navigation['site'] ?? false)): ?>
    <details class="nav-group" <?= $admOpen ? 'open' : '' ?>><summary><span><i class="fa-solid fa-gear fa-fw" aria-hidden="true"></i>ADM</span></summary><div class="nav-submenu">
      <?php if ($navigation['users'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/users"><i class="fa-solid fa-users fa-fw" aria-hidden="true"></i>Usuários</a><?php endif; ?>
      <?php if ($navigation['roles'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/roles"><i class="fa-solid fa-user-shield fa-fw" aria-hidden="true"></i>Perfis e permissões</a><?php endif; ?>
      <?php if ($navigation['tags'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/tags"><i class="fa-solid fa-tags fa-fw" aria-hidden="true"></i>Etiquetas</a><?php endif; ?>
      <?php if ($navigation['statuses'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/statuses"><i class="fa-solid fa-list-check fa-fw" aria-hidden="true"></i>Status do CRM</a><?php endif; ?>
      <?php if ($navigation['external_forms'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/external-forms"><i class="fa-solid fa-globe fa-fw" aria-hidden="true"></i>Sites externos</a><?php endif; ?>
      <?php if ($navigation['whatsapp_lines'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/whatsapp/lines"><i class="fa-solid fa-sim-card fa-fw" aria-hidden="true"></i>Linhas do WhatsApp</a><?php endif; ?>
      <?php if ($navigation['whatsapp_templates'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/whatsapp/templates"><i class="fa-solid fa-file-lines fa-fw" aria-hidden="true"></i>Modelos do WhatsApp</a><?php endif; ?>
      <?php if ($navigation['ticket_departments'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/ticket-departments"><i class="fa-solid fa-people-group fa-fw" aria-hidden="true"></i>Setores</a><?php endif; ?>
      <?php if ($navigation['site'] ?? false): ?><a class="nav-link" href="<?= $escape($basePath) ?>/admin/site"><i class="fa-solid fa-store fa-fw" aria-hidden="true"></i>Site Institucional</a><?php endif; ?>
    </div></details>
  <?php endif; ?>
<?php endif; ?>
