<?php
declare(strict_types=1);
/** @var Closure(mixed): string $escape */
$editing=$contact!==null;
$draft=$contact??$prefill??[];
$registered=$editing?date('Y-m-d\TH:i',strtotime((string)$contact['registered_at'])):date('Y-m-d\TH:i');
$selectedStatusId=(int)($draft['status_id']??($statuses[0]['id']??0));
$selectedResponsibleId=(int)($draft['responsible_user_id']??$currentUser->id);
$required='<span class="required-mark">*</span>';
?>
<span class="status">Alunos · Cadastro</span><h1><?= $editing?'Editar contato':'Novo contato' ?></h1>
<?php if($error):?><p class="alert alert-danger"><?= $escape($error) ?></p><?php endif;?>
<form id="contact-form" method="post" action="<?= $escape($basePath) ?>/crm/contacts<?= $editing?'/'.$escape($contact['id']):'' ?>" data-contact-unit-form><?= $csrfField ?><?php if(!$editing&&(int)($draft['whatsapp_conversation_id']??0)>0):?><input type="hidden" name="whatsapp_conversation_id" value="<?= (int)$draft['whatsapp_conversation_id'] ?>"><?php endif;?>
<?php if($editing):?><input type="hidden" name="unit_id" value="<?= $selectedUnitId ?>"><?php endif;?><label>Unidade <?= $required ?><select class="form-select" <?= $editing?'name="unit_id_display" disabled':'name="unit_id" required' ?> data-contact-unit><option value="">Selecione a unidade</option><?php foreach($availableUnits as$availableUnit):?><option value="<?= (int)$availableUnit['id'] ?>" <?= $selectedUnitId===(int)$availableUnit['id']?'selected':'' ?>><?= $escape($availableUnit['name']) ?></option><?php endforeach;?></select><?php if($editing):?><small>A unidade do contato é preservada durante a edição.</small><?php else:?><small>Esta unidade definirá quem poderá visualizar e atender o contato.</small><?php endif;?></label>
<div class="row"><div class="col-sm-6"><label>Status <?= $required ?></label><details class="tag-dropdown status-dropdown"><summary>Selecionar status</summary><div class="tag-dropdown-menu status-options"><?php foreach($statuses as $statusOption):?><label><input type="radio" name="status_id" value="<?= $escape($statusOption['id']) ?>" <?= $selectedStatusId===(int)$statusOption['id']?'checked':'' ?> required><span class="tag-badge" style="--tag-color:<?= $escape($statusOption['color']) ?>"><?= $escape($statusOption['name']) ?></span></label><?php endforeach;?></div></details></div>
<div class="col-sm-6"><label>Etiquetas <?= $required ?></label><details class="tag-dropdown tags-dropdown"><summary><?= $selectedTags===[]?'Selecionar etiquetas':$escape(count($selectedTags).' etiqueta(s) selecionada(s)') ?></summary><div class="tag-dropdown-menu"><?php if($tags===[]):?><p class="meta">Nenhuma etiqueta disponível.</p><?php endif;?><?php foreach($tags as $tag):?><label><input type="checkbox" name="tags[]" value="<?= $escape($tag['id']) ?>" <?= in_array((int)$tag['id'],$selectedTags,true)?'checked':'' ?>><span class="tag-badge" style="--tag-color:<?= $escape($tag['color']) ?>"><?= $escape($tag['name']) ?></span></label><?php endforeach;?></div></details></div></div>
<label>Nome <?= $required ?><input name="name" required minlength="2" maxlength="160" value="<?= $escape($draft['name']??'') ?>"></label>
<div class="row"><div class="col-sm-6"><label>Telefone/WhatsApp <?= $required ?><input name="phone" required inputmode="tel" autocomplete="tel" minlength="14" maxlength="16" data-mask="phone" placeholder="(00) 00000-0000" value="<?= $escape($draft['phone']??'') ?>"></label></div><div class="col-sm-6"><label>E-mail <?= $required ?><input name="email" required type="email" autocomplete="email" maxlength="190" data-normalize="email" placeholder="nome@exemplo.com.br" value="<?= $escape($draft['email']??'') ?>"></label></div></div>
<div class="row"><div class="col-sm-6"><label>CPF/CNPJ <?= $required ?><input name="document" required inputmode="numeric" minlength="14" maxlength="18" data-mask="document" placeholder="000.000.000-00" value="<?= $escape($contact['document']??'') ?>"></label></div><div class="col-sm-6"><label>Curso <?= $required ?><input name="course" required maxlength="160" value="<?= $escape($contact['course']??'') ?>"></label></div></div>
<div class="row"><div class="col-sm-6"><label>Interesse (0 a 10) <?= $required ?><input name="interest_score" required type="number" min="0" max="10" value="<?= $escape($contact['interest_score']??'') ?>"></label></div><div class="col-sm-6"><label>Polo/Cidade <?= $required ?><select class="form-select" name="origin_city" required><option value="">Selecione</option><?php foreach($poles as $pole):?><option value="<?= $escape($pole['name']) ?>" <?= ($contact['origin_city']??'')===$pole['name']?'selected':'' ?>><?= $escape($pole['name']) ?><?= $pole['city']!==$pole['name']?' — '.$escape($pole['city']):'' ?></option><?php endforeach;?></select></label></div></div>
<div class="row"><div class="col-sm-6"><label>Atendente <?= $required ?><select class="form-select" name="responsible_user_id" data-contact-responsible required><option value="">Selecione a unidade primeiro</option><?php foreach($responsibles as $person):?><option value="<?= $escape($person['id']) ?>" data-unit-ids="<?= $escape(implode(',',array_unique($person['unit_ids']))) ?>" <?= $selectedResponsibleId===(int)$person['id']?'selected':'' ?>><?= $escape($person['name']) ?></option><?php endforeach;?></select></label></div><div class="col-sm-6"><label>Origem do cadastro <?= $required ?><select class="form-select" name="registration_source" required><option value="internal" <?= ($contact['registration_source']??'internal')==='internal'?'selected':'' ?>>Cadastro interno</option><option value="external_form" <?= ($contact['registration_source']??'')==='external_form'?'selected':'' ?>>Site externo</option></select></label></div></div>
<label>Data e hora <?= $required ?><input name="registered_at" type="datetime-local" required value="<?= $escape($registered) ?>"></label>
<label>Observações <?= $required ?><textarea name="notes" required minlength="2" rows="4" maxlength="5000"><?= $escape($contact['notes']??'') ?></textarea></label><div class="checks"><label><input type="checkbox" name="is_active" value="1" <?= !$editing||(int)$contact['is_active']===1?'checked':'' ?>>Contato ativo</label></div><button type="submit">Salvar contato</button></form><p><a href="<?= $escape($basePath) ?>/crm/contacts">Cancelar</a></p>
