<?php declare(strict_types=1); /** @var Closure(mixed): string $escape */ $editing=$contact!==null; $registered=$editing?date('Y-m-d\TH:i',strtotime((string)$contact['registered_at'])):date('Y-m-d\TH:i'); ?>
<span class="status">CRM · <?= $escape($unit['name']) ?></span><h1><?= $editing?'Editar contato':'Novo contato' ?></h1>
<?php if($error):?><p class="alert alert-danger"><?= $escape($error) ?></p><?php endif;?>
<form method="post" action="<?= $escape($basePath) ?>/crm/contacts<?= $editing?'/'.$escape($contact['id']):'' ?>" novalidate><?= $csrfField ?>
<label>Nome<input name="name" required maxlength="160" value="<?= $escape($contact['name']??'') ?>"></label>
<div class="row"><div class="col-sm-6"><label>Telefone/WhatsApp<input name="phone" maxlength="32" value="<?= $escape($contact['phone']??'') ?>"></label></div><div class="col-sm-6"><label>E-mail<input name="email" type="email" maxlength="190" value="<?= $escape($contact['email']??'') ?>"></label></div></div>
<div class="row"><div class="col-sm-6"><label>CPF/CNPJ<input name="document" maxlength="24" value="<?= $escape($contact['document']??'') ?>"></label></div><div class="col-sm-6"><label>Curso<input name="course" maxlength="160" value="<?= $escape($contact['course']??'') ?>"></label></div></div>
<div class="row"><div class="col-sm-6"><label>Status<select class="form-select" name="status_id" required><?php foreach($statuses as $status):?><option value="<?= $escape($status['id']) ?>" <?= (int)($contact['status_id']??$statuses[0]['id'])===(int)$status['id']?'selected':'' ?>><?= $escape($status['name']) ?></option><?php endforeach;?></select></label></div><div class="col-sm-6"><label>Interesse (0 a 10)<input name="interest_score" type="number" min="0" max="10" value="<?= $escape($contact['interest_score']??'') ?>"></label></div></div>
<div class="row"><div class="col-sm-6"><label>Polo/cidade de origem<input name="origin_city" maxlength="120" value="<?= $escape($contact['origin_city']??'') ?>"></label></div><div class="col-sm-6"><label>Responsável<select class="form-select" name="responsible_user_id"><option value="">Não definido</option><?php foreach($responsibles as $person):?><option value="<?= $escape($person['id']) ?>" <?= (int)($contact['responsible_user_id']??0)===(int)$person['id']?'selected':'' ?>><?= $escape($person['name']) ?></option><?php endforeach;?></select></label></div></div>
<div class="row"><div class="col-sm-6"><label>Origem do cadastro<select class="form-select" name="registration_source"><option value="internal" <?= ($contact['registration_source']??'internal')==='internal'?'selected':'' ?>>Cadastro interno</option><option value="external_form" <?= ($contact['registration_source']??'')==='external_form'?'selected':'' ?>>Formulário externo</option></select></label></div><div class="col-sm-6"><label>Data e hora<input name="registered_at" type="datetime-local" required value="<?= $escape($registered) ?>"></label></div></div>
<label>Observações<textarea name="notes" rows="4" maxlength="5000"><?= $escape($contact['notes']??'') ?></textarea></label><div class="checks"><label><input type="checkbox" name="is_active" value="1" <?= !$editing||(int)$contact['is_active']===1?'checked':'' ?>>Contato ativo</label></div><button type="submit">Salvar contato</button></form><p><a href="<?= $escape($basePath) ?>/crm/contacts">Cancelar</a></p>
