<?php
$centralPrice=$catalog['central_default_price']??null;
$trailPrice=$catalog['central_trail_default_price']??null;
$moduleWorkload=$catalog['central_default_module_workload']??null;
$trailWorkload=$catalog['central_default_trail_workload']??null;
$moduleInstallments=max(1,(int)($catalog['central_default_max_installments']??1));
$trailInstallments=max(1,(int)($catalog['central_trail_default_max_installments']??$moduleInstallments));
$franchiseOverrideAllowed=(int)($catalog['allow_franchise_commercial_override']??1)===1;
$priceOverrideAllowed=(int)($catalog['allow_franchise_price_override']??1)===1;
$installmentOverrideAllowed=(int)($catalog['allow_franchise_installment_override']??1)===1;
$visibilityOverrideAllowed=(int)($catalog['allow_franchise_visibility_override']??1)===1;
?>
<div class="catalog-subpanel" data-catalog-subpanel="<?= $escape($provider) ?>:policy" hidden>
 <section class="central-policy-shell">
  <header><div><p class="eyebrow">Governança comercial</p><h3>Política da rede e das franquias</h3><p>Defina os padrões herdados por Módulos e Trilhas. Salvar não altera ofertas existentes; a aplicação em lote continua sendo uma ação separada.</p></div><span class="catalog-badge <?= $franchiseOverrideAllowed?'ok':'private' ?>"><i class="fa-solid <?= $franchiseOverrideAllowed?'fa-pen':'fa-lock' ?>"></i> <?= $franchiseOverrideAllowed?'Exceções controladas':'Regra central bloqueada' ?></span></header>
  <form method="post" action="<?= $escape($basePath) ?>/admin/platform/integrations/course-providers/catalogs/<?= (int)$catalog['id'] ?>/commercial-policy">
   <?= $csrfField ?><input type="hidden" name="provider" value="<?= $escape($provider) ?>">
   <div class="policy-kind-grid">
    <section class="policy-kind-card"><div class="policy-kind-title"><i class="fa-solid fa-cubes-stacked"></i><div><strong>Módulos</strong><small>Padrão dos cursos comercializados individualmente.</small></div></div><div class="policy-kind-fields"><label><span>Preço padrão (R$)</span><input inputmode="decimal" name="default_price" value="<?= $centralPrice!==null?$escape(number_format((float)$centralPrice,2,',','')):'' ?>" placeholder="Ex.: 149,90"></label><label><span>Carga horária padrão</span><input type="number" min="1" step="1" inputmode="numeric" name="module_workload" value="<?= $moduleWorkload!==null?(int)round((float)$moduleWorkload):'' ?>" placeholder="Ex.: 20"></label><label><span>Parcelamento máximo</span><input type="number" min="1" max="60" name="module_max_installments" value="<?= $moduleInstallments ?>"></label></div></section>
    <section class="policy-kind-card"><div class="policy-kind-title"><i class="fa-solid fa-route"></i><div><strong>Trilhas</strong><small>Padrão dos pacotes formados por dois ou mais Módulos.</small></div></div><div class="policy-kind-fields"><label><span>Preço padrão (R$)</span><input inputmode="decimal" name="trail_default_price" value="<?= $trailPrice!==null?$escape(number_format((float)$trailPrice,2,',','')):'' ?>" placeholder="Ex.: 399,90"></label><label><span>Carga horária padrão</span><input type="number" min="1" step="1" inputmode="numeric" name="trail_workload" value="<?= $trailWorkload!==null?(int)round((float)$trailWorkload):'' ?>" placeholder="Ex.: 80"></label><label><span>Parcelamento máximo</span><input type="number" min="1" max="60" name="trail_max_installments" value="<?= $trailInstallments ?>"></label></div></section>
   </div>
   <section class="policy-network-card"><div><h4>Herança e autonomia da franquia</h4><p>Escolha exatamente o que poderá ser personalizado no ADM da Franquia.</p></div><div class="policy-permission-grid"><label><input type="checkbox" name="allow_franchise_override" value="1" <?= $franchiseOverrideAllowed?'checked':'' ?>><span><strong>Permitir exceções</strong><small>Habilita a personalização controlada.</small></span></label><label><input type="checkbox" name="allow_price_override" value="1" <?= $priceOverrideAllowed?'checked':'' ?>><span><strong>Preço</strong><small>A franquia pode definir outro valor.</small></span></label><label><input type="checkbox" name="allow_installment_override" value="1" <?= $installmentOverrideAllowed?'checked':'' ?>><span><strong>Parcelamento</strong><small>A franquia pode ajustar as parcelas.</small></span></label><label><input type="checkbox" name="allow_visibility_override" value="1" <?= $visibilityOverrideAllowed?'checked':'' ?>><span><strong>Visibilidade</strong><small>A franquia pode ocultar ofertas locais.</small></span></label></div></section>
   <div class="central-policy-grid policy-validity-grid"><label><span>Válida a partir de</span><input type="date" name="valid_from" value="<?= $escape((string)($catalog['central_valid_from']??'')) ?>"><small>Vazio aplica imediatamente.</small></label><label><span>Válida até</span><input type="date" name="valid_until" value="<?= $escape((string)($catalog['central_valid_until']??'')) ?>"><small>Vazio mantém a regra sem prazo.</small></label><label class="central-policy-target"><span>Aplicar o padrão em</span><select name="organization_id"><option value="0">Todas as franquias ativas</option><?php foreach($organizationRows as$organization):?><option value="<?= (int)$organization['id'] ?>"><?= $escape((string)($organization['display_name']?:$organization['legal_name'])) ?></option><?php endforeach;?></select><small>A aplicação preserva bloqueios específicos.</small></label></div>
   <div class="catalog-lifecycle"><span class="is-done">Sincronizado</span><i class="fa-solid fa-arrow-right"></i><span>Dados incompletos</span><i class="fa-solid fa-arrow-right"></i><span>Curadoria/IA</span><i class="fa-solid fa-arrow-right"></i><span>Pronto para publicar</span><i class="fa-solid fa-arrow-right"></i><span>Publicado</span></div>
   <footer class="central-policy-actions"><span><i class="fa-solid fa-shield-halved"></i> As cargas horárias são sugestões para novos cadastros e não alteram títulos já revisados.</span><div><button class="btn btn-secondary" type="submit" name="policy_action" value="save"><i class="fa-solid fa-floppy-disk"></i> Salvar política</button><button class="btn btn-primary" type="submit" name="policy_action" value="apply" onclick="return confirm('Aplicar esta política ao destino selecionado?')"><i class="fa-solid fa-wand-magic-sparkles"></i> Salvar e aplicar</button></div></footer>
  </form>
 </section>
</div>
