<?php if($isInter):?>
<section class="catalog-subpanel catalog-overview-panel" data-catalog-subpanel="<?= $escape($provider) ?>:commercial" hidden>
 <div class="catalog-area-hero"><span class="catalog-icon"><i class="fa-solid fa-store"></i></span><div><span class="eyebrow">Loja de Cursos</span><h3>Vitrine da Formação INTER</h3><p>Visão consolidada dos títulos recebidos do AVA Cursos. A curadoria comercial e a disponibilidade para as franquias permanecem centralizadas.</p></div></div>
 <div class="catalog-summary wide-summary"><article class="catalog-stat"><small>Títulos sincronizados</small><strong><?= (int)($catalog['course_count']??0) ?></strong></article><article class="catalog-stat"><small>Franquias com acesso</small><strong><?= (int)($catalog['organization_count']??0) ?></strong></article></div>
</section>
<section class="catalog-subpanel catalog-overview-panel" data-catalog-subpanel="<?= $escape($provider) ?>:courses" hidden>
 <div class="catalog-area-hero"><span class="catalog-icon"><i class="fa-solid fa-graduation-cap"></i></span><div><span class="eyebrow">Módulos</span><h3>Conteúdo acadêmico da Formação INTER</h3><p>Os módulos são administrados no AVA Cursos e reutilizados pelas franquias autorizadas, sem duplicar o conteúdo acadêmico.</p></div></div>
 <div class="catalog-actions"><a class="btn btn-primary" href="<?= $escape((string)($catalog['ava_url']?:'https://avacursos.com.br')) ?>" target="_blank" rel="noopener"><i class="fa-solid fa-arrow-up-right-from-square"></i> Abrir AVA Cursos</a></div>
</section>
<?php endif;?>

<?php if(!$isInter&&$provider!=='iesde'):?>
<section class="catalog-subpanel catalog-overview-panel" data-catalog-subpanel="<?= $escape($provider) ?>:commercial" hidden>
 <div class="catalog-area-hero"><span class="catalog-icon"><i class="fa-solid fa-store"></i></span><div><span class="eyebrow">Loja de Cursos</span><h3>Acervo comercial desta Formação</h3><p>Sincronize o catálogo oficial, confira novidades e complete textos e capas antes de disponibilizar os Módulos nas lojas das franquias.</p></div></div>
 <div class="catalog-summary wide-summary"><article class="catalog-stat"><small>Módulos sincronizados</small><strong><?= (int)($catalog['course_count']??count($catalogCourses)) ?></strong></article><article class="catalog-stat"><small>Componentes internos</small><strong><?= (int)($catalog['content_count']??0) ?></strong></article></div>
 <div class="catalog-commerce-actions"><form method="post" action="<?= $escape($basePath) ?>/admin/platform/integrations/course-providers/catalog/<?= $escape($provider) ?>/sync"><?= $csrfField ?><button class="btn btn-primary" type="submit" <?= $configured&&$adapterReady?'':'disabled' ?>><i class="fa-solid fa-cloud-arrow-down"></i> Sincronizar Catálogo</button></form><form method="post" action="<?= $escape($basePath) ?>/admin/platform/integrations/course-providers/catalog/<?= $escape($provider) ?>/complete-commercial-ai"><?= $csrfField ?><button class="btn btn-secondary" type="submit"><i class="fa-solid fa-wand-magic-sparkles"></i> Completar pendências com IA</button></form></div>
 <div class="catalog-note"><i class="fa-solid fa-shield-halved"></i><div>Cada execução da IA analisa até 10 pendências. Textos e capas ajustados manualmente nunca são sobrescritos.</div></div>
</section>
<?php endif;?>

<section class="catalog-subpanel catalog-overview-panel" data-catalog-subpanel="<?= $escape($provider) ?>:modules" hidden>
 <div class="catalog-area-hero"><span class="catalog-icon"><i class="fa-solid fa-cubes-stacked"></i></span><div><span class="eyebrow">Módulos</span><h3>Estrutura acadêmica dos Módulos</h3><p>Cadastros comerciais, aulas, livros, avaliações e demais recursos ficam organizados no Módulo correspondente, em uma única área.</p></div></div>
 <?php if($provider==='iesde'):?><div class="catalog-note"><i class="fa-solid fa-circle-info"></i><div><strong>Formação MASTER:</strong> abra um Módulo abaixo e use “Aulas e recursos” para revisar seus componentes oficiais.</div></div><?php elseif($isConted):?><div class="catalog-note"><i class="fa-solid fa-circle-info"></i><div><strong>Formação EXPERT:</strong> os componentes importados são relacionados ao módulo de origem e preservam a rastreabilidade do fornecedor.</div></div><?php else:?><div class="catalog-note"><i class="fa-solid fa-circle-info"></i><div>Os componentes internos aparecerão aqui quando o conector deste fornecedor disponibilizar a estrutura acadêmica.</div></div><?php endif;?>
</section>

<section class="catalog-subpanel catalog-overview-panel" data-catalog-subpanel="<?= $escape($provider) ?>:trails" hidden>
 <div class="catalog-area-hero"><span class="catalog-icon"><i class="fa-solid fa-route"></i></span><div><span class="eyebrow">Trilhas</span><h3>Pacotes comerciais desta Formação</h3><p>Combine dois ou mais Módulos em uma única oferta, preservando a origem acadêmica de cada item.</p></div></div>
 <div class="catalog-trail-list-head"><div><strong><?= count((array)($catalogTrails??[])) ?> Trilha(s) cadastrada(s)</strong><small>Abra uma Trilha para revisar composição, textos, capa, preço e publicação.</small></div><a class="btn btn-primary" href="<?= $escape($basePath) ?>/admin/platform/catalog-trails?tab=trails&amp;trail_new=1<?= $provider==='iesde'?'&amp;catalog=iesde':'' ?>"><i class="fa-solid fa-plus"></i> Nova Trilha</a></div>
 <?php if((array)($catalogTrails??[])===[]):?><div class="catalog-empty compact"><i class="fa-solid fa-route fa-2x"></i><h3>Nenhuma Trilha desta Formação</h3><p>Crie o primeiro pacote selecionando dois ou mais Módulos relacionados.</p></div><?php else:?><div class="catalog-trail-grid"><?php foreach((array)$catalogTrails as$trail):?><article><div><span class="catalog-badge <?= (int)($trail['is_active']??0)===1?'ok':'private' ?>"><?= (int)($trail['is_active']??0)===1?'Ativa':'Rascunho' ?></span><h4><?= $escape((string)$trail['name']) ?></h4><p><?= (int)($trail['item_count']??0) ?> Módulo(s)<?= ($trail['workload_hours']??null)!==null?' · '.number_format((float)$trail['workload_hours'],0,',','.').'h':'' ?><?= ($trail['default_price']??null)!==null?' · R$ '.number_format((float)$trail['default_price'],2,',','.') :'' ?></p></div><a class="btn btn-secondary" href="<?= $escape($basePath) ?>/admin/platform/catalog-trails?tab=trails&amp;trail_edit=<?= (int)$trail['id'] ?><?= $provider==='iesde'?'&amp;catalog=iesde':'' ?>"><i class="fa-solid fa-pen-to-square"></i> Editar</a></article><?php endforeach;?></div><?php endif;?>
</section>
