<div class="catalog-subpanel" data-catalog-subpanel="<?= $escape($provider) ?>:contents" hidden>
 <div class="catalog-note" style="margin:0 0 1rem"><i class="fa-solid fa-diagram-project"></i><div><strong>Conteúdos liberados por padrão.</strong><br>A curadoria organiza nome, capa e descrição. O bloqueio global é uma exceção e interrompe novas vendas em todas as franquias sem excluir históricos.</div></div>
 <div class="content-toolbar">
  <form method="get" action="<?= $escape($basePath) ?>/admin/platform/integrations/course-providers">
   <input type="hidden" name="catalog" value="<?= $escape($provider) ?>">
   <input type="hidden" name="section" value="contents">
   <label>Localizar conteúdo, disciplina, curso ou código<input name="content_q" value="<?= $escape($contentQuery) ?>" placeholder="Ex.: Atendimento ao cliente"></label>
   <button class="btn btn-primary" type="submit"><i class="fa-solid fa-magnifying-glass"></i> Pesquisar</button>
   <?php if($contentQuery!==''):?><a class="btn btn-secondary" href="<?= $escape($basePath) ?>/admin/platform/integrations/course-providers?catalog=<?= $escape($provider) ?>&amp;section=contents">Limpar</a><?php endif;?>
  </form>
  <p><strong><?= (int)($contentPage['total']??0) ?></strong> conteúdo(s)</p>
 </div>
 <?php if($contentRows===[]):?>
  <div class="catalog-empty"><i class="fa-solid fa-puzzle-piece fa-2x"></i><h3>Nenhum conteúdo individual sincronizado</h3><p>Use “Sincronizar cursos” na aba Conexão e API. A hierarquia será importada automaticamente.</p></div>
 <?php else:?>
  <div class="table-responsive content-table-wrap"><table class="content-table"><thead><tr><th>Conteúdo individual</th><th>Origem</th><th>Curadoria</th><th>Disponibilidade global</th><th>Ações</th></tr></thead><tbody>
  <?php foreach($contentRows as$content):
   $contentReview=(string)($content['review_status']??'imported');
   $contentRelease=(string)($content['release_status']??'private');
   $globallyEnabled=(int)($content['is_globally_enabled']??1)===1&&(int)($content['catalog_globally_enabled']??1)===1;
   $courseNames=array_values(array_filter(explode('||',(string)($content['course_names']??''))));
   $editorId='content-curation-'.(int)$content['id'];
  ?>
   <tr class="content-summary-row <?= $globallyEnabled?'':'is-blocked' ?>">
    <td><div class="catalog-course"><?php $contentCover=!empty($content['media_asset_id'])?$basePath.'/catalog-media/'.(int)$content['media_asset_id']:(string)($content['effective_cover_url']??'');if($contentCover!==''):?><img class="catalog-cover" src="<?= $escape($contentCover) ?>" alt="" loading="lazy"><?php else:?><span class="catalog-cover catalog-icon"><i class="fa-solid fa-play"></i></span><?php endif;?><div><strong><?= $escape((string)($content['effective_name']??$content['name'])) ?></strong><small><?= $escape((string)($content['content_type']??'unit')) ?> · código <?= $escape((string)$content['external_key']) ?></small><div class="catalog-course-state"><span class="catalog-badge <?= (int)$content['is_available']===1?'ok':'' ?>"><?= (int)$content['is_available']===1?'No fornecedor':'Retirado pelo fornecedor' ?></span><?php if((string)($content['sync_state']??'')==='changed'):?><span class="catalog-badge changed">Alterado</span><?php endif;?></div></div></div></td>
    <td><div class="content-origin"><strong><?= $escape((string)($content['discipline_name']?:'Disciplina não informada')) ?></strong><small><?= $content['semester_number']!==null?'Semestre '.(int)$content['semester_number'].' · ':'' ?><?= (int)$content['course_count'] ?> curso(s) relacionado(s)</small><?php if($courseNames!==[]):?><small title="<?= $escape(implode(' · ',$courseNames)) ?>"><?= $escape(implode(' · ',array_slice($courseNames,0,2))) ?><?= count($courseNames)>2?' e mais '.(count($courseNames)-2):'' ?></small><?php endif;?></div></td>
    <td><div class="catalog-course-state"><span class="catalog-badge <?= $contentReview==='approved'?'ok':'' ?>"><?= $escape($reviewLabels[$contentReview]??'Importado') ?></span><span class="catalog-badge <?= $contentRelease==='private'?'private':'ok' ?>"><?= $escape($releaseLabels[$contentRelease]??'Somente ADM Central') ?></span></div></td>
    <td><span class="availability-pill <?= $globallyEnabled?'is-enabled':'is-disabled' ?>"><i class="fa-solid <?= $globallyEnabled?'fa-circle-check':'fa-ban' ?>"></i><?= $globallyEnabled?'Liberado para todas':'Bloqueado globalmente' ?></span><small><?= (int)($content['offer_count']??0) ?> oferta(s) configurada(s)</small></td>
    <td><div class="content-row-actions"><button class="btn btn-secondary" type="button" data-content-curation-toggle="<?= $escape($editorId) ?>" aria-expanded="false"><i class="fa-solid fa-pen-to-square"></i> Curadoria</button><form method="post" action="<?= $escape($basePath) ?>/admin/platform/integrations/course-providers/contents/<?= (int)$content['id'] ?>/availability" onsubmit="return confirm('<?= $globallyEnabled?'Bloquear este conteúdo para todas as franquias?':'Liberar este conteúdo para todas as franquias por padrão?' ?>')"><?= $csrfField ?><input type="hidden" name="provider" value="<?= $escape($provider) ?>"><input type="hidden" name="enabled" value="<?= $globallyEnabled?'0':'1' ?>"><button class="btn <?= $globallyEnabled?'btn-danger':'btn-primary' ?>" type="submit" title="<?= $globallyEnabled?'Bloquear em todas as franquias':'Liberar em todas as franquias' ?>"><i class="fa-solid <?= $globallyEnabled?'fa-ban':'fa-unlock' ?>"></i> <?= $globallyEnabled?'Bloquear':'Liberar' ?></button></form></div></td>
   </tr>
   <tr class="content-curation-row" id="<?= $escape($editorId) ?>" hidden><td colspan="5">
    <form class="content-curation-form" method="post" enctype="multipart/form-data" action="<?= $escape($basePath) ?>/admin/platform/integrations/course-providers/contents/<?= (int)$content['id'] ?>/review"><?= $csrfField ?><input type="hidden" name="provider" value="<?= $escape($provider) ?>">
     <header><div><span class="eyebrow">Curadoria comercial</span><h3><?= $escape((string)($content['effective_name']??$content['name'])) ?></h3><p>Organize a vitrine sem alterar os dados recebidos do fornecedor.</p></div><button class="action-icon" type="button" data-content-curation-close="<?= $escape($editorId) ?>" title="Fechar curadoria"><i class="fa-solid fa-xmark"></i></button></header>
     <div class="content-curation-grid">
      <label>Situação<select name="review_status"><?php foreach($reviewLabels as$key=>$label):?><option value="<?= $key ?>" <?= $contentReview===$key?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label>
      <label>Liberação comercial<select name="release_status"><?php foreach($releaseLabels as$key=>$label):?><option value="<?= $key ?>" <?= $contentRelease===$key?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label>
      <label class="span-2">Nome comercial<input name="commercial_name" maxlength="500" value="<?= $escape((string)($content['commercial_name']?:$content['name'])) ?>"></label>
      <label>Categoria<input name="commercial_category" maxlength="255" value="<?= $escape((string)($content['commercial_category']??'')) ?>" placeholder="<?= $escape((string)($content['effective_category']??$content['discipline_name']??'')) ?>"></label>
      <label>Carga horária<input name="commercial_workload" maxlength="100" value="<?= $escape((string)($content['commercial_workload']??'')) ?>" placeholder="<?= $escape((string)($content['effective_workload']??'')) ?>"></label>
      <label class="span-2">Imagem comercial por URL<input type="url" name="commercial_cover_url" value="<?= $escape((string)($content['commercial_cover_url']??'')) ?>"></label>
      <label class="span-2 catalog-image-upload">Capa otimizada no Spaces<input type="file" name="commercial_cover_file" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG ou WebP. A imagem será reduzida e armazenada fora da VPS.</small><?php if(!empty($content['media_asset_id'])):?><span class="catalog-image-current"><img src="<?= $escape($basePath) ?>/catalog-media/<?= (int)$content['media_asset_id'] ?>" alt="Capa atual"><span><?= ($content['media_inheritance']??'')==='own'?'Capa própria':'Capa herdada do curso-pai' ?></span></span><?php if(($content['media_inheritance']??'')==='own'):?><span class="checkbox-row"><input type="checkbox" name="remove_cover" value="1"> Remover capa própria</span><?php endif;?><?php endif;?></label>
      <label class="span-2">Descrição comercial<textarea name="commercial_description"><?= $escape((string)($content['commercial_description']??'')) ?></textarea></label>
      <label class="span-2">Observações internas<textarea name="review_notes"><?= $escape((string)($content['review_notes']??'')) ?></textarea></label>
     </div>
     <footer><span><i class="fa-solid fa-circle-info"></i> A disponibilidade para franquias é controlada por exceções no cadastro de cada franquia.</span><button class="btn btn-primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Salvar curadoria</button></footer>
    </form>
    <form class="catalog-ai-form content-ai-form <?= $imageAiReady?'':'is-disabled' ?>" method="post" action="<?= $escape($basePath) ?>/admin/platform/integrations/course-providers/contents/<?= (int)$content['id'] ?>/generate-cover"><?= $csrfField ?><input type="hidden" name="provider" value="<?= $escape($provider) ?>"><label><strong><i class="fa-solid fa-wand-magic-sparkles"></i> Capa inteligente para este conteúdo</strong><input name="prompt" maxlength="500" placeholder="Orientação opcional: aula prática, tecnologia e ambiente moderno"></label><button class="btn btn-secondary" type="submit" <?= $imageAiReady?'':'disabled' ?>><i class="fa-solid fa-wand-magic-sparkles"></i> Gerar capa com IA</button><small><?= $imageAiReady?'A tarefa entra na fila; a imagem final será otimizada e salva no Spaces.':'Ative a integração IA para capas no ADM Central.' ?></small></form>
   </td></tr>
  <?php endforeach;?>
  </tbody></table></div>
  <?php if((int)($contentPage['pages']??1)>1):$currentPage=(int)$contentPage['page'];$lastPage=(int)$contentPage['pages'];$visiblePages=array_values(array_unique(array_filter([1,$currentPage-2,$currentPage-1,$currentPage,$currentPage+1,$currentPage+2,$lastPage],static fn(int$page):bool=>$page>=1&&$page<=$lastPage)));sort($visiblePages);?><nav class="content-pagination" aria-label="Paginação de conteúdos"><?php $previousPage=0;foreach($visiblePages as$pageNumber):if($previousPage>0&&$pageNumber>$previousPage+1):?><span aria-hidden="true">…</span><?php endif;$pageUrl=$basePath.'/admin/platform/integrations/course-providers?catalog='.$provider.'&section=contents&content_page='.$pageNumber.($contentQuery!==''?'&content_q='.rawurlencode($contentQuery):'');?><a class="<?= $pageNumber===$currentPage?'is-current':'' ?>" href="<?= $escape($pageUrl) ?>"><?= $pageNumber ?></a><?php $previousPage=$pageNumber;endforeach;?></nav><?php endif;?>
 <?php endif;?>
</div>
