<tr class="course-curation-row content-curation-row" id="<?= $escape($editorId) ?>" hidden><td colspan="5">
 <div class="course-curation-shell">
  <form class="course-curation-form content-curation-form" method="post" enctype="multipart/form-data" action="<?= $escape($basePath) ?>/admin/platform/integrations/course-providers/courses/<?= (int)$course['id'] ?>/review"><?= $csrfField ?><input type="hidden" name="provider" value="<?= $escape($provider) ?>">
   <header><div><span class="eyebrow">Curadoria comercial</span><h3><?= $escape((string)($course['effective_name']??$course['name'])) ?></h3><p>Edite a apresentação comercial sem alterar os dados recebidos do fornecedor.</p></div><button class="action-icon" type="button" data-course-curation-close="<?= $escape($editorId) ?>" title="Fechar curadoria"><i class="fa-solid fa-xmark"></i></button></header>
   <div class="catalog-source-data"><span>Categoria original<strong><?= $escape((string)($course['category']?:'—')) ?></strong></span><span>Carga original<strong><?= $escape((string)($course['workload']?:'—')) ?></strong></span><span>Certificado original<strong><?= $escape((string)($course['certificate']?:'—')) ?></strong></span><span>ID externo<strong><?= $escape((string)($course['remote_id']?:$course['external_key'])) ?></strong></span></div>
   <div class="content-curation-grid course-curation-grid">
    <label>Situação<select name="review_status"><?php foreach($reviewLabels as$key=>$label):?><option value="<?= $key ?>" <?= $review===$key?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label>
    <label>Liberação comercial<select name="release_status"><?php foreach($releaseLabels as$key=>$label):?><option value="<?= $key ?>" <?= $release===$key?'selected':'' ?>><?= $label ?></option><?php endforeach;?></select></label>
    <label class="span-2">Nome comercial<input name="commercial_name" maxlength="500" value="<?= $escape((string)($course['commercial_name']?:$course['name'])) ?>"></label>
    <label>Categoria comercial<input name="commercial_category" maxlength="255" value="<?= $escape((string)($course['commercial_category']??'')) ?>" placeholder="<?= $escape((string)($course['category']??'')) ?>"></label>
    <label>Carga horária comercial<input name="commercial_workload" maxlength="100" value="<?= $escape((string)($course['commercial_workload']??'')) ?>" placeholder="<?= $escape((string)($course['workload']??'')) ?>"></label>
    <label class="span-2">Certificado<input name="commercial_certificate" maxlength="190" value="<?= $escape((string)($course['commercial_certificate']??'')) ?>" placeholder="<?= $escape((string)($course['certificate']??'')) ?>"></label>
    <label class="span-2">Imagem comercial por URL<input type="url" name="commercial_cover_url" maxlength="1000" value="<?= $escape((string)($course['commercial_cover_url']??'')) ?>" placeholder="<?= $escape((string)($course['cover_url']??'')) ?>"></label>
    <label class="span-2 catalog-image-upload">Capa otimizada no Spaces<input type="file" name="commercial_cover_file" accept="image/jpeg,image/png,image/webp"><small>JPG, PNG ou WebP, até 8 MB. O arquivo será reduzido e convertido para WebP.</small><?php if(!empty($course['media_asset_id'])):?><span class="catalog-image-current"><img src="<?= $escape($basePath) ?>/catalog-media/<?= (int)$course['media_asset_id'] ?>" alt="Capa atual"><span>Capa própria armazenada no Spaces</span></span><span class="checkbox-row"><input type="checkbox" name="remove_cover" value="1"> Remover capa própria</span><?php endif;?></label>
    <label class="span-2">Descrição comercial<textarea name="commercial_description"><?= $escape((string)($course['commercial_description']?:$course['description'])) ?></textarea></label>
    <label class="span-2">Observações internas<textarea name="review_notes"><?= $escape((string)($course['review_notes']??'')) ?></textarea></label>
   </div>
   <footer><span><i class="fa-solid fa-shield-halved"></i> Aprovar não publica sozinho. Escolha também a liberação comercial desejada.</span><button class="btn btn-primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Salvar curadoria</button></footer>
  </form>
  <aside class="course-curation-aside">
   <div><span class="eyebrow">Capa inteligente</span><h3>Gerar imagem com IA</h3><p>Crie uma capa contextual e leve, pronta para a vitrine.</p></div>
   <?php if($cover!==''):?><img class="course-curation-preview" src="<?= $escape($cover) ?>" alt="Capa comercial atual" loading="lazy"><?php else:?><div class="course-curation-placeholder"><i class="fa-solid fa-image"></i><span>Nenhuma capa definida</span></div><?php endif;?>
   <form class="catalog-ai-form <?= $imageAiReady?'':'is-disabled' ?>" method="post" action="<?= $escape($basePath) ?>/admin/platform/integrations/course-providers/courses/<?= (int)$course['id'] ?>/generate-cover"><?= $csrfField ?><input type="hidden" name="provider" value="<?= $escape($provider) ?>"><label>Orientação opcional para a IA<input name="prompt" maxlength="500" placeholder="Ex.: ambiente profissional, pessoas diversas"></label><button class="btn btn-secondary" type="submit" <?= $imageAiReady?'':'disabled' ?>><i class="fa-solid fa-wand-magic-sparkles"></i> Gerar capa com IA</button><small><?= $imageAiReady?'A tarefa entra na fila e a capa final será otimizada no Spaces.':'Ative a integração de imagens no ADM Central.' ?></small></form>
  </aside>
 </div>
</td></tr>
