<?php
$template = is_array($template ?? null) ? $template : [];
$templatePreview = is_array($templatePreview ?? null) ? $templatePreview : [];
$previewBrand = is_array($templatePreview['brand'] ?? null) ? $templatePreview['brand'] : [];
$previewLogo = trim((string) ($previewBrand['logo_path'] ?? ''));
if ($previewLogo !== '' && !preg_match('#^https?://#i', $previewLogo) && !str_starts_with($previewLogo, 'spaces:')) {
    $previewLogo = rtrim((string) $basePath, '/') . '/' . ltrim($previewLogo, '/');
}
$previewPrimary = preg_match('/^#[0-9a-f]{6}$/i', (string) ($previewBrand['primary_color'] ?? '')) === 1 ? (string) $previewBrand['primary_color'] : '#ed1c24';
$previewSecondary = preg_match('/^#[0-9a-f]{6}$/i', (string) ($previewBrand['secondary_color'] ?? '')) === 1 ? (string) $previewBrand['secondary_color'] : '#102a56';
$tokens = ['aluno', 'curso', 'franquia', 'unidade', 'login', 'senha', 'ava_url', 'suporte_email', 'suporte_whatsapp'];
?>
<style>
.mail-page{max-width:92rem;margin:0 auto;color:var(--inter-ink)}.mail-head{display:flex;align-items:flex-end;justify-content:space-between;gap:1rem;margin-bottom:1.1rem}.mail-head h1{margin:.15rem 0 .35rem;font-size:clamp(2rem,4vw,3rem)}.mail-head p{margin:0;max-width:58rem;color:var(--inter-muted)}.mail-alert{margin-bottom:1rem;padding:.9rem 1rem;border-radius:.8rem}.mail-alert.ok{color:#086c42;background:#e3f8ed;border:1px solid #a9e2c5}.mail-alert.error{color:#a31621;background:#fff0f1;border:1px solid #ffc2c7}
.mail-nav{display:flex;gap:.45rem;overflow:auto;margin-bottom:1rem;padding:.45rem;border:1px solid #dce4e9;border-radius:1rem;background:#fff}.mail-nav a{display:inline-flex;align-items:center;gap:.45rem;white-space:nowrap;padding:.7rem .9rem;border-radius:.7rem;color:#41566b;font-weight:800;text-decoration:none}.mail-nav a:hover{color:#ed1c24;background:#fff0f1}.mail-stats{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.85rem;margin-bottom:1rem}.mail-stat{padding:1rem 1.1rem;border:1px solid #dce4e9;border-radius:1rem;background:#fff;box-shadow:0 .4rem 1.2rem rgb(23 33 43 / 5%)}.mail-stat span{display:block;color:var(--inter-muted);font-size:.78rem}.mail-stat strong{display:block;margin-top:.25rem;font-size:1.35rem}.mail-stat i{margin-right:.35rem;color:#f97316}
.mail-grid{display:grid;grid-template-columns:minmax(0,1.45fr) minmax(20rem,.75fr);gap:1rem;align-items:start}.mail-card{padding:1.25rem;border:1px solid #dce4e9;border-radius:1rem;background:#fff;box-shadow:0 .45rem 1.4rem rgb(23 33 43 / 6%)}.mail-card h2,.mail-card h3{margin:0}.mail-card-head{display:flex;align-items:center;gap:.8rem;padding-bottom:1rem;margin-bottom:1rem;border-bottom:1px solid #e5ebef}.mail-card-head>i{display:grid;place-items:center;flex:0 0 2.8rem;width:2.8rem;height:2.8rem;border-radius:.8rem;color:#c2410c;background:#fff2e8}.mail-card-head p{margin:.2rem 0 0;color:var(--inter-muted);font-size:.86rem}.mail-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.9rem}.mail-field label{display:block;margin-bottom:.35rem;font-weight:800;font-size:.86rem}.mail-field input,.mail-field select,.mail-field textarea{width:100%;min-height:2.85rem;padding:.65rem .75rem;border:1px solid #bdcbd4;border-radius:.65rem;background:#fff;color:var(--inter-ink)}.mail-field textarea{min-height:6.5rem;resize:vertical}.mail-field small{display:block;margin-top:.3rem;color:var(--inter-muted);line-height:1.35}.mail-field.full{grid-column:1/-1}.mail-check{display:flex;align-items:flex-start;gap:.55rem;padding:.85rem;border-radius:.75rem;background:#f5f8fa}.mail-check input{margin-top:.2rem}.mail-actions{display:flex;align-items:center;justify-content:flex-end;gap:.65rem;margin-top:1rem;flex-wrap:wrap}.mail-btn{display:inline-flex;align-items:center;justify-content:center;gap:.45rem;min-height:2.75rem;padding:.65rem 1rem;border:1px solid #bdcbd4;border-radius:.7rem;background:#fff;color:var(--inter-ink);font-weight:800;text-decoration:none;cursor:pointer}.mail-btn.primary{color:#fff;background:#f11d2d;border-color:#f11d2d}.mail-btn:disabled{opacity:.55;cursor:not-allowed}.mail-test{display:grid;gap:.75rem}.mail-rule{margin-top:1rem;padding:1rem;border:1px solid #fed7aa;border-radius:.85rem;background:#fff7ed}.mail-rule strong{display:block;margin-bottom:.4rem;color:#9a3412}.mail-rule p{margin:0;color:#7c4a25;font-size:.87rem;line-height:1.5}
.mail-section{margin-top:1rem;scroll-margin-top:1rem}.mail-section-title{display:flex;align-items:end;justify-content:space-between;gap:1rem;margin-bottom:.8rem}.mail-section-title h2{margin:0}.mail-section-title p{margin:.2rem 0 0;color:var(--inter-muted)}.template-shell{display:grid;grid-template-columns:minmax(0,1.05fr) minmax(25rem,.95fr);gap:1rem}.token-list{display:flex;gap:.4rem;flex-wrap:wrap;margin-top:.5rem}.token-chip{padding:.38rem .58rem;border:1px solid #d9e1e7;border-radius:999px;background:#f7f9fa;color:#53677a;font:700 .75rem/1 inherit;cursor:pointer}.template-tools{display:grid;grid-template-columns:1fr 1fr;gap:.8rem;margin-top:1rem;padding-top:1rem;border-top:1px solid #e5ebef}.preview-toolbar{display:flex;align-items:end;gap:.6rem;margin-bottom:.8rem}.preview-toolbar .mail-field{flex:1}.email-preview-frame{padding:1.2rem;border-radius:1rem;background:#edf2f5;min-height:36rem}.email-preview{max-width:39rem;margin:auto;overflow:hidden;border-radius:1.1rem;background:#fff;box-shadow:0 .6rem 2rem rgb(15 23 42 / 10%)}.email-preview-bar{height:.42rem;background:var(--preview-primary)}.email-preview-body{padding:1.8rem 2rem 1rem}.email-preview-logo{display:block;max-width:10.5rem;max-height:4rem;margin-bottom:1.4rem}.email-preview-eyebrow{color:var(--preview-primary);font-size:.72rem;font-weight:900;letter-spacing:.12em}.email-preview h3{margin:.5rem 0 .7rem;color:var(--preview-secondary);font-size:1.75rem}.email-preview-intro{margin:0;color:#526273;line-height:1.6;white-space:pre-line}.email-preview-data{margin:1rem 2rem;border:1px solid #e2e8f0;border-radius:.75rem;overflow:hidden}.preview-row{display:grid;grid-template-columns:34% 1fr;padding:.65rem .75rem;border-bottom:1px solid #edf0f3;font-size:.85rem}.preview-row:last-child{border-bottom:0}.preview-row span{color:#64748b}.preview-row strong{color:#172033}.email-preview-cta{text-align:center;padding:.25rem 2rem 1.7rem}.email-preview-cta span{display:inline-block;padding:.8rem 1.2rem;border-radius:.65rem;background:var(--preview-primary);color:#fff;font-weight:900}.email-preview-footer{padding:1.1rem 2rem;background:#f8fafc;border-top:1px solid #edf0f3;color:#64748b;font-size:.78rem;line-height:1.5}.email-preview-footer p{margin:0 0 .35rem;white-space:pre-line}
.sender-list{display:grid;gap:.75rem}.sender-card{border:1px solid #dce4e9;border-radius:1rem;background:#fff;overflow:hidden}.sender-summary{display:grid;grid-template-columns:minmax(12rem,1fr) minmax(12rem,1fr) auto;gap:1rem;align-items:center;padding:1rem 1.1rem}.sender-summary strong,.sender-summary small{display:block}.sender-summary small{margin-top:.2rem;color:var(--inter-muted)}.sender-status{display:inline-flex;align-items:center;gap:.35rem;width:max-content;padding:.32rem .6rem;border-radius:999px;font-size:.76rem;font-weight:800}.sender-status.verified{color:#087443;background:#dff7ea}.sender-status.pending{color:#8b5e00;background:#fff0c2}.sender-status.rejected{color:#a31621;background:#ffe1e4}.sender-form{display:grid;grid-template-columns:1fr 1fr 1fr .75fr auto;gap:.75rem;align-items:end;padding:1rem 1.1rem;background:#f8fafb;border-top:1px solid #e5ebef}.sender-form .mail-field{min-width:0}.sender-save{display:grid;gap:.4rem}.sender-empty{padding:1.2rem;color:var(--inter-muted)}
.mail-log{overflow:auto;border:1px solid #dce4e9;border-radius:1rem;background:#fff}.mail-log table{width:100%;border-collapse:collapse;min-width:68rem}.mail-log th,.mail-log td{padding:.8rem .9rem;text-align:left;border-bottom:1px solid #e5ebef;vertical-align:top}.mail-log th{font-size:.75rem;text-transform:uppercase;color:var(--inter-muted);background:#f8fafb}.delivery-status{display:inline-flex;align-items:center;gap:.35rem;padding:.3rem .55rem;border-radius:999px;font-size:.76rem;font-weight:900}.delivery-status.sent{color:#087443;background:#dff7ea}.delivery-status.failed{color:#b91c1c;background:#ffe1e4}.mail-empty{text-align:center;color:var(--inter-muted);padding:1.5rem!important}.retry-note{display:block;margin-top:.25rem;color:var(--inter-muted);font-size:.73rem}
@media(max-width:1100px){.template-shell{grid-template-columns:1fr}.email-preview-frame{min-height:auto}.mail-grid{grid-template-columns:1fr}}@media(max-width:980px){.mail-stats{grid-template-columns:repeat(2,1fr)}.sender-form{grid-template-columns:repeat(2,1fr)}.sender-save{grid-column:1/-1}.sender-save .mail-btn{width:100%}}@media(max-width:640px){.mail-head{align-items:flex-start;flex-direction:column}.mail-stats,.mail-fields,.sender-form,.template-tools{grid-template-columns:1fr}.mail-field.full,.sender-save{grid-column:auto}.sender-summary{grid-template-columns:1fr}.mail-actions{align-items:stretch;flex-direction:column}.mail-actions .mail-btn{width:100%}.email-preview-body{padding:1.4rem}.email-preview-data{margin:1rem}.email-preview-cta{padding:0 1rem 1.4rem}.email-preview-footer{padding:1rem 1.4rem}}
</style>

<div class="mail-page">
 <header class="mail-head">
  <div><p class="eyebrow">ADM Central · Integrações</p><h1>E-mail Central</h1><p>Envios transacionais com a identidade de cada franquia, modelos reutilizáveis e rastreabilidade completa.</p></div>
  <a class="mail-btn" href="<?= $escape($basePath) ?>/admin/platform/integrations"><i class="fa-solid fa-arrow-left"></i> Integrações</a>
 </header>

 <?php if (!empty($message)): ?><div class="mail-alert ok"><i class="fa-solid fa-circle-check"></i> <?= $escape((string) $message) ?></div><?php endif; ?>
 <?php if (!empty($error)): ?><div class="mail-alert error"><i class="fa-solid fa-triangle-exclamation"></i> <?= $escape((string) $error) ?></div><?php endif; ?>

 <nav class="mail-nav" aria-label="Áreas do E-mail Central">
  <a href="#conexao"><i class="fa-solid fa-server"></i> Conexão</a><a href="#modelo"><i class="fa-solid fa-wand-magic-sparkles"></i> Modelo de acesso</a><a href="#franquias"><i class="fa-solid fa-building"></i> Franquias</a><a href="#historico"><i class="fa-solid fa-clock-rotate-left"></i> Histórico</a>
 </nav>

 <section class="mail-stats" aria-label="Resumo dos envios">
  <div class="mail-stat"><span><i class="fa-solid fa-power-off"></i>Situação</span><strong><?= !empty($settings['configured']) && !empty($settings['is_active']) ? 'Ativa' : 'Pendente' ?></strong></div>
  <div class="mail-stat"><span><i class="fa-solid fa-paper-plane"></i>Enviados em 30 dias</span><strong><?= (int) ($summary['sent'] ?? 0) ?></strong></div>
  <div class="mail-stat"><span><i class="fa-solid fa-circle-exclamation"></i>Falhas em 30 dias</span><strong><?= (int) ($summary['failed'] ?? 0) ?></strong></div>
  <div class="mail-stat"><span><i class="fa-solid fa-vial-circle-check"></i>Último teste</span><strong style="font-size:1rem"><?= !empty($settings['last_tested_at']) ? $escape(date('d/m/Y H:i', strtotime((string) $settings['last_tested_at']))) : 'Não realizado' ?></strong></div>
 </section>

 <div class="mail-grid" id="conexao">
  <section class="mail-card">
   <div class="mail-card-head"><i class="fa-solid fa-envelope-open-text"></i><div><h2>Servidor de envio</h2><p>Credenciais criptografadas e compartilhadas por toda a rede.</p></div></div>
   <form method="post" action="<?= $escape($basePath) ?>/admin/platform/integrations/email">
    <?= $csrfField ?>
    <div class="mail-fields">
     <div class="mail-field"><label for="smtp_host">Servidor SMTP *</label><input id="smtp_host" name="smtp_host" required value="<?= $escape((string) ($settings['smtp_host'] ?? '')) ?>" placeholder="smtp.seuprovedor.com"></div>
     <div class="mail-field"><label for="smtp_port">Porta *</label><input id="smtp_port" name="smtp_port" type="number" min="1" max="65535" required value="<?= (int) ($settings['smtp_port'] ?? 587) ?>"></div>
     <div class="mail-field"><label for="encryption">Segurança *</label><select id="encryption" name="encryption"><option value="tls" <?= ($settings['encryption'] ?? 'tls') === 'tls' ? 'selected' : '' ?>>STARTTLS</option><option value="ssl" <?= ($settings['encryption'] ?? '') === 'ssl' ? 'selected' : '' ?>>SSL/TLS</option><option value="none" <?= ($settings['encryption'] ?? '') === 'none' ? 'selected' : '' ?>>Sem criptografia</option></select></div>
     <div class="mail-field"><label for="username">Usuário SMTP *</label><input id="username" name="username" autocomplete="off" placeholder="<?= !empty($settings['username_last4']) ? 'Credencial salva ····' . $escape((string) $settings['username_last4']) : 'Usuário do provedor' ?>"><small>Vazio preserva a credencial atual.</small></div>
     <div class="mail-field"><label for="password">Senha SMTP *</label><input id="password" name="password" type="password" autocomplete="new-password" placeholder="<?= !empty($settings['password_last4']) ? 'Senha salva ····' . $escape((string) $settings['password_last4']) : 'Senha ou chave SMTP' ?>"><small>Vazio preserva a senha atual.</small></div>
     <div class="mail-field"><label for="from_name">Nome central *</label><input id="from_name" name="from_name" required value="<?= $escape((string) ($settings['from_name'] ?? 'Mundo Inter')) ?>"></div>
     <div class="mail-field"><label for="from_email">E-mail autenticado *</label><input id="from_email" name="from_email" type="email" required value="<?= $escape((string) ($settings['from_email'] ?? 'no-reply@mundointer.com.br')) ?>"></div>
     <div class="mail-field"><label for="reply_to_email">Responder para</label><input id="reply_to_email" name="reply_to_email" type="email" value="<?= $escape((string) ($settings['reply_to_email'] ?? '')) ?>" placeholder="suporte@mundointer.com.br"></div>
     <label class="mail-check full"><input type="checkbox" name="is_active" value="1" <?= !empty($settings['is_active']) ? 'checked' : '' ?>><span><strong>Ativar envios reais</strong><br><small>Acessos de alunos e mensagens transacionais usarão este serviço.</small></span></label>
    </div>
    <div class="mail-actions"><button class="mail-btn primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Salvar integração</button></div>
   </form>
  </section>

  <aside class="mail-card">
   <div class="mail-card-head"><i class="fa-solid fa-paper-plane"></i><div><h2>Validar entrega</h2><p>Confirme a conexão antes de ativar os envios reais.</p></div></div>
   <form class="mail-test" method="post" action="<?= $escape($basePath) ?>/admin/platform/integrations/email/test">
    <?= $csrfField ?><label for="test_email"><strong>E-mail para o teste técnico</strong></label><input id="test_email" name="test_email" type="email" required placeholder="seuemail@dominio.com.br"><button class="mail-btn primary" type="submit"><i class="fa-solid fa-paper-plane"></i> Testar SMTP</button>
   </form>
   <div class="mail-rule"><strong><i class="fa-solid fa-shield-halved"></i> Remetente seguro</strong><p>O endereço técnico autenticado permanece no campo “De”. A marca, as cores e o “Responder para” pertencem à franquia. Um domínio próprio só deve assumir o remetente depois de SPF e DKIM validados; mantenha também uma política DMARC ativa.</p></div>
   <?php if (!empty($settings['last_error'])): ?><div class="mail-alert error" style="margin:1rem 0 0"><?= $escape((string) $settings['last_error']) ?></div><?php endif; ?>
  </aside>
 </div>

 <section class="mail-section" id="modelo">
  <div class="mail-section-title"><div><h2>Modelo · Acesso ao AVA</h2><p>Edite o conteúdo, revise a identidade escolhida e envie uma prévia sem alterar a configuração.</p></div></div>
  <div class="template-shell">
   <form class="mail-card" method="post" action="<?= $escape($basePath) ?>/admin/platform/integrations/email/templates/ava-access" id="ava-template-form">
    <?= $csrfField ?>
    <div class="mail-card-head"><i class="fa-solid fa-wand-magic-sparkles"></i><div><h2>Conteúdo do e-mail</h2><p>As variáveis são preenchidas automaticamente em cada envio.</p></div></div>
    <div class="mail-fields">
     <div class="mail-field full"><label for="subject_template">Assunto *</label><input id="subject_template" data-preview="subject" name="subject_template" maxlength="255" required value="<?= $escape((string) ($template['subject_template'] ?? '')) ?>"></div>
     <div class="mail-field"><label for="eyebrow">Identificação</label><input id="eyebrow" data-preview="eyebrow" name="eyebrow" maxlength="120" value="<?= $escape((string) ($template['eyebrow'] ?? '')) ?>"></div>
     <div class="mail-field"><label for="heading">Título *</label><input id="heading" data-preview="heading" name="heading" maxlength="255" required value="<?= $escape((string) ($template['heading'] ?? '')) ?>"></div>
     <div class="mail-field full"><label for="intro">Mensagem *</label><textarea id="intro" data-preview="intro" name="intro" maxlength="2000" required><?= $escape((string) ($template['intro'] ?? '')) ?></textarea></div>
     <div class="mail-field"><label for="button_label">Texto do botão *</label><input id="button_label" data-preview="button" name="button_label" maxlength="80" required value="<?= $escape((string) ($template['button_label'] ?? '')) ?>"></div>
     <div class="mail-field"><label for="footer_text">Rodapé</label><textarea id="footer_text" data-preview="footer" name="footer_text" maxlength="500"><?= $escape((string) ($template['footer_text'] ?? '')) ?></textarea></div>
     <div class="mail-field full"><label>Variáveis disponíveis</label><div class="token-list"><?php foreach ($tokens as $token): ?><button class="token-chip" type="button" data-token="{{<?= $escape($token) ?>}}">{{<?= $escape($token) ?>}}</button><?php endforeach; ?></div><small>Clique em uma variável para inseri-la no campo em edição.</small></div>
     <label class="mail-check full"><input type="checkbox" name="is_active" value="1" <?= !empty($template['is_active']) ? 'checked' : '' ?>><span><strong>Modelo ativo</strong><br><small>Se desativado, o envio de novos acessos ficará bloqueado.</small></span></label>
    </div>
    <div class="template-tools">
     <div class="mail-field"><label for="organization_id">Identidade do teste</label><select id="organization_id" name="organization_id"><option value="0">Mundo Inter</option><?php foreach (($senders ?? []) as $sender): ?><option value="<?= (int) $sender['organization_id'] ?>" <?= (int) $previewOrganization === (int) $sender['organization_id'] ? 'selected' : '' ?>><?= $escape((string) $sender['display_name']) ?></option><?php endforeach; ?></select></div>
     <div class="mail-field"><label for="template_test_email">Enviar prévia para</label><input id="template_test_email" name="test_email" type="email" placeholder="seuemail@dominio.com.br"></div>
    </div>
    <div class="mail-actions"><button class="mail-btn" type="submit" formaction="<?= $escape($basePath) ?>/admin/platform/integrations/email/templates/ava-access/test"><i class="fa-solid fa-paper-plane"></i> Enviar prévia</button><button class="mail-btn primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Salvar modelo</button></div>
   </form>

   <aside class="mail-card">
    <div class="mail-card-head"><i class="fa-solid fa-eye"></i><div><h2>Pré-visualização</h2><p>Os campos ao lado são refletidos aqui antes de salvar.</p></div></div>
    <div class="preview-toolbar"><div class="mail-field"><label>Marca exibida</label><strong><?= $escape((string) ($previewBrand['display_name'] ?? 'Mundo Inter')) ?></strong><small>A seleção de outra franquia recarrega somente a identidade.</small></div><a class="mail-btn" id="apply-preview-brand" href="<?= $escape($basePath) ?>/admin/platform/integrations/email?preview_organization=<?= (int) $previewOrganization ?>#modelo"><i class="fa-solid fa-rotate"></i> Aplicar</a></div>
    <div class="email-preview-frame">
     <article class="email-preview" style="--preview-primary:<?= $escape($previewPrimary) ?>;--preview-secondary:<?= $escape($previewSecondary) ?>">
      <div class="email-preview-bar"></div><div class="email-preview-body"><?php if ($previewLogo !== '' && !str_starts_with($previewLogo, 'spaces:')): ?><img class="email-preview-logo" src="<?= $escape($previewLogo) ?>" alt="Logo da franquia"><?php endif; ?><div class="email-preview-eyebrow" data-preview-target="eyebrow"></div><h3 data-preview-target="heading"></h3><p class="email-preview-intro" data-preview-target="intro"></p></div>
      <div class="email-preview-data"><div class="preview-row"><span>Login</span><strong>mariana.oliveira</strong></div><div class="preview-row"><span>Senha inicial</span><strong>Os 5 primeiros dígitos do CPF</strong></div><div class="preview-row"><span>Curso</span><strong>Gestão Administrativa</strong></div><div class="preview-row"><span>Unidade</span><strong>Unidade Centro</strong></div></div>
      <div class="email-preview-cta"><span data-preview-target="button"></span></div><footer class="email-preview-footer"><p data-preview-target="footer"></p><span>Suporte: <?= $escape((string) (($previewBrand['support_email'] ?? '') ?: 'contato da franquia')) ?><?php if (!empty($previewBrand['support_phone'])): ?> · WhatsApp <?= $escape((string) $previewBrand['support_phone']) ?><?php endif; ?></span></footer>
     </article>
    </div>
   </aside>
  </div>
 </section>

 <section class="mail-section" id="franquias">
  <div class="mail-section-title"><div><h2>Identidade por franquia</h2><p>O remetente próprio só pode ser ativado após a validação do domínio.</p></div></div>
  <div class="sender-list">
   <?php if (($senders ?? []) === []): ?><div class="sender-card sender-empty">Nenhuma franquia cadastrada.</div><?php endif; ?>
   <?php foreach (($senders ?? []) as $sender): $host = trim((string) ($sender['primary_host'] ?? '')); $status = (string) ($sender['domain_status'] ?? 'pending'); $mailDomain = preg_replace('/^www\./', '', $host) ?: $host; $defaultEmail = $mailDomain !== '' ? 'no-reply@' . $mailDomain : ''; ?>
    <article class="sender-card">
     <div class="sender-summary"><div><strong><?= $escape((string) $sender['display_name']) ?></strong><small><?= $host !== '' ? $escape($host) : 'Domínio público ainda não configurado' ?></small></div><div><strong><?= !empty($sender['from_email']) ? $escape((string) $sender['from_email']) : 'Remetente central em uso' ?></strong><small><?= !empty($sender['reply_to_email']) ? 'Respostas: ' . $escape((string) $sender['reply_to_email']) : 'Resposta usa o contato da franquia' ?></small></div><span class="sender-status <?= $escape($status) ?>"><i class="fa-solid <?= $status === 'verified' ? 'fa-circle-check' : ($status === 'rejected' ? 'fa-circle-xmark' : 'fa-clock') ?>"></i><?= $status === 'verified' ? 'Domínio autenticado' : ($status === 'rejected' ? 'Autenticação recusada' : 'Aguardando DNS') ?></span></div>
     <form class="sender-form" method="post" action="<?= $escape($basePath) ?>/admin/platform/integrations/email/organizations/<?= (int) $sender['organization_id'] ?>"><?= $csrfField ?><div class="mail-field"><label>Nome do remetente</label><input name="from_name" required value="<?= $escape((string) ($sender['from_name'] ?: $sender['display_name'])) ?>"></div><div class="mail-field"><label>E-mail no-reply</label><input name="from_email" type="email" required value="<?= $escape((string) ($sender['from_email'] ?: $defaultEmail)) ?>" <?= $host === '' ? 'disabled' : '' ?>></div><div class="mail-field"><label>Responder para</label><input name="reply_to_email" type="email" value="<?= $escape((string) ($sender['reply_to_email'] ?: ($sender['support_email'] ?: $sender['manager_email']))) ?>"></div><div class="mail-field"><label>Domínio</label><select name="domain_status"><option value="pending" <?= $status === 'pending' ? 'selected' : '' ?>>Aguardando DNS</option><option value="verified" <?= $status === 'verified' ? 'selected' : '' ?>>SPF/DKIM validado</option><option value="rejected" <?= $status === 'rejected' ? 'selected' : '' ?>>Com problema</option></select></div><div class="sender-save"><label class="mail-check"><input type="checkbox" name="is_active" value="1" <?= !empty($sender['is_active']) ? 'checked' : '' ?>><span><strong>Usar remetente</strong></span></label><button class="mail-btn" type="submit" <?= $host === '' ? 'disabled' : '' ?>><i class="fa-solid fa-floppy-disk"></i> Salvar</button></div></form>
    </article>
   <?php endforeach; ?>
  </div>
 </section>

 <section class="mail-section" id="historico">
  <div class="mail-section-title"><div><h2>Histórico de entregas</h2><p>Envios, falhas e novas tentativas processados pelo serviço central.</p></div></div>
  <div class="mail-log"><table><thead><tr><th>Data</th><th>Franquia</th><th>Destinatário</th><th>Assunto</th><th>Tipo</th><th>Situação</th><th>Ação</th></tr></thead><tbody>
   <?php if (($deliveries ?? []) === []): ?><tr><td class="mail-empty" colspan="7">Nenhum e-mail processado ainda.</td></tr><?php endif; ?>
   <?php foreach (($deliveries ?? []) as $delivery): ?><tr><td><?= $escape(date('d/m/Y H:i', strtotime((string) $delivery['created_at']))) ?><?php if (!empty($delivery['retry_of_id'])): ?><span class="retry-note">Nova tentativa do envio #<?= (int) $delivery['retry_of_id'] ?></span><?php endif; ?></td><td><?= $escape((string) ($delivery['organization_name'] ?? 'ADM Central')) ?></td><td><?= $escape((string) $delivery['recipient_email']) ?></td><td><?= $escape((string) $delivery['subject']) ?></td><td><?= $escape((string) $delivery['message_type']) ?></td><td><span class="delivery-status <?= $escape((string) $delivery['status']) ?>"><i class="fa-solid <?= $delivery['status'] === 'sent' ? 'fa-circle-check' : 'fa-circle-xmark' ?>"></i><?= $delivery['status'] === 'sent' ? 'Enviado' : 'Falhou' ?></span><?php if (!empty($delivery['error_message'])): ?><br><small><?= $escape((string) $delivery['error_message']) ?></small><?php endif; ?></td><td><?php if ($delivery['status'] === 'failed' && $delivery['message_type'] === 'ava_access' && $delivery['related_type'] === 'student_enrollment' && (int) $delivery['related_id'] > 0): ?><form method="post" action="<?= $escape($basePath) ?>/admin/platform/integrations/email/deliveries/<?= (int) $delivery['id'] ?>/retry"><?= $csrfField ?><button class="mail-btn" type="submit"><i class="fa-solid fa-rotate-right"></i> Reenviar</button></form><?php else: ?>—<?php endif; ?></td></tr><?php endforeach; ?>
  </tbody></table></div>
 </section>
</div>

<script>
(() => {
 const form = document.getElementById('ava-template-form'); if (!form) return;
 const samples = {aluno:'Mariana Oliveira',curso:'Gestão Administrativa',franquia:<?= json_encode((string) ($previewBrand['display_name'] ?? 'Mundo Inter'), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>,unidade:'Unidade Centro',login:'mariana.oliveira',senha:'Os 5 primeiros dígitos do CPF',ava_url:'https://avacursos.com.br/',suporte_email:<?= json_encode((string) ($previewBrand['support_email'] ?? ''), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>,suporte_whatsapp:<?= json_encode((string) ($previewBrand['support_phone'] ?? ''), JSON_UNESCAPED_UNICODE | JSON_UNESCAPED_SLASHES) ?>};
 const renderText = value => String(value || '').replace(/{{\s*([a-z_]+)\s*}}/gi, (_, key) => samples[key.toLowerCase()] || '');
 const update = () => document.querySelectorAll('[data-preview-target]').forEach(target => { const source = form.querySelector('[data-preview="' + target.dataset.previewTarget + '"]'); if (source) target.textContent = renderText(source.value); });
 form.querySelectorAll('[data-preview]').forEach(field => field.addEventListener('input', update)); update();
 let activeField = form.querySelector('[data-preview="intro"]'); form.querySelectorAll('input:not([type]),input[type="text"],textarea').forEach(field => field.addEventListener('focus', () => activeField = field));
 document.querySelectorAll('[data-token]').forEach(button => button.addEventListener('click', () => { if (!activeField) return; const start = activeField.selectionStart ?? activeField.value.length; const end = activeField.selectionEnd ?? start; activeField.value = activeField.value.slice(0, start) + button.dataset.token + activeField.value.slice(end); activeField.focus(); activeField.setSelectionRange(start + button.dataset.token.length, start + button.dataset.token.length); activeField.dispatchEvent(new Event('input')); }));
 const select = document.getElementById('organization_id'), link = document.getElementById('apply-preview-brand'); const syncLink = () => link.href = <?= json_encode(rtrim((string) $basePath, '/') . '/admin/platform/integrations/email?preview_organization=', JSON_UNESCAPED_SLASHES) ?> + encodeURIComponent(select.value) + '#modelo'; select.addEventListener('change', syncLink); syncLink();
})();
</script>
