<div class="page-header storage-header"><div><p class="eyebrow">ADM Central · Integrações</p><h1>DigitalOcean Spaces</h1><p>Armazenamento externo e privado para toda a rede Mundo Inter.</p></div><a class="btn btn-secondary" href="<?= $escape($basePath) ?>/admin/platform/integrations"><i class="fa-solid fa-arrow-left"></i> Voltar</a></div>
<?php if(!empty($message)):?><div class="alert alert-success"><?= $escape($message) ?></div><?php endif;?>
<?php if(!empty($error)):?><div class="alert alert-danger"><?= $escape($error) ?></div><?php endif;?>
<div class="storage-metrics">
  <article><span><i class="fa-solid fa-plug"></i> Conexão</span><strong><?= $settings['is_active']&&$settings['configured']?'Ativa':'Pendente' ?></strong></article>
  <article><span><i class="fa-solid fa-database"></i> Objetos registrados</span><strong><?= number_format((int)$settings['objects'],0,',','.') ?></strong></article>
  <article><span><i class="fa-solid fa-hard-drive"></i> Volume registrado</span><strong><?= $settings['bytes']>=1073741824?number_format($settings['bytes']/1073741824,2,',','.').' GB':number_format($settings['bytes']/1048576,2,',','.').' MB' ?></strong></article>
  <article><span><i class="fa-solid fa-shield-halved"></i> Último teste</span><strong><?= $settings['last_tested_at']?date('d/m/Y H:i',strtotime((string)$settings['last_tested_at'])):'Não realizado' ?></strong></article>
</div>
<div class="storage-grid">
  <section class="card storage-card"><div class="card-header"><div><p class="eyebrow">Conexão segura</p><h2>Spaces Bucket</h2><p>A chave atual nunca é exibida e fica criptografada com a chave-mestra do Painel.</p></div><span class="status-pill <?= $settings['is_active']?'status-success':'status-warning' ?>"><?= $settings['is_active']?'Ativa':'Inativa' ?></span></div>
    <form method="post" action="<?= $escape($basePath) ?>/admin/platform/integrations/digital-ocean" class="storage-form"><?= $csrfField ?>
      <div class="field field-wide"><label for="spaces-endpoint">Endpoint *</label><input id="spaces-endpoint" name="endpoint" type="url" required value="<?= $escape((string)$settings['endpoint']) ?>" placeholder="https://bucket.nyc3.digitaloceanspaces.com"></div>
      <div class="field"><label for="spaces-bucket">Bucket *</label><input id="spaces-bucket" name="bucket" required value="<?= $escape((string)$settings['bucket']) ?>"></div>
      <div class="field"><label>Região detectada</label><input value="<?= $escape((string)$settings['region']) ?>" readonly></div>
      <div class="field"><label for="spaces-access">Access Key ID <?= $settings['access_key_last4']!==''?'· final '.$escape($settings['access_key_last4']):'*' ?></label><input id="spaces-access" name="access_key" type="password" autocomplete="new-password" placeholder="<?= $settings['configured']?'Deixe vazio para manter':'Informe a chave' ?>"></div>
      <div class="field"><label for="spaces-secret">Secret Access Key <?= $settings['secret_key_last4']!==''?'· final '.$escape($settings['secret_key_last4']):'*' ?></label><input id="spaces-secret" name="secret_key" type="password" autocomplete="new-password" placeholder="<?= $settings['configured']?'Deixe vazio para manter':'Informe o segredo' ?>"></div>
      <div class="field"><label for="spaces-central">Pasta do ADM Central *</label><input id="spaces-central" name="central_prefix" required value="<?= $escape((string)$settings['central_prefix']) ?>"></div>
      <div class="field"><label for="spaces-franchises">Pasta das franquias *</label><input id="spaces-franchises" name="franchises_prefix" required value="<?= $escape((string)$settings['franchises_prefix']) ?>"></div>
      <label class="check-row field-wide"><input type="checkbox" name="is_active" value="1" <?= $settings['is_active']?'checked':'' ?>> Ativar armazenamento externo para novos arquivos</label>
      <div class="field-wide storage-actions"><button class="btn btn-primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Salvar conexão</button></div>
    </form>
  </section>
  <aside class="storage-side">
    <section class="card"><h2>Estrutura automática</h2><div class="folder-tree"><strong><i class="fa-solid fa-folder"></i> <?= $escape((string)$settings['central_prefix']) ?></strong><span>Personalização · Contratos · Solicitações · Tickets · Documentos · Backups</span><strong><i class="fa-solid fa-folder-tree"></i> <?= $escape((string)$settings['franchises_prefix']) ?></strong><span>Uma pasta exclusiva por franquia, com Alunos, Tickets, Documentos, Contratos e Backups.</span></div></section>
    <section class="card"><h2>Validar e preparar</h2><p>O teste envia, lê e remove um pequeno arquivo privado. Depois prepara as pastas do ADM Central e de todas as franquias já cadastradas.</p><form method="post" action="<?= $escape($basePath) ?>/admin/platform/integrations/digital-ocean/test"><?= $csrfField ?><button class="btn btn-primary btn-block" type="submit" <?= !$settings['configured']?'disabled':'' ?>><i class="fa-solid fa-cloud-arrow-up"></i> Testar e criar estrutura</button></form><?php if(!empty($settings['last_error'])):?><p class="storage-error"><i class="fa-solid fa-triangle-exclamation"></i> <?= $escape((string)$settings['last_error']) ?></p><?php endif;?></section>
    <section class="alert alert-info"><strong>Privacidade por padrão</strong><br>Os arquivos são enviados com acesso privado. O Painel entrega anexos somente após validar o usuário e suas permissões.</section>
  </aside>
</div>
<style>
.storage-header{align-items:flex-start}.storage-metrics{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:14px;margin:18px 0}.storage-metrics article{background:#fff;border:1px solid #d8e0e8;border-radius:14px;padding:18px;display:grid;gap:8px}.storage-metrics span{color:#64748b}.storage-metrics strong{font-size:1.2rem}.storage-grid{display:grid;grid-template-columns:minmax(0,2fr) minmax(300px,1fr);gap:18px;align-items:start}.storage-card{padding:0}.storage-card .card-header{padding:22px 24px;border-bottom:1px solid #e2e8f0;display:flex;justify-content:space-between;gap:20px}.storage-card .card-header h2,.storage-side h2{margin:.15rem 0;font-size:1.35rem}.storage-form{padding:24px;display:grid;grid-template-columns:1fr 1fr;gap:18px}.storage-form .field{display:grid;gap:7px;min-width:0}.storage-form input{width:100%}.field-wide{grid-column:1/-1}.check-row{display:flex;gap:10px;align-items:center}.check-row input{width:auto}.storage-actions{display:flex;justify-content:flex-end}.storage-side{display:grid;gap:18px}.storage-side .card{padding:22px}.folder-tree{display:grid;gap:9px;margin-top:18px}.folder-tree span{color:#64748b;padding:0 0 12px 23px}.storage-error{color:#b4232c;margin-top:14px}.status-pill{height:max-content}.btn-block{width:100%}@media(max-width:900px){.storage-metrics{grid-template-columns:1fr 1fr}.storage-grid{grid-template-columns:1fr}}@media(max-width:600px){.storage-metrics,.storage-form{grid-template-columns:1fr}.field-wide{grid-column:auto}}
</style>
