<div class="page-header"><div><p class="eyebrow">ADM Central · Integrações</p><h1>IA para capas dos cursos</h1><p>Gere imagens coerentes com cada formação, otimize e armazene a versão definitiva no Spaces.</p></div><a class="btn btn-secondary" href="<?= $escape($basePath) ?>/admin/platform/integrations"><i class="fa-solid fa-arrow-left"></i> Voltar</a></div>
<?php if($message):?><div class="alert alert-success"><?= $escape($message) ?></div><?php endif;?>
<?php if($error):?><div class="alert alert-danger"><?= $escape($error) ?></div><?php endif;?>
<style>
.image-ai-flow{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin:1rem 0}.image-ai-flow article,.image-ai-card{padding:1.2rem;border:1px solid #dbe4ea;border-radius:1rem;background:#fff;box-shadow:0 .5rem 1.2rem rgba(20,40,60,.05)}.image-ai-flow span{display:grid;place-items:center;width:2.4rem;height:2.4rem;border-radius:.75rem;background:#ffecef;color:#ed1c24;font-weight:900}.image-ai-flow h3{margin:.65rem 0 .25rem}.image-ai-flow p{margin:0;color:#64748b}.image-ai-layout{display:grid;grid-template-columns:minmax(0,1.6fr) minmax(17rem,.8fr);gap:1rem}.image-ai-form{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.9rem}.image-ai-form label{display:grid;gap:.35rem}.image-ai-form .wide{grid-column:1/-1}.image-ai-form textarea{min-height:8rem}.image-ai-status{display:grid;gap:.75rem}.image-ai-status div{padding:.85rem;border-radius:.8rem;background:#f4f7f9}.image-ai-status small,.image-ai-status strong{display:block}.image-ai-actions{display:flex;gap:.6rem;flex-wrap:wrap;align-items:center;grid-column:1/-1}@media(max-width:850px){.image-ai-flow,.image-ai-layout,.image-ai-form{grid-template-columns:1fr}.image-ai-form .wide{grid-column:auto}}
</style>
<section class="image-ai-flow"><article><span>1</span><h3>Fonte do fornecedor</h3><p>Quando houver uma imagem confiável, ela continua sendo a primeira opção.</p></article><article><span>2</span><h3>Geração contextual</h3><p>A IA interpreta nome, categoria e descrição comercial do curso.</p></article><article><span>3</span><h3>Spaces e vitrine</h3><p>A capa é reduzida, convertida e passa a ser servida pelo armazenamento externo.</p></article></section>
<div class="image-ai-layout"><section class="image-ai-card"><h2>Configuração central</h2><form class="image-ai-form" method="post" action="<?= $escape($basePath) ?>/admin/platform/integrations/image-generation"><?= $csrfField ?>
 <label class="wide">Nova chave da API<input type="password" name="api_key" autocomplete="new-password" placeholder="sk-..."><small><?= $settings['configured']?'Chave cadastrada terminada em ••••'.$escape($settings['api_key_last4']).'. Deixe vazio para preservar.':'A chave será criptografada e nunca será exibida novamente.' ?></small></label>
 <label>Modelo<select name="model"><option value="gpt-image-2" <?= $settings['model']==='gpt-image-2'?'selected':'' ?>>GPT Image 2 · recomendado</option><option value="gpt-image-1.5" <?= $settings['model']==='gpt-image-1.5'?'selected':'' ?>>GPT Image 1.5</option><option value="gpt-image-1-mini" <?= $settings['model']==='gpt-image-1-mini'?'selected':'' ?>>GPT Image 1 mini · econômico</option></select></label>
 <label>Qualidade<select name="quality"><option value="low" <?= $settings['quality']==='low'?'selected':'' ?>>Baixa · lote econômico</option><option value="medium" <?= $settings['quality']==='medium'?'selected':'' ?>>Média</option><option value="high" <?= $settings['quality']==='high'?'selected':'' ?>>Alta</option></select></label>
 <label class="wide">Direção visual padrão<textarea name="style_prompt"><?= $escape($settings['style_prompt']) ?></textarea><small>O nome, a categoria e a descrição de cada curso são acrescentados automaticamente.</small></label>
 <label class="wide"><span class="checkbox-row"><input type="checkbox" name="is_active" value="1" <?= $settings['is_active']?'checked':'' ?>> Ativar geração de capas após salvar e testar</span></label>
 <label class="wide"><span class="checkbox-row"><input type="checkbox" name="auto_generate_missing" value="1" <?= ($settings['auto_generate_missing']??false)?'checked':'' ?>> Ao aprovar um curso ou conteúdo sem imagem, adicionar automaticamente à fila</span><small>Importações em massa não geram imagens sozinhas. A automação começa somente depois da aprovação do curador, evitando custos inesperados.</small></label>
 <div class="image-ai-actions"><button class="btn btn-primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Salvar configuração</button></div>
 </form><form method="post" action="<?= $escape($basePath) ?>/admin/platform/integrations/image-generation/test" style="margin-top:.75rem"><?= $csrfField ?><button class="btn btn-secondary" type="submit" <?= !$settings['configured']?'disabled':'' ?>><i class="fa-solid fa-plug-circle-check"></i> Testar chave sem gerar imagem</button></form></section>
 <aside class="image-ai-card image-ai-status"><h2>Operação</h2><div><small>Integração</small><strong><?= $settings['configured']?($settings['is_active']?'Ativa':'Configurada e pausada'):'Não configurada' ?></strong></div><div><small>Formato final</small><strong>Horizontal 3:2 · otimizado no Spaces</strong></div><div><small>Fila</small><strong><?= (int)$jobs['pending'] ?> aguardando · <?= (int)$jobs['processing'] ?> processando</strong></div><div><small>Histórico</small><strong><?= (int)$jobs['ready'] ?> concluída(s) · <?= (int)$jobs['failed'] ?> falha(s)</strong></div><p class="muted"><i class="fa-solid fa-shield-halved"></i> A geração é iniciada na curadoria do curso. Nenhum segredo é salvo em texto aberto.</p></aside></div>
