<div class="page-header"><div><p class="eyebrow">ADM Central</p><h1>Integrações</h1><p>Conexões utilizadas pela operação central do Mundo Inter.</p></div></div>
<div class="row">
  <div class="col-sm-6"><a class="quick-link" href="<?= $escape($basePath) ?>/admin/platform/integrations/asaas"><span class="quick-icon"><i class="fa-solid fa-wallet"></i></span><strong>Asaas</strong><small>Cobranças das franquias, contratos, webhooks e split de pagamentos.</small><span class="connection-badge <?= $asaasConfigured&&$asaasActive?'connection-approved':'connection-pending' ?>"><?= $asaasConfigured&&$asaasActive?'Ativa':'Configuração pendente' ?></span></a></div>
  <div class="col-sm-6"><a class="quick-link" href="<?= $escape($basePath) ?>/admin/platform/integrations/digital-ocean"><span class="quick-icon"><i class="fa-solid fa-cloud"></i></span><strong>DigitalOcean Spaces</strong><small>Arquivos privados do ADM Central, franquias, alunos, tickets e personalizações.</small><span class="connection-badge <?= $spacesConfigured&&$spacesActive?'connection-approved':'connection-pending' ?>"><?= $spacesConfigured&&$spacesActive?'Ativa':'Configuração pendente' ?></span></a></div>
</div>
<div class="row">
  <div class="col-sm-6"><a class="quick-link" href="<?= $escape($basePath) ?>/admin/platform/integrations/ava-cursos"><span class="quick-icon"><i class="fa-solid fa-graduation-cap"></i></span><strong>AVA Cursos</strong><small>Moodle compartilhado, catálogo central e matrículas das franquias autorizadas.</small><span class="connection-badge <?= $avaConfigured&&$avaActive?'connection-approved':'connection-pending' ?>"><?= $avaConfigured&&$avaActive?'Ativa':'Configuração pendente' ?></span></a></div>
  <div class="col-sm-6"><a class="quick-link" href="<?= $escape($basePath) ?>/admin/platform/painel-inter"><span class="quick-icon"><i class="fa-solid fa-chalkboard-user"></i></span><strong>Painel Inter</strong><small>Conectores Moodle, versões instaladas, disponibilidade e falhas por franquia.</small><span class="connection-badge connection-pending">Monitoramento</span></a></div>
</div>
