<?php $total=count($connections);$active=count(array_filter($connections,static fn(array$c):bool=>(bool)$c['is_active']));$errors=count(array_filter($connections,static fn(array$c):bool=>!empty($c['last_error'])||!empty($c['plugin_last_error']))); ?>
<style>
.connector-page{max-width:82rem;margin:0 auto}.connector-summary{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin:1.2rem 0}.connector-metric{padding:1.2rem 1.35rem}.connector-metric strong{display:block;font-size:1.8rem}.connector-table td{vertical-align:middle}.connector-guide{display:grid;grid-template-columns:repeat(3,1fr);gap:1rem;margin-top:1rem}.connector-step{padding:1.2rem}.connector-step span{display:grid;place-items:center;width:2.3rem;height:2.3rem;border-radius:50%;background:#fff0f1;color:var(--inter-accent);font-weight:800}@media(max-width:800px){.connector-summary,.connector-guide{grid-template-columns:1fr}}
</style>
<div class="connector-page">
 <header class="page-header"><div><p class="eyebrow">ADM Central · AVA</p><h1>Painel Inter</h1><p>Gerencie o conector instalado nos Moodles e acompanhe a saúde das integrações.</p></div><div class="page-actions"><a class="button button-primary" href="<?= $escape($basePath) ?>/admin/platform/integrations/ava-cursos"><i class="fa-solid fa-graduation-cap"></i> AVA Cursos</a></div></header>
 <?php if(!empty($message)):?><div class="alert alert-success"><?= $escape($message) ?></div><?php endif;?>
 <?php if(!empty($error)):?><div class="alert alert-danger"><?= $escape($error) ?></div><?php endif;?>
 <section class="connector-summary"><div class="card connector-metric"><span class="meta">Conexões cadastradas</span><strong><?= $total ?></strong></div><div class="card connector-metric"><span class="meta">Ativas</span><strong><?= $active ?></strong></div><div class="card connector-metric"><span class="meta">Com atenção</span><strong><?= $errors ?></strong></div></section>
 <section class="card table-card"><div class="section-heading"><div><h2>Instalações Moodle</h2><p class="meta">AVA compartilhado e ambientes próprios das franquias.</p></div></div><div class="table-responsive"><table class="connector-table"><thead><tr><th>Ambiente</th><th>Franquia</th><th>Endereço</th><th>Conexão</th><th>Plugin</th><th>Última validação</th><th>Ação</th></tr></thead><tbody><?php if($connections===[]):?><tr><td colspan="7" class="empty-state">Nenhuma conexão cadastrada.</td></tr><?php else:?><?php foreach($connections as$c):?><tr><td><strong><?= $escape((string)$c['name']) ?></strong><small><?= $c['connection_type']==='shared'?'Compartilhado':'Próprio' ?></small></td><td><?= $escape((string)($c['organization_name']??'Toda a rede')) ?></td><td><?= $c['base_url']?'<a href="'.$escape((string)$c['base_url']).'" target="_blank" rel="noopener">'.$escape((string)$c['base_url']).'</a>':'—' ?></td><td><span class="status-pill <?= $c['is_active']&&$c['configured']?'status-success':'status-warning' ?>"><?= $c['is_active']&&$c['configured']?'Ativa':'Pendente' ?></span><?php if($c['last_error']):?><small><?= $escape((string)$c['last_error']) ?></small><?php endif;?></td><td><strong><?= $escape((string)($c['plugin_release']?:'A instalar')) ?></strong><?php if($c['plugin_last_error']):?><small>Conector não detectado</small><?php elseif($c['last_seen_at']):?><small>Ativo</small><?php endif;?></td><td><?= $escape((string)($c['last_tested_at']?:'Ainda não testada')) ?></td><td><form method="post" action="<?= $escape($basePath) ?>/admin/platform/painel-inter/<?= (int)$c['id'] ?>/test"><?= $csrfField ?><button class="button button-secondary button-icon" type="submit" title="Testar Moodle e conector"><i class="fa-solid fa-plug-circle-check"></i></button></form></td></tr><?php endforeach;?><?php endif;?></tbody></table></div></section>
 <section class="connector-guide"><div class="card connector-step"><span>1</span><h3>Instalar</h3><p>Copiar o plugin para <code>/local/mundointer</code> e concluir a instalação pelo Moodle.</p></div><div class="card connector-step"><span>2</span><h3>Conectar</h3><p>Gerar o token do serviço web e salvá-lo exclusivamente no ADM Central.</p></div><div class="card connector-step"><span>3</span><h3>Monitorar</h3><p>Versão, disponibilidade e falhas ficam centralizadas nesta tela.</p></div></section>
</div>
