<?php
$labels=['draft'=>'Rascunho','sent'=>'Liberado','viewed'=>'Visualizado','signed'=>'Assinado','cancelled'=>'Cancelado'];
$rules=['percentage_commission'=>'Comissão percentual','fixed_monthly'=>'Mensalidade fixa','hybrid'=>'Mensalidade + comissão','per_enrollment'=>'Valor por matrícula'];
$processingLabels=['central_monthly_settlement'=>'Conta central · repasse mensal','central_automatic_split'=>'Conta central · split automático','franchise_asaas'=>'Asaas exclusivo da franquia'];
$commercialRule=trim((string)($contract['commercial_rule']??''));
if($commercialRule==='')$commercialRule=($contract['commercial_model']??'')==='fixed_plus_percentage'?((float)($contract['sales_fee_percentage']??0)>0?'hybrid':'fixed_monthly'):'percentage_commission';
$financialProcessing=trim((string)($contract['financial_processing']??''));
if($financialProcessing==='')$financialProcessing=(float)($contract['sales_fee_percentage']??0)>0?'central_automatic_split':'central_monthly_settlement';
$flowActive=($contract['commercial_flow_status']??'pending')==='active';
$splitRequired=$financialProcessing==='central_automatic_split';
$exclusiveRequired=$financialProcessing==='franchise_asaas';
$walletReady=!empty($contract['asaas_wallet_id'])&&($contract['asaas_wallet_status']??'')==='validated'&&(int)($contract['split_enabled']??0)===1;
$exclusiveReady=($contract['finance_account_mode']??'')==='exclusive'&&(int)($contract['finance_integration_active']??0)===1&&($contract['finance_integration_test_status']??'')==='success';
$processingReady=(!$splitRequired||$walletReady)&&(!$exclusiveRequired||$exclusiveReady);
$organizationId=(int)($contract['organization_id']??0);
$cancelled=$contract['status']==='cancelled';
$signed=!empty($contract['signed_at'])||$contract['status']==='signed';
$monthly=(float)($contract['monthly_fixed_amount']??0);
$centralPercentage=(float)($contract['sales_fee_percentage']??0);
$franchisePercentage=(float)($contract['franchise_fee_percentage']??0);
if($centralPercentage>0&&$franchisePercentage<=0)$franchisePercentage=100-$centralPercentage;
$perEnrollment=(float)($contract['fixed_fee_per_enrollment']??0);
$commercialReady=!$cancelled&&$signed&&$processingReady;
$signatureSteps=[
 ['label'=>'Gerado','date'=>$contract['created_at']??null],
 ['label'=>'Liberado','date'=>$contract['sent_at']??null],
 ['label'=>'Visualizado','date'=>$contract['viewed_at']??null],
 ['label'=>'Assinado','date'=>$contract['signed_at']??null],
];
$processingTitle=$splitRequired?'Wallet e split':($exclusiveRequired?'Asaas exclusivo':'Fechamento mensal');
$processingDetail=$splitRequired?($walletReady?'Wallet validada e split habilitado.':'Wallet ou split pendente.'):($exclusiveRequired?($exclusiveReady?'Integração exclusiva testada e ativa.':'Integração exclusiva pendente.'):'Fechamento no dia '.(int)($contract['closing_day']??30).' e repasse no dia '.(int)($contract['settlement_day']??10).'.');
?>
<style>
.contract-document .contract-body{margin:0;max-height:45rem;overflow:auto;font:400 .98rem/1.7 Georgia,serif}.contract-document .contract-body h2{font-size:1.4rem}.contract-document .contract-body h3{font-size:1.15rem}.contract-document .contract-body blockquote{margin:1rem 0;padding:.7rem 1rem;border-left:.25rem solid var(--inter-accent);background:#fff7f7}.input-copy-row{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:.5rem}.input-copy-row>*{margin:0!important}.contract-timeline{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.75rem}.contract-timeline>div{padding:1rem;border:1px solid #e0e6ea;border-radius:.75rem;background:#fff}.contract-timeline small,.contract-timeline strong{display:block}.contract-summary-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.75rem}.contract-summary-grid>div{padding:1rem;border-radius:.75rem;background:#f6f8fa;min-height:5.5rem}.contract-summary-grid small,.contract-summary-grid strong{display:block}.contract-operation-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:.75rem}.contract-operation-grid>div{border:1px solid #e0e6ea;border-radius:.75rem;padding:1rem}.contract-operation-grid small{display:block;margin-top:.25rem}@media(max-width:767px){.contract-timeline,.contract-summary-grid,.contract-operation-grid{grid-template-columns:1fr}}
</style>
<div class="page-header"><div><p class="eyebrow">Contrato #<?= (int)($contract['contract_number']??1) ?> · <?= ($contract['contract_type']??'new')==='renewal'?'Renovação':'Novo contrato' ?></p><h1><?= $escape((string)$contract['title']) ?></h1><p><?= $escape((string)$contract['franchise_name']) ?> · <span class="badge <?= $cancelled?'badge-danger':($signed?'badge-success':'badge-warning') ?>"><?= $escape($labels[$contract['status']]??(string)$contract['status']) ?></span></p></div><div class="page-actions"><a class="button button-secondary" href="<?= $escape($basePath) ?>/admin/franchise-applications/<?= (int)$contract['franchise_application_id'] ?>/contracts/create?renew_from=<?= (int)$contract['id'] ?>"><i class="fa-solid fa-rotate"></i> Renovar</a><?php if(!$cancelled):?><a class="button button-danger" href="#cancelamento"><i class="fa-solid fa-ban"></i> Cancelar</a><?php endif;?><a class="button button-secondary" href="<?= $escape($basePath) ?><?= $organizationId>0?'/admin/organizations/'.$organizationId:'/admin/franchise-contracts' ?>"><i class="fa-solid fa-arrow-left"></i> Voltar à franquia</a></div></div>
<?php if(!empty($message)):?><div class="alert alert-success"><?= $escape($message) ?></div><?php endif;?><?php if(!empty($error)):?><div class="alert alert-danger"><?= $escape($error) ?></div><?php endif;?>
<?php if($cancelled):?><section class="alert alert-danger mb-4" id="cancelamento"><strong><i class="fa-solid fa-circle-xmark"></i> Contrato cancelado</strong><p class="mb-1"><?= $escape((string)($contract['cancelled_reason']??'Motivo não informado.')) ?></p><small>Cancelado em <?= !empty($contract['cancelled_at'])?$escape(date('d/m/Y H:i',strtotime((string)$contract['cancelled_at']))):'data não registrada' ?> por <?= $escape((string)($contract['cancelled_by_name']?:'Sistema')) ?>. O histórico foi preservado.</small></section><?php endif;?>

<section class="card p-4 mb-4"><div class="contract-summary-grid">
 <div><small>Regra comercial</small><strong><?= $escape($rules[$commercialRule]??'Legado') ?></strong></div>
 <div><small>Processamento financeiro</small><strong><?= $escape($processingLabels[$financialProcessing]??'Não definido') ?></strong></div>
 <div><small>Vigência</small><strong><?= $contract['valid_from']?$escape(date('d/m/Y',strtotime((string)$contract['valid_from']))):'—' ?> a <?= $contract['valid_until']?$escape(date('d/m/Y',strtotime((string)$contract['valid_until']))):'indeterminada' ?></strong></div>
 <div><small>Mensalidade</small><strong><?= $monthly>0?'R$ '.number_format($monthly,2,',','.'):'Sem mensalidade fixa' ?></strong></div>
 <div><small>Divisão por venda</small><strong><?= $centralPercentage>0?'Mundo Inter '.number_format($centralPercentage,2,',','.').'% · Franquia '.number_format($franchisePercentage,2,',','.').'%':'Não se aplica' ?></strong></div>
 <div><small>Valor por matrícula</small><strong><?= $perEnrollment>0?'R$ '.number_format($perEnrollment,2,',','.'):'Não se aplica' ?></strong></div>
</div></section>

<section class="card mb-4"><div class="card-header"><div><p class="eyebrow">Operação comercial</p><h2><?= $cancelled?'Regra bloqueada':($flowActive?'Regra ativa':'Aguardando ativação') ?></h2><p class="meta"><?= $cancelled?'O cancelamento interrompeu o uso desta regra em novas vendas.':($flowActive?'As novas vendas já utilizam as condições deste contrato.':($commercialReady?'Todos os requisitos estão prontos para ativação.':'Ainda existem requisitos pendentes.')) ?></p></div><div class="page-actions">
 <?php if($cancelled):?><span class="badge badge-danger"><i class="fa-solid fa-ban"></i> Bloqueada</span>
 <?php elseif($flowActive):?><span class="badge badge-success"><i class="fa-solid fa-circle-check"></i> Ativa</span>
 <?php elseif(!$signed):?><a class="button button-primary" href="#assinatura"><i class="fa-solid fa-file-signature"></i> Concluir assinatura</a>
 <?php elseif($splitRequired&&!$walletReady&&$organizationId>0):?><a class="button button-primary" href="<?= $escape($basePath) ?>/admin/organizations/<?= $organizationId ?>#operacao-comercial"><i class="fa-solid fa-wallet"></i> Configurar Wallet</a>
 <?php elseif($exclusiveRequired&&!$exclusiveReady&&$organizationId>0):?><a class="button button-primary" href="<?= $escape($basePath) ?>/admin/organizations/<?= $organizationId ?>/edit#integracoes"><i class="fa-solid fa-plug"></i> Configurar Asaas exclusivo</a>
 <?php else:?><form method="post" action="<?= $escape($basePath) ?>/admin/franchise-contracts/<?= (int)$contract['id'] ?>/activate-commercial-flow"><?= $csrfField ?><button class="button button-primary" type="submit" data-confirm-submit="Ativar esta regra para as novas vendas da franquia?"><i class="fa-solid fa-circle-play"></i> Ativar regra comercial</button></form><?php endif;?>
</div></div><div class="p-4 pt-0"><div class="contract-operation-grid"><div><i class="fa-solid <?= $signed?'fa-circle-check text-success':'fa-clock text-warning' ?>"></i><strong class="d-block mt-2">Contrato assinado</strong><small class="meta"><?= $signed?'Concluído':'Pendente' ?></small></div><div><i class="fa-solid <?= $processingReady?'fa-circle-check text-success':'fa-clock text-warning' ?>"></i><strong class="d-block mt-2"><?= $escape($processingTitle) ?></strong><small class="meta"><?= $escape($processingDetail) ?></small></div><div><i class="fa-solid <?= $flowActive?'fa-circle-check text-success':'fa-clock text-warning' ?>"></i><strong class="d-block mt-2">Novas vendas</strong><small class="meta"><?= $flowActive?'Regra aplicada':'Aguardando ativação' ?></small></div></div>
<?php if($splitRequired&&!$walletReady):?><div class="alert alert-warning mt-3 mb-0"><strong>Ativação pendente.</strong> Valide a Wallet da franquia e habilite o split automático.</div><?php endif;?>
<?php if($exclusiveRequired&&!$exclusiveReady):?><div class="alert alert-warning mt-3 mb-0"><strong>Ativação pendente.</strong> A conta Asaas exclusiva da franquia precisa estar salva, testada e ativa.</div><?php endif;?></div></section>

<section class="card mb-4" id="assinatura"><div class="card-header"><div><h2>Assinatura e evidências</h2><p class="meta">Acompanhe o processo e envie o link manualmente ao responsável.</p></div><?php if($contract['status']==='draft'):?><form method="post" action="<?= $escape($basePath) ?>/admin/franchise-contracts/<?= (int)$contract['id'] ?>/send"><?= $csrfField ?><button class="button button-primary" type="submit" data-confirm-submit="Liberar este contrato para assinatura?"><i class="fa-solid fa-paper-plane"></i> Liberar assinatura</button></form><?php endif;?></div><div class="p-4"><div class="contract-timeline mb-4"><?php foreach($signatureSteps as$step):?><div><i class="fa-solid <?= $step['date']?'fa-circle-check text-success':'fa-clock text-warning' ?>"></i><small class="mt-2"><?= $escape($step['label']) ?></small><strong><?= $step['date']?$escape(date('d/m/Y H:i',strtotime((string)$step['date']))):'Pendente' ?></strong></div><?php endforeach;?></div>
<?php if(!$cancelled&&in_array($contract['status'],['sent','viewed','signed'],true)):?><div class="row g-3"><div class="col-lg-7"><label>Link público de assinatura<div class="input-copy-row"><input id="contract-public-url" readonly value="<?= $escape($publicUrl) ?>"><button class="button button-secondary button-icon" type="button" data-copy-target="contract-public-url" title="Copiar link"><i class="fa-solid fa-copy"></i></button></div></label><small>O envio à franquia permanece manual.</small></div><?php if($signed):?><div class="col-lg-5"><strong><?= $escape((string)$contract['signer_name']) ?></strong><p class="meta mb-1"><?= $escape((string)$contract['signer_email']) ?> · Documento <?= $escape((string)$contract['signer_document']) ?></p><small>IP <?= $escape((string)$contract['signer_ip']) ?></small></div><?php endif;?></div><?php elseif($cancelled&&$signed):?><div class="border rounded-3 p-3"><strong><?= $escape((string)$contract['signer_name']) ?></strong><p class="meta mb-1"><?= $escape((string)$contract['signer_email']) ?> · Documento <?= $escape((string)$contract['signer_document']) ?></p><small>Assinatura histórica preservada · IP <?= $escape((string)$contract['signer_ip']) ?></small></div><?php endif;?>
<?php if($signed):?><details class="mt-3"><summary><strong>Ver integridade da assinatura</strong></summary><div class="mt-2"><label>Hash da evidência<input readonly value="<?= $escape((string)$contract['evidence_hash']) ?>"></label><button class="button button-secondary mt-2" type="button" data-print-page><i class="fa-solid fa-print"></i> Salvar contrato em PDF</button></div></details><?php endif;?></div></section>

<section class="card mb-4"><div class="card-header"><div><h2>Mensalidade do contrato</h2><p class="meta">Cobrança recorrente vinculada ao instrumento, quando contratada.</p></div></div><div class="p-4">
<?php if($monthly<=0):?><div class="alert alert-info mb-0"><strong>Sem mensalidade fixa.</strong> A remuneração seguirá a regra comercial e o processamento financeiro indicados acima.</div>
<?php elseif(!empty($contract['asaas_payment_link_url'])):?><div class="row g-3 align-items-end"><div class="col-lg-8"><label>Link recorrente mensal<div class="input-copy-row"><input id="recurring-payment-url" readonly value="<?= $escape((string)$contract['asaas_payment_link_url']) ?>"><button class="button button-secondary button-icon" type="button" data-copy-target="recurring-payment-url" title="Copiar"><i class="fa-solid fa-copy"></i></button></div></label></div><div class="col-lg-4"><a class="button button-primary" target="_blank" rel="noopener" href="<?= $escape((string)$contract['asaas_payment_link_url']) ?>"><i class="fa-solid fa-arrow-up-right-from-square"></i> Abrir assinatura mensal</a></div></div>
<?php elseif($signed&&!$cancelled):?><p>Gere o link recorrente somente quando desejar enviá-lo à franquia.</p><?php if(!$asaasReady):?><div class="alert alert-warning">A integração Asaas central precisa estar ativa.</div><?php endif;?><form method="post" action="<?= $escape($basePath) ?>/admin/franchise-contracts/<?= (int)$contract['id'] ?>/recurring-link"><?= $csrfField ?><button class="button button-primary" type="submit" <?= !$asaasReady?'disabled':'' ?> data-confirm-submit="Gerar o link mensal real no Asaas?"><i class="fa-solid fa-link"></i> Gerar link mensal</button></form>
<?php else:?><p class="mb-0">Disponível depois da assinatura do contrato.</p><?php endif;?><?php if(!empty($contract['billing_error'])):?><div class="alert alert-danger mt-3 mb-0"><?= $escape((string)$contract['billing_error']) ?></div><?php endif;?></div></section>

<?php if(!$cancelled):?><details class="card mb-4" id="cancelamento"><summary class="card-header"><div><h2>Cancelar contrato</h2><p class="meta">Use somente quando o instrumento não deve mais produzir efeitos.</p></div><i class="fa-solid fa-chevron-down"></i></summary><form class="p-4" method="post" action="<?= $escape($basePath) ?>/admin/franchise-contracts/<?= (int)$contract['id'] ?>/cancel"><?= $csrfField ?><div class="alert alert-warning"><strong>O histórico não será apagado.</strong> A regra comercial será bloqueada, mas cobranças já emitidas no Asaas deverão ser tratadas separadamente.</div><label>Motivo do cancelamento *<textarea name="cancelled_reason" required minlength="10" maxlength="500" rows="3" placeholder="Explique por que este contrato está sendo cancelado."></textarea></label><label class="mt-3"><input type="checkbox" name="confirm_cancel" value="1" required> Confirmo o cancelamento deste contrato e o bloqueio da regra comercial.</label><button class="button button-danger mt-3" type="submit" data-confirm-submit="Cancelar este contrato e bloquear sua regra comercial?"><i class="fa-solid fa-ban"></i> Confirmar cancelamento</button></form></details><?php endif;?>

<details class="card contract-document mb-4"><summary class="card-header"><div><h2>Conteúdo completo do contrato</h2><p class="meta">Abra somente quando precisar consultar ou imprimir o instrumento.</p></div><i class="fa-solid fa-chevron-down"></i></summary><article class="p-4 contract-body"><?= \Interferencia\Modules\Organization\ContractContent::toHtml((string)$contract['content']) ?></article></details>

<?php if(!empty($billingEvents)):?><section class="card"><div class="card-header"><div><h2>Histórico operacional</h2><p class="meta">Eventos financeiros e alterações da regra comercial.</p></div><span class="badge"><?= count($billingEvents) ?></span></div><div class="table-responsive"><table><thead><tr><th>Data</th><th>Evento</th><th>Responsável</th></tr></thead><tbody><?php foreach($billingEvents as$event):?><tr><td><?= $escape(date('d/m/Y H:i',strtotime((string)$event['created_at']))) ?></td><td><?= $escape((string)$event['description']) ?></td><td><?= $escape((string)($event['user_name']?:'Sistema')) ?></td></tr><?php endforeach;?></tbody></table></div></section><?php endif;?>
