<header class="section-heading"><div><span class="status">ADM</span><h1>AVA</h1><p class="meta">Administração acadêmica, integrações e liberações especiais.</p></div></header>
<?php if($message):?><p class="alert alert-success"><?= $escape($message) ?></p><?php endif;?><?php if($error):?><p class="alert alert-danger"><?= $escape($error) ?></p><?php endif;?>
<section class="admin-links integrations-grid mb-4">
<a class="admin-link" href="<?= $escape($basePath) ?>/admin/integrations/moodle"><span class="quick-icon"><i class="fa-solid fa-plug"></i></span><span><strong>Integração AVA</strong><small>Conexão, sincronização e campos acadêmicos</small></span><i class="fa-solid fa-chevron-right"></i></a>
<a class="admin-link" href="<?= $escape($basePath) ?>/students/moodle-reconciliation"><span class="quick-icon"><i class="fa-solid fa-link"></i></span><span><strong>Conciliação</strong><small>Vincular usuários existentes aos alunos do Painel</small></span><i class="fa-solid fa-chevron-right"></i></a>
<a class="admin-link" href="<?= $escape($basePath) ?>/admin/finance/products"><span class="quick-icon"><i class="fa-solid fa-book-open"></i></span><span><strong>Cursos e preços</strong><small>Catálogo sincronizado e condições comerciais</small></span><i class="fa-solid fa-chevron-right"></i></a>
</section>
<section class="card"><div class="card-body"><div class="page-heading"><div><p class="eyebrow">Bolsa ou cortesia</p><h2>Nova liberação especial</h2><p class="meta">Dispense a cobrança com justificativa e prepare o acesso ao curso. A operação ficará registrada no histórico.</p></div></div>
<form method="post" action="<?= $escape($basePath) ?>/admin/ava/waivers" data-confirm-submit="Autorizar a liberação deste curso sem pagamento?"><?= $csrfField ?>
<div class="form-grid">
<div class="form-field"><label for="waiver-unit">Unidade <span class="required">*</span></label><select id="waiver-unit" name="unit_id" required><option value="">Selecione</option><?php foreach($units as$unit):?><option value="<?= (int)$unit['id'] ?>"><?= $escape($unit['name']) ?></option><?php endforeach;?></select></div>
<div class="form-field"><label for="waiver-student">Aluno <span class="required">*</span></label><select id="waiver-student" name="finance_customer_id" required><option value="">Selecione</option><?php foreach($students as$student):?><option value="<?= (int)$student['id'] ?>" data-unit-id="<?= (int)$student['unit_id'] ?>"><?= $escape($student['name'].' · '.$student['unit_name'].' · '.($student['cpf_cnpj']?:'sem CPF')) ?></option><?php endforeach;?></select></div>
<div class="form-field form-field-full"><label for="waiver-course">Curso no AVA <span class="required">*</span></label><select id="waiver-course" name="moodle_course_id" required><option value="">Selecione</option><?php foreach($courses as$course):?><option value="<?= (int)$course['id'] ?>"><?= $escape($course['fullname']) ?></option><?php endforeach;?></select></div>
<div class="form-field form-field-full"><label for="waiver-reason">Motivo da bolsa ou cortesia <span class="required">*</span></label><textarea id="waiver-reason" name="reason" minlength="10" maxlength="500" rows="4" placeholder="Ex.: Bolsa integral aprovada pela direção..." required></textarea><small>Obrigatório para auditoria. Entre 10 e 500 caracteres.</small></div>
</div><div class="alert alert-warning"><strong>Atenção:</strong> esta operação dispensa a cobrança no Asaas. Após salvar, confirme a liberação na tela de Matrículas.</div><button class="button-primary" type="submit"><i class="fa-solid fa-graduation-cap"></i> Autorizar liberação especial</button></form>
</div></section>
