<?php $risk=$risk??'all';$riskLabels=['ok'=>'Regular','pending'=>'Aguardando liberação','blocked'=>'Acesso bloqueado','never_accessed'=>'Nunca acessou','inactive_7'=>'Sem acesso há 7 dias','inactive_15'=>'Sem acesso há 15 dias','inactive_30'=>'Sem acesso há 30 dias','stalled'=>'Progresso parado','unavailable'=>'Acompanhamento não fornecido'];$riskShortLabels=['ok'=>'Regular','pending'=>'A liberar','blocked'=>'Bloqueado','never_accessed'=>'Sem acesso','inactive_7'=>'Inativo 7d','inactive_15'=>'Inativo 15d','inactive_30'=>'Inativo 30d','stalled'=>'Parado','unavailable'=>'Sem dados'];$riskIcons=['ok'=>'circle-check','pending'=>'clock','blocked'=>'lock','never_accessed'=>'triangle-exclamation','inactive_7'=>'clock-rotate-left','inactive_15'=>'triangle-exclamation','inactive_30'=>'circle-exclamation','stalled'=>'pause','unavailable'=>'circle-info']; ?>
<div class="page-heading"><div><p class="eyebrow">Alunos</p><h1>Pedagógico</h1><p class="meta">Identifique alunos que precisam de acompanhamento e execute ações acadêmicas.</p></div><?php if($canManage):?><form method="post" action="<?= $escape($basePath) ?>/students/pedagogical/sync"><?= $csrfField ?><button class="button-secondary" type="submit"><i class="fa-solid fa-rotate"></i> Atualizar acompanhamento</button></form><?php endif;?></div>
<?php if($message):?><p class="alert alert-success"><?= $escape($message) ?></p><?php endif;?><?php if($error):?><p class="alert alert-danger"><?= $escape($error) ?></p><?php endif;?>
<div class="dashboard-grid mb-4">
  <a class="metric-card" href="<?= $escape($basePath) ?>/students/pedagogical?risk=all"><span>Alunos</span><strong><?= (int)$summary['students'] ?></strong><small><?= (int)$summary['enrolments'] ?> matrícula(s)</small></a>
  <a class="metric-card" href="<?= $escape($basePath) ?>/students/pedagogical?risk=never_accessed"><span>Sem primeiro acesso</span><strong><?= (int)$summary['never_accessed'] ?></strong><small>já liberados no AVA</small></a>
  <a class="metric-card" href="<?= $escape($basePath) ?>/students/pedagogical?risk=inactive_15"><span>Sem acesso há 15 dias</span><strong><?= (int)$summary['inactive_15'] ?></strong><small>precisam de contato</small></a>
  <a class="metric-card" href="<?= $escape($basePath) ?>/students/pedagogical?risk=blocked"><span>Acessos bloqueados</span><strong><?= (int)$summary['blocked'] ?></strong><small>em todo o AVA</small></a>
  <div class="metric-card"><span>Aprovados</span><strong><?= (int)($summary['approved']??0) ?></strong><small>com nota de aprovação</small></div>
  <div class="metric-card"><span>Certificados</span><strong><?= (int)($summary['certificates']??0) ?></strong><small>já emitidos no AVA</small></div>
</div>
<?php if((int)$summary['attention']>0):?><div class="alert alert-warning"><i class="fa-solid fa-triangle-exclamation"></i> <strong><?= (int)$summary['attention'] ?> matrícula(s) precisam de atenção pedagógica.</strong> Use o filtro para priorizar os contatos.</div><?php endif;?>
<section class="card pedagogical-card"><div class="card-body">
  <form class="finance-search-row pedagogical-filters mb-3" method="get" action="<?= $escape($basePath) ?>/students/pedagogical"><input name="q" value="<?= $escape($search) ?>" placeholder="Aluno, CPF ou curso"><select name="risk" aria-label="Situação pedagógica"><option value="all">Todas as situações</option><?php foreach($riskLabels as$code=>$label):?><option value="<?= $escape($code) ?>"<?= $risk===$code?' selected':'' ?>><?= $escape($label) ?></option><?php endforeach;?></select><button class="button-primary" type="submit"><i class="fa-solid fa-filter"></i> Filtrar</button></form>
  <div class="table-responsive pedagogical-table-wrap"><table class="pedagogical-table"><thead><tr><th>Aluno</th><th>Curso</th><th>Unidade</th><th>Situação</th><th>Progresso</th><th>Nota</th><th>Último acesso</th><th>AVA</th><th class="pedagogical-actions-heading">Ações</th></tr></thead><tbody>
  <?php if($students===[]):?><tr><td colspan="9">Nenhum aluno encontrado neste filtro.</td></tr><?php endif;?>
  <?php foreach($students as$item):?><?php $last=(int)($item['last_access']??0);$percent=$item['completion_percent']===null?null:max(0,min(100,(float)$item['completion_percent']));$grade=$item['academic_grade_percent']===null?null:max(0,min(100,(float)$item['academic_grade_percent']));$gradeStatus=(string)($item['academic_grade_status']??'not_available');$certificateStatus=(string)($item['academic_certificate_status']??'not_available');$certificateUrl=trim((string)($item['academic_certificate_url']??''));$suspended=(int)($item['suspended']??0)===1;$riskCode=(string)$item['risk_code'];$riskClass=in_array($riskCode,['inactive_30','blocked'],true)?'connection-error':(in_array($riskCode,['never_accessed','inactive_15','stalled','pending'],true)?'connection-awaiting_official_api':'connection-connected'); ?>
    <tr>
      <td><strong><?= $escape($item['name']) ?></strong><div class="meta"><?= $escape($item['cpf_cnpj']?:'CPF não informado') ?></div></td><td><?= $escape($item['course_name']) ?></td><td><?= $escape($item['unit_name']) ?></td>
      <td><span class="connection-badge pedagogical-risk-badge <?= $riskClass ?>" title="<?= $escape($riskLabels[$riskCode]??'Em acompanhamento') ?>"><i class="fa-solid fa-<?= $escape($riskIcons[$riskCode]??'circle-info') ?>"></i> <?= $escape($riskShortLabels[$riskCode]??'Acompanhar') ?></span></td>
      <td><?php if($item['completion_status']==='not_configured'):?><span class="badge badge-warning">Sem critérios no AVA</span><?php elseif($percent===null):?><span class="meta">Não consultado</span><?php else:?><div style="min-width:120px"><div style="height:8px;background:#e5e7eb;border-radius:999px;overflow:hidden"><span style="display:block;height:100%;width:<?= $percent ?>%;background:#ed1c24"></span></div><small><?= number_format($percent,0,',','.') ?>% · <?= $escape(match($item['completion_status']){'completed'=>'Concluído','in_progress'=>'Em andamento','not_started'=>'Não iniciado',default=>'Indisponível'}) ?></small></div><?php endif;?></td>
      <td><?php if($grade===null):?><span class="meta">Não fornecida</span><?php else:?><strong><?= number_format($grade,1,',','.') ?>%</strong><div><span class="connection-badge <?= $gradeStatus==='passed'?'connection-connected':($gradeStatus==='failed'?'connection-error':'connection-awaiting_official_api') ?>"><?= $escape(match($gradeStatus){'passed'=>'Aprovado','failed'=>'Reprovado',default=>'Em avaliação'}) ?></span></div><?php endif;?></td>
      <td><?= $last>0?$escape(date('d/m/Y H:i',$last)):'Ainda não acessou' ?></td>
      <td><div class="pedagogical-ava-cell"><?php if($suspended):?><span class="connection-badge connection-error"><i class="fa-solid fa-lock"></i> Bloqueado</span><?php elseif($item['moodle_enrolment_status']==='released'):?><span class="connection-badge connection-connected"><i class="fa-solid fa-circle-check"></i> Liberado</span><?php else:?><span class="connection-badge connection-awaiting_official_api"><i class="fa-solid fa-clock"></i> Pendente</span><?php endif;?><?php if($certificateStatus==='issued'&&$certificateUrl!==''):?><a class="pedagogical-certificate" href="<?= $escape($certificateUrl) ?>" target="_blank" rel="noopener" title="Abrir certificado"><i class="fa-solid fa-certificate"></i> Certificado</a><?php elseif($certificateStatus==='issued'):?><small><i class="fa-solid fa-certificate"></i> Emitido</small><?php elseif($certificateStatus==='available'):?><small><i class="fa-solid fa-certificate"></i> Disponível</small><?php else:?><small class="meta">Sem certificado</small><?php endif;?></div></td>
      <td class="pedagogical-actions-cell"><div class="table-actions pedagogical-actions"><a class="button-secondary button-small pedagogical-action" href="<?= $escape($basePath) ?>/finance/customers/<?= (int)$item['customer_id'] ?>" title="Abrir cadastro" aria-label="Abrir cadastro"><i class="fa-solid fa-eye"></i></a><?php if($canManage&&$item['moodle_enrolment_status']==='released'):?><a class="button-secondary button-small pedagogical-action" href="<?= $escape($basePath) ?>/students/enrollments/<?= (int)$item['enrollment_id'] ?>/access" title="Dados de acesso do aluno" aria-label="Dados de acesso do aluno"><i class="fa-solid fa-key"></i></a><?php endif;?><?php if($navigation['tickets_create']??false):?><a class="button-secondary button-small pedagogical-action" href="<?= $escape($basePath) ?>/tickets/create?student=<?= (int)$item['customer_id'] ?>" title="Abrir ticket para este aluno" aria-label="Abrir ticket"><i class="fa-solid fa-ticket"></i></a><?php endif;?><?php if($canManage):?><a class="button-secondary button-small pedagogical-action" href="<?= $escape($basePath) ?>/students/enrollments/create?student=<?= (int)$item['customer_id'] ?>" title="Nova matrícula" aria-label="Nova matrícula"><i class="fa-solid fa-graduation-cap"></i></a><?php endif;?><?php if($canManage&&(int)($item['ava_user_id']??0)>0):?><form class="pedagogical-action-form" method="post" action="<?= $escape($basePath) ?>/students/enrollments/<?= (int)$item['enrollment_id'] ?>/ava-status" onsubmit="return confirm('<?= $suspended?'Reativar o acesso deste aluno ao AVA?':'Bloquear este aluno em todo o AVA? Ele não conseguirá acessar nenhum curso.' ?>')"><?= $csrfField ?><input type="hidden" name="status" value="<?= $suspended?'active':'blocked' ?>"><input type="hidden" name="confirm" value="1"><button class="<?= $suspended?'button-secondary':'button-danger' ?> button-small pedagogical-action<?= $suspended?'':' pedagogical-action-danger' ?>" type="submit" title="<?= $suspended?'Reativar acesso ao AVA':'Bloquear acesso em todo o AVA' ?>" aria-label="<?= $suspended?'Reativar acesso ao AVA':'Bloquear acesso ao AVA' ?>"><i class="fa-solid fa-<?= $suspended?'unlock':'user-lock' ?>"></i></button></form><?php endif;?></div></td>
    </tr>
  <?php endforeach;?></tbody></table></div>
</div></section>
<style>
.pedagogical-card{overflow:hidden}
.pedagogical-table-wrap{margin:0;border:1px solid #e0e6ea;border-radius:.85rem;background:#fff}
.pedagogical-table{width:100%;min-width:55.5rem;margin:0;table-layout:fixed}
.pedagogical-table th,.pedagogical-table td{box-sizing:border-box;padding:.78rem .62rem;overflow-wrap:anywhere}
.pedagogical-table th{color:#263544;font-size:.79rem;line-height:1.25}
.pedagogical-table td{font-size:.88rem;line-height:1.45}
.pedagogical-table tbody tr{transition:background-color .15s ease}
.pedagogical-table tbody tr:hover{background:#fffafb}
.pedagogical-table th:nth-child(1){width:7rem}.pedagogical-table th:nth-child(2){width:7rem}.pedagogical-table th:nth-child(3){width:3.75rem}.pedagogical-table th:nth-child(4){width:6rem}.pedagogical-table th:nth-child(5){width:5.5rem}.pedagogical-table th:nth-child(6){width:3.5rem}.pedagogical-table th:nth-child(7){width:4.5rem}.pedagogical-table th:nth-child(8){width:6rem}.pedagogical-table th:nth-child(9){width:12.25rem}
.pedagogical-table td:nth-child(5)>div{min-width:0!important}
.pedagogical-table .connection-badge{max-width:100%;line-height:1.25;text-align:center}.pedagogical-risk-badge{white-space:nowrap;font-size:.73rem}
.pedagogical-ava-cell{display:grid;justify-items:start;gap:.35rem}.pedagogical-ava-cell small{font-size:.72rem;line-height:1.2}.pedagogical-certificate{display:inline-flex;align-items:center;gap:.28rem;color:var(--inter-accent-dark);font-size:.72rem;font-weight:700;text-decoration:none}.pedagogical-certificate:hover{text-decoration:underline}
.pedagogical-actions-heading,.pedagogical-actions-cell{position:sticky;right:0;z-index:3;background:#fff;box-shadow:-10px 0 16px -16px rgb(23 33 43 / 55%)}
.pedagogical-actions-heading{z-index:4;background:#f8fafb}
.pedagogical-actions{display:flex;gap:.25rem;align-items:center;justify-content:flex-end;width:100%}
.pedagogical-action-form{display:block;width:2rem;height:2rem;margin:0!important}
.pedagogical-action{display:inline-flex!important;align-items:center!important;justify-content:center!important;box-sizing:border-box!important;width:2rem!important;min-width:2rem!important;height:2rem!important;min-height:2rem!important;margin:0!important;padding:0!important;border-radius:.5rem!important;line-height:1!important}
.pedagogical-action i{margin:0!important;font-size:.88rem;line-height:1}
.pedagogical-action-danger{border:1px solid #b4232c!important;background:#b4232c!important;color:#fff!important}
.pedagogical-action-danger:hover{border-color:#8f1720!important;background:#8f1720!important}
@media(max-width:760px){.pedagogical-filters{grid-template-columns:1fr}.pedagogical-filters button{width:100%}.pedagogical-table{min-width:55.5rem}.pedagogical-table th,.pedagogical-table td{padding:.65rem .5rem}.pedagogical-actions-heading,.pedagogical-actions-cell{box-shadow:-12px 0 18px -16px rgb(23 33 43 / 75%)}}
</style>
