<?php $risk=$risk??'all';$riskLabels=['ok'=>'Regular','pending'=>'Aguardando liberação','blocked'=>'Acesso bloqueado','never_accessed'=>'Nunca acessou','inactive_7'=>'Sem acesso há 7 dias','inactive_15'=>'Sem acesso há 15 dias','inactive_30'=>'Sem acesso há 30 dias','stalled'=>'Progresso parado','unavailable'=>'Acompanhamento não fornecido'];$riskIcons=['ok'=>'circle-check','pending'=>'clock','blocked'=>'lock','never_accessed'=>'triangle-exclamation','inactive_7'=>'clock-rotate-left','inactive_15'=>'triangle-exclamation','inactive_30'=>'circle-exclamation','stalled'=>'pause','unavailable'=>'circle-info']; ?>
<div class="page-heading"><div><p class="eyebrow">Alunos</p><h1>Pedagógico</h1><p class="meta">Identifique alunos que precisam de acompanhamento e execute ações acadêmicas.</p></div><?php if($canManage):?><form method="post" action="<?= $escape($basePath) ?>/students/pedagogical/sync"><?= $csrfField ?><button class="button-secondary" type="submit"><i class="fa-solid fa-rotate"></i> Atualizar acompanhamento</button></form><?php endif;?></div>
<?php if($message):?><p class="alert alert-success"><?= $escape($message) ?></p><?php endif;?><?php if($error):?><p class="alert alert-danger"><?= $escape($error) ?></p><?php endif;?>
<div class="dashboard-grid mb-4">
  <a class="metric-card" href="<?= $escape($basePath) ?>/students/pedagogical?risk=all"><span>Alunos</span><strong><?= (int)$summary['students'] ?></strong><small><?= (int)$summary['enrolments'] ?> matrícula(s)</small></a>
  <a class="metric-card" href="<?= $escape($basePath) ?>/students/pedagogical?risk=never_accessed"><span>Sem primeiro acesso</span><strong><?= (int)$summary['never_accessed'] ?></strong><small>já liberados no AVA</small></a>
  <a class="metric-card" href="<?= $escape($basePath) ?>/students/pedagogical?risk=inactive_15"><span>Sem acesso há 15 dias</span><strong><?= (int)$summary['inactive_15'] ?></strong><small>precisam de contato</small></a>
  <a class="metric-card" href="<?= $escape($basePath) ?>/students/pedagogical?risk=blocked"><span>Acessos bloqueados</span><strong><?= (int)$summary['blocked'] ?></strong><small>em todo o AVA</small></a>
  <div class="metric-card"><span>Aprovados</span><strong><?= (int)($summary['approved']??0) ?></strong><small>com nota de aprovação</small></div>
  <div class="metric-card"><span>Certificados</span><strong><?= (int)($summary['certificates']??0) ?></strong><small>já emitidos no AVA</small></div>
</div>
<?php if((int)$summary['attention']>0):?><div class="alert alert-warning"><i class="fa-solid fa-triangle-exclamation"></i> <strong><?= (int)$summary['attention'] ?> matrícula(s) precisam de atenção pedagógica.</strong> Use o filtro para priorizar os contatos.</div><?php endif;?>
<section class="card"><div class="card-body">
  <form class="finance-search-row mb-3" method="get" action="<?= $escape($basePath) ?>/students/pedagogical"><input name="q" value="<?= $escape($search) ?>" placeholder="Aluno, CPF ou curso"><select name="risk" aria-label="Situação pedagógica"><option value="all">Todas as situações</option><?php foreach($riskLabels as$code=>$label):?><option value="<?= $escape($code) ?>"<?= $risk===$code?' selected':'' ?>><?= $escape($label) ?></option><?php endforeach;?></select><button class="button-primary" type="submit"><i class="fa-solid fa-filter"></i> Filtrar</button></form>
  <div class="table-responsive"><table><thead><tr><th>Aluno</th><th>Curso</th><th>Unidade</th><th>Situação</th><th>Progresso</th><th>Nota</th><th>Último acesso</th><th>Certificado</th><th>Acesso AVA</th><th>Ações</th></tr></thead><tbody>
  <?php if($students===[]):?><tr><td colspan="10">Nenhum aluno encontrado neste filtro.</td></tr><?php endif;?>
  <?php foreach($students as$item):?><?php $last=(int)($item['last_access']??0);$percent=$item['completion_percent']===null?null:max(0,min(100,(float)$item['completion_percent']));$grade=$item['academic_grade_percent']===null?null:max(0,min(100,(float)$item['academic_grade_percent']));$gradeStatus=(string)($item['academic_grade_status']??'not_available');$certificateStatus=(string)($item['academic_certificate_status']??'not_available');$certificateUrl=trim((string)($item['academic_certificate_url']??''));$suspended=(int)($item['suspended']??0)===1;$riskCode=(string)$item['risk_code'];$riskClass=in_array($riskCode,['inactive_30','blocked'],true)?'connection-error':(in_array($riskCode,['never_accessed','inactive_15','stalled','pending'],true)?'connection-awaiting_official_api':'connection-connected'); ?>
    <tr>
      <td><strong><?= $escape($item['name']) ?></strong><div class="meta"><?= $escape($item['cpf_cnpj']?:'CPF não informado') ?></div></td><td><?= $escape($item['course_name']) ?></td><td><?= $escape($item['unit_name']) ?></td>
      <td><span class="connection-badge <?= $riskClass ?>"><i class="fa-solid fa-<?= $escape($riskIcons[$riskCode]??'circle-info') ?>"></i> <?= $escape($riskLabels[$riskCode]??'Em acompanhamento') ?></span></td>
      <td><?php if($item['completion_status']==='not_configured'):?><span class="badge badge-warning">Sem critérios no AVA</span><?php elseif($percent===null):?><span class="meta">Não consultado</span><?php else:?><div style="min-width:120px"><div style="height:8px;background:#e5e7eb;border-radius:999px;overflow:hidden"><span style="display:block;height:100%;width:<?= $percent ?>%;background:#ed1c24"></span></div><small><?= number_format($percent,0,',','.') ?>% · <?= $escape(match($item['completion_status']){'completed'=>'Concluído','in_progress'=>'Em andamento','not_started'=>'Não iniciado',default=>'Indisponível'}) ?></small></div><?php endif;?></td>
      <td><?php if($grade===null):?><span class="meta">Não fornecida</span><?php else:?><strong><?= number_format($grade,1,',','.') ?>%</strong><div><span class="connection-badge <?= $gradeStatus==='passed'?'connection-connected':($gradeStatus==='failed'?'connection-error':'connection-awaiting_official_api') ?>"><?= $escape(match($gradeStatus){'passed'=>'Aprovado','failed'=>'Reprovado',default=>'Em avaliação'}) ?></span></div><?php endif;?></td>
      <td><?= $last>0?$escape(date('d/m/Y H:i',$last)):'Ainda não acessou' ?></td>
      <td><?php if($certificateStatus==='issued'&&$certificateUrl!==''):?><a class="button-secondary button-small" href="<?= $escape($certificateUrl) ?>" target="_blank" rel="noopener" title="Abrir certificado"><i class="fa-solid fa-certificate"></i></a><?php elseif($certificateStatus==='issued'):?><span class="connection-badge connection-connected"><i class="fa-solid fa-certificate"></i> Emitido</span><?php elseif($certificateStatus==='available'):?><span class="connection-badge connection-awaiting_official_api">Disponível</span><?php else:?><span class="meta">Não fornecido</span><?php endif;?></td>
      <td><?php if($suspended):?><span class="connection-badge connection-error"><i class="fa-solid fa-lock"></i> Bloqueado</span><?php elseif($item['moodle_enrolment_status']==='released'):?><span class="connection-badge connection-connected"><i class="fa-solid fa-circle-check"></i> Liberado</span><?php else:?><span class="connection-badge connection-awaiting_official_api"><i class="fa-solid fa-clock"></i> Pendente</span><?php endif;?></td>
      <td><div class="table-actions"><a class="button-secondary button-small" href="<?= $escape($basePath) ?>/finance/customers/<?= (int)$item['customer_id'] ?>" title="Abrir cadastro" aria-label="Abrir cadastro"><i class="fa-solid fa-eye"></i></a><?php if($canManage&&$item['moodle_enrolment_status']==='released'):?><a class="button-secondary button-small" href="<?= $escape($basePath) ?>/students/enrollments/<?= (int)$item['enrollment_id'] ?>/access" title="Dados de acesso do aluno" aria-label="Dados de acesso do aluno"><i class="fa-solid fa-key"></i></a><?php endif;?><?php if($navigation['tickets_create']??false):?><a class="button-secondary button-small" href="<?= $escape($basePath) ?>/tickets/create?student=<?= (int)$item['customer_id'] ?>" title="Abrir ticket para este aluno" aria-label="Abrir ticket"><i class="fa-solid fa-ticket"></i></a><?php endif;?><?php if($canManage):?><a class="button-secondary button-small" href="<?= $escape($basePath) ?>/students/enrollments/create?student=<?= (int)$item['customer_id'] ?>" title="Nova matrícula" aria-label="Nova matrícula"><i class="fa-solid fa-graduation-cap"></i></a><?php endif;?><?php if($canManage&&(int)($item['ava_user_id']??0)>0):?><form method="post" action="<?= $escape($basePath) ?>/students/enrollments/<?= (int)$item['enrollment_id'] ?>/ava-status" onsubmit="return confirm('<?= $suspended?'Reativar o acesso deste aluno ao AVA?':'Bloquear este aluno em todo o AVA? Ele não conseguirá acessar nenhum curso.' ?>')"><?= $csrfField ?><input type="hidden" name="status" value="<?= $suspended?'active':'blocked' ?>"><input type="hidden" name="confirm" value="1"><button class="<?= $suspended?'button-secondary':'button-danger' ?> button-small" type="submit" title="<?= $suspended?'Reativar acesso ao AVA':'Bloquear acesso em todo o AVA' ?>" aria-label="<?= $suspended?'Reativar acesso ao AVA':'Bloquear acesso ao AVA' ?>"><i class="fa-solid fa-<?= $suspended?'unlock':'user-lock' ?>"></i></button></form><?php endif;?></div></td>
    </tr>
  <?php endforeach;?></tbody></table></div>
</div></section>
