<div class="page-heading"><div><p class="eyebrow">ADM · Integrações</p><h1>Moodle</h1><p class="meta">Unifique cursos, usuários e matrículas acadêmicas com o PAINEL INTER.</p></div></div>
<?php if($message):?><p class="alert alert-success"><?= $escape($message) ?></p><?php endif;?>
<?php if($error):?><p class="alert alert-danger"><?= $escape($error) ?></p><?php endif;?>
<?php if(!$encryptionReady):?><p class="alert alert-warning"><strong>Proteção pendente.</strong> A chave-mestra do servidor deve estar configurada antes de salvar o token.</p><?php endif;?>

<section class="card mb-4"><div class="card-body">
<div class="actions"><div><h2>Conexão</h2><p class="meta mb-0">O token permanece criptografado e nunca é exibido novamente.</p></div><?php if($settings['configured']):?><span class="connection-badge <?= $settings['is_active']?'connection-approved':'connection-pending' ?>"><?= $settings['is_active']?'Ativa':'Inativa' ?></span><?php endif;?></div>
<?php if($settings['configured']):?><p><strong>Estado atual</strong><br><span class="meta"><?= $escape($settings['base_url']) ?> · token terminado em ••••<?= $escape($settings['token_last4']) ?></span></p><?php endif;?>
<form method="post" action="<?= $escape($basePath) ?>/admin/integrations/moodle"><?= $csrfField ?>
<div class="row"><div class="col-sm-6 form-field"><label for="moodle-url">Endereço do Moodle <span class="required">*</span></label><input id="moodle-url" name="base_url" type="url" required placeholder="https://moodle.exemplo.com.br" value="<?= $escape($settings['base_url']) ?>" <?= !$encryptionReady?'disabled':'' ?>></div><div class="col-sm-6 form-field"><label for="moodle-token">Novo token <span class="required">*</span></label><input id="moodle-token" name="token" type="password" autocomplete="new-password" required placeholder="Token do serviço web" <?= !$encryptionReady?'disabled':'' ?>></div></div>
<label class="checkbox-row"><input type="checkbox" name="is_active" value="1" checked> Ativar integração após salvar</label>
<div class="d-flex gap-2 flex-wrap"><button class="button-primary" type="submit" <?= !$encryptionReady?'disabled':'' ?>><i class="fa-solid fa-floppy-disk"></i> Salvar conexão</button></form><?php if($settings['configured']):?><form method="post" action="<?= $escape($basePath) ?>/admin/integrations/moodle/test"><?= $csrfField ?><button class="button-secondary" type="submit"><i class="fa-solid fa-plug-circle-check"></i> Testar conexão</button></form><?php endif;?></div>
<?php if($settings['last_tested_at']):?><p class="meta mt-3">Último teste: <?= $escape(date('d/m/Y H:i',strtotime($settings['last_tested_at']))) ?><?= $settings['last_error']?' · '.$escape($settings['last_error']):'' ?></p><?php endif;?>
</div></section>

<section class="card mb-4" id="synchronization"><div class="card-body">
<div class="actions"><div><h2>Sincronização somente leitura</h2><p class="meta mb-0">O Painel consulta lotes de até cinco cursos. Nenhum usuário ou matrícula será alterado no Moodle.</p></div><form method="post" action="<?= $escape($basePath) ?>/admin/integrations/moodle/sync"><?= $csrfField ?><button class="button-primary" type="submit" <?= !$connectionReady?'disabled':'' ?>><i class="fa-solid fa-rotate"></i> <?= $settings['sync_complete']?'Conferir novamente':'Sincronizar próximo lote' ?></button></form></div>
<div class="dashboard-grid mt-4"><article class="metric-card"><span>Cursos</span><strong><?= number_format($summary['courses'],0,',','.') ?></strong></article><article class="metric-card"><span>Usuários acadêmicos</span><strong><?= number_format($summary['users'],0,',','.') ?></strong></article><article class="metric-card"><span>Matrículas</span><strong><?= number_format($summary['enrolments'],0,',','.') ?></strong></article><article class="metric-card"><span>Aguardando conciliação</span><strong><?= number_format($summary['review'],0,',','.') ?></strong></article></div>
<div class="actions mt-4"><p class="meta mb-0">Última sincronização: <?= $settings['last_synced_at']?$escape(date('d/m/Y H:i',strtotime($settings['last_synced_at']))):'ainda não realizada' ?>.</p><form method="post" action="<?= $escape($basePath) ?>/admin/integrations/moodle/sync/reset" data-confirm-submit="Reiniciar a conferência completa? Nenhum dado será apagado."><?= $csrfField ?><button class="button-secondary" type="submit" <?= !$connectionReady?'disabled':'' ?>><i class="fa-solid fa-arrow-rotate-left"></i> Reiniciar conferência</button></form></div>
</div></section>

<section class="card"><div class="card-body"><div class="actions"><div><h2>Cursos encontrados</h2><p class="meta mb-0">Prévia dos cursos já importados para conferência.</p></div><span class="count-badge"><?= count($courses) ?></span></div><div class="table-responsive mt-3"><table><thead><tr><th>Curso</th><th>Nome breve</th><th>Identificador</th><th>Situação</th><th>Sincronizado</th></tr></thead><tbody><?php if($courses===[]):?><tr><td colspan="5">Nenhum curso sincronizado.</td></tr><?php endif;?><?php foreach($courses as$course):?><tr><td><strong><?= $escape($course['fullname']) ?></strong></td><td><?= $escape($course['shortname']) ?></td><td><?= $escape($course['idnumber']?:'—') ?></td><td><?= (int)$course['visible']===1?'Visível':'Oculto' ?></td><td><?= $escape(date('d/m/Y H:i',strtotime($course['synced_at']))) ?></td></tr><?php endforeach;?></tbody></table></div></div></section>
