<?php
$enabled=(int)($settings['is_enabled']??0)===1;
$selectedIds=array_map('intval',$selectedProductIds??[]);
$publicUrl=rtrim((string)$basePath,'/').'/site';
?>
<style>
.site-admin{max-width:80rem;margin:0 auto}.site-admin-grid{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(18rem,.7fr);gap:1rem}.site-editor-card{padding:1.35rem}.site-editor-section{padding:0 0 1.25rem;margin-bottom:1.25rem;border-bottom:1px solid #e1e7eb}.site-editor-section:last-child{padding:0;margin:0;border:0}.site-editor-section>header{display:flex;gap:.75rem;align-items:flex-start;margin-bottom:1rem}.site-editor-section>header i{display:grid;place-items:center;width:2.35rem;height:2.35rem;flex:0 0 2.35rem;border-radius:.65rem;background:#fff0f1;color:var(--inter-accent)}.site-editor-section h2,.site-editor-section p{margin:0}.site-fields{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:1rem}.site-fields label{margin:0}.site-fields .full{grid-column:1/-1}.site-fields input,.site-fields select,.site-fields textarea{width:100%}.site-course-list{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:.7rem}.site-course-option{position:relative;display:block;margin:0}.site-course-option input{position:absolute;opacity:0}.site-course-option span{display:flex;align-items:center;justify-content:space-between;gap:.8rem;height:100%;padding:.85rem;border:1px solid #dfe6ea;border-radius:.75rem;background:#fff;cursor:pointer}.site-course-option input:checked+span{border-color:var(--inter-accent);background:#fff5f5}.site-course-option small{display:block;color:var(--inter-muted);font-weight:400}.site-admin-side{display:grid;align-content:start;gap:1rem}.site-admin-side .card{padding:1.2rem}.site-state{display:grid;gap:.8rem}.site-state-row{display:flex;align-items:center;justify-content:space-between;gap:.8rem;padding-bottom:.7rem;border-bottom:1px solid #e5eaed}.site-state-row:last-child{padding:0;border:0}.site-public-address{display:block;padding:.75rem;border-radius:.65rem;background:#f4f7f9;overflow-wrap:anywhere}.site-savebar{position:sticky;bottom:1rem;display:flex;align-items:center;justify-content:space-between;gap:1rem;margin-top:1rem;padding:1rem 1.2rem;border:1px solid #dfe5e9;border-radius:.9rem;background:rgba(255,255,255,.96);box-shadow:0 .7rem 1.8rem rgb(23 33 43 / 12%)}.site-savebar p{margin:0}@media(max-width:900px){.site-admin-grid{grid-template-columns:1fr}.site-admin-side{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.site-fields,.site-course-list,.site-admin-side{grid-template-columns:1fr}.site-savebar{align-items:stretch;flex-direction:column}.site-savebar .button{width:100%}}
</style>
<div class="site-admin">
 <header class="page-header"><div><p class="eyebrow">ADM · Site Institucional</p><h1>Site da franquia</h1><p>Personalize o conteúdo público sem alterar a estrutura protegida da plataforma.</p></div><div class="page-actions"><a class="button button-secondary" href="<?= $escape($publicUrl) ?>?preview=1" target="_blank"><i class="fa-solid fa-eye"></i> Pré-visualizar</a></div></header>
 <?php if(!empty($message)):?><div class="alert alert-success"><?= $escape($message) ?></div><?php endif;?>
 <?php if(!empty($error)):?><div class="alert alert-danger"><?= $escape($error) ?></div><?php endif;?>
 <?php if(!$enabled):?><div class="alert alert-warning"><strong>Site ainda não liberado.</strong> O ADM Central precisa ativar este recurso para a franquia antes da publicação.</div><?php endif;?>
 <form method="post" action="<?= $escape($basePath) ?>/admin/site"><?= $csrfField ?>
  <div class="site-admin-grid">
   <main class="card site-editor-card">
    <section class="site-editor-section"><header><i class="fa-solid fa-sliders"></i><div><h2>Formato e publicação</h2><p class="meta">Escolha somente entre as opções liberadas pelo ADM Central.</p></div></header><div class="site-fields">
     <label>Formato do site<select name="selected_mode" required><?php if((int)($settings['allow_catalog']??0)===1):?><option value="catalog" <?= ($settings['selected_mode']??'catalog')==='catalog'?'selected':'' ?>>Catálogo de cursos</option><?php endif;?><?php if((int)($settings['allow_store']??0)===1):?><option value="store" <?= ($settings['selected_mode']??'')==='store'?'selected':'' ?>>Loja virtual</option><?php endif;?></select></label>
     <label>Situação<select name="publication_status"><option value="draft" <?= ($settings['publication_status']??'draft')==='draft'?'selected':'' ?>>Rascunho</option><option value="published" <?= ($settings['publication_status']??'')==='published'?'selected':'' ?>>Publicado</option><option value="maintenance" <?= ($settings['publication_status']??'')==='maintenance'?'selected':'' ?>>Manutenção</option></select></label>
    </div></section>
    <section class="site-editor-section"><header><i class="fa-solid fa-pen-ruler"></i><div><h2>Página inicial</h2><p class="meta">Textos principais da vitrine institucional.</p></div></header><div class="site-fields">
     <label>Nome do site *<input required maxlength="160" name="site_title" value="<?= $escape($settings['site_title']??'') ?>"></label>
     <label>Título principal *<input required maxlength="190" name="hero_title" value="<?= $escape($settings['hero_title']??'') ?>"></label>
     <label class="full">Texto de apresentação<textarea rows="3" maxlength="700" name="hero_text"><?= $escape($settings['hero_text']??'') ?></textarea></label>
     <label>Título institucional<input maxlength="160" name="about_title" value="<?= $escape($settings['about_title']??'') ?>"></label>
     <label class="full">Sobre a franquia<textarea rows="6" maxlength="5000" name="about_text"><?= $escape($settings['about_text']??'') ?></textarea></label>
    </div></section>
    <section class="site-editor-section"><header><i class="fa-solid fa-book-open"></i><div><h2>Cursos em destaque</h2><p class="meta">Selecione até <?= (int)($settings['max_featured_courses']??6) ?> cursos. A lista vem do catálogo autorizado da franquia.</p></div></header>
     <?php if($products===[]):?><p class="meta">Nenhum curso ativo e com preço está disponível no momento.</p><?php else:?><div class="site-course-list"><?php foreach($products as$product):?><label class="site-course-option"><input type="checkbox" name="product_ids[]" value="<?= (int)$product['id'] ?>" <?= in_array((int)$product['id'],$selectedIds,true)?'checked':'' ?>><span><span><strong><?= $escape($product['name']) ?></strong><small><?= $escape($product['description']??'Curso disponível') ?></small></span><strong>R$ <?= number_format((float)$product['value'],2,',','.') ?></strong></span></label><?php endforeach;?></div><?php endif;?>
    </section>
    <section class="site-editor-section"><header><i class="fa-solid fa-address-card"></i><div><h2>Contato e redes</h2><p class="meta">Canais que aparecerão no rodapé e nas chamadas do site.</p></div></header><div class="site-fields">
     <label>E-mail<input type="email" maxlength="190" name="contact_email" value="<?= $escape($settings['contact_email']??'') ?>"></label><label>Telefone<input maxlength="30" name="contact_phone" value="<?= $escape($settings['contact_phone']??'') ?>"></label>
     <label>WhatsApp<input maxlength="30" name="whatsapp" value="<?= $escape($settings['whatsapp']??'') ?>"></label><label>Instagram<input type="url" maxlength="500" name="instagram_url" value="<?= $escape($settings['instagram_url']??'') ?>" placeholder="https://instagram.com/..."></label>
     <label>Facebook<input type="url" maxlength="500" name="facebook_url" value="<?= $escape($settings['facebook_url']??'') ?>" placeholder="https://facebook.com/..."></label>
    </div></section>
    <section class="site-editor-section"><header><i class="fa-solid fa-magnifying-glass"></i><div><h2>Buscadores</h2><p class="meta">Título e descrição usados pelo Google e no compartilhamento.</p></div></header><div class="site-fields"><label>Título para busca<input maxlength="190" name="seo_title" value="<?= $escape($settings['seo_title']??'') ?>"></label><label class="full">Descrição para busca<textarea rows="3" maxlength="320" name="seo_description"><?= $escape($settings['seo_description']??'') ?></textarea></label></div></section>
   </main>
   <aside class="site-admin-side">
    <section class="card"><p class="eyebrow">Governança</p><h2>Recursos liberados</h2><div class="site-state"><div class="site-state-row"><span>Modelo-base</span><strong><?= $escape(ucfirst((string)($settings['template_key']??'modern'))) ?></strong></div><div class="site-state-row"><span>Catálogo</span><span class="badge <?= (int)($settings['allow_catalog']??0)===1?'badge-success':'badge-warning' ?>"><?= (int)($settings['allow_catalog']??0)===1?'Liberado':'Bloqueado' ?></span></div><div class="site-state-row"><span>Loja</span><span class="badge <?= (int)($settings['allow_store']??0)===1?'badge-success':'badge-warning' ?>"><?= (int)($settings['allow_store']??0)===1?'Liberada':'Bloqueada' ?></span></div><div class="site-state-row"><span>Páginas extras</span><strong><?= (int)($settings['allow_custom_pages']??0)===1?(int)$settings['max_pages']:'Não liberadas' ?></strong></div></div></section>
    <section class="card"><p class="eyebrow">Endereço público</p><h2>Acesso provisório</h2><code class="site-public-address"><?= $escape($publicUrl) ?></code><p class="meta">O domínio próprio apontará para esta mesma estrutura quando for validado pelo ADM Central.</p></section>
   </aside>
  </div>
  <footer class="site-savebar"><p class="meta"><i class="fa-solid fa-shield-halved"></i> A identidade visual é reaproveitada do Painel da franquia.</p><button class="button button-primary" type="submit" <?= !$enabled?'disabled':'' ?>><i class="fa-solid fa-floppy-disk"></i> Salvar Site Institucional</button></footer>
 </form>
</div>
