<section class="card site-module site-panel" data-site-panel="cursos" hidden>
 <header class="site-module-head"><div><p class="eyebrow">SEO dos cursos</p><h2>Como cada curso aparece no Google</h2><p class="meta">Personalize título e resumo sem alterar o nome acadêmico do curso.</p></div></header>
 <?php foreach(($products??[])as$product):$seo=$productSeo[(int)$product['id']]??[];?><details class="site-details"><summary><span class="site-summary"><i class="fa-solid fa-magnifying-glass"></i><span><?= $escape($product['name']) ?></span></span><i class="fa-solid fa-chevron-down"></i></summary><form class="site-detail-form" method="post" action="<?= $escape($basePath) ?>/admin/site/products/<?= (int)$product['id'] ?>/seo"><?= $csrfField ?><div class="site-fields"><label>Título para busca<input maxlength="190" name="seo_title" value="<?= $escape($seo['seo_title']??'') ?>" placeholder="<?= $escape($product['name']) ?>"></label><label>Descrição para busca<textarea rows="3" maxlength="320" name="seo_description" placeholder="Resumo que aparecerá nos buscadores."><?= $escape($seo['seo_description']??'') ?></textarea></label></div><div class="site-actions"><button class="button button-primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Salvar SEO</button></div></form></details><?php endforeach;?>
</section>

<section class="card site-module site-panel" data-site-panel="banners" hidden>
 <header class="site-module-head"><div><p class="eyebrow">DigitalOcean Spaces</p><h2>Biblioteca de imagens da franquia</h2><p class="meta">Arquivos isolados por franquia, otimizados automaticamente e exibidos em enquadramento padronizado.</p></div><span class="badge"><?= count($media) ?> imagem(ns)</span></header>
 <details class="site-details"><summary><span class="site-summary"><i class="fa-solid fa-cloud-arrow-up"></i><span>Enviar nova imagem</span></span><i class="fa-solid fa-chevron-down"></i></summary><form class="site-detail-form" method="post" enctype="multipart/form-data" action="<?= $escape($basePath) ?>/admin/site/media"><?= $csrfField ?><div class="site-fields"><label>Título *<input required maxlength="190" name="title"></label><label>Texto alternativo<input maxlength="255" name="alt_text" placeholder="Descreva a imagem para acessibilidade e SEO"></label><label class="full">Arquivo *<input required type="file" name="image" accept="image/jpeg,image/png,image/webp"><small class="meta">Até 8 MB. A imagem será redimensionada para web e enquadrada em 16:9 nas vitrines.</small></label></div><div class="site-actions"><button class="button button-primary" type="submit"><i class="fa-solid fa-cloud-arrow-up"></i> Otimizar e enviar</button></div></form></details>
 <?php if($media!==[]):?><div class="site-media-grid"><?php foreach($media as$item):?><article class="site-media-card"><img loading="lazy" src="<?= $escape($basePath) ?>/site/media/<?= (int)$item['id'] ?>" alt="<?= $escape($item['alt_text']??$item['title']) ?>"><div><strong><?= $escape($item['title']) ?></strong><small class="meta"><?= (int)($item['width']??0) ?>×<?= (int)($item['height']??0) ?> · <?= number_format(((int)$item['file_size'])/1024,0,',','.') ?> KB</small><code><?= $escape($basePath) ?>/site/media/<?= (int)$item['id'] ?></code><form method="post" action="<?= $escape($basePath) ?>/admin/site/media/<?= (int)$item['id'] ?>/delete" onsubmit="return confirm('Excluir esta imagem da biblioteca?')"><?= $csrfField ?><button class="button button-danger" type="submit" title="Excluir imagem"><i class="fa-solid fa-trash"></i></button></form></div></article><?php endforeach;?></div><?php endif;?>
</section>
