<?php
$models=['fixed_plus_percentage'=>'Mensal + percentual','split_only'=>'Somente split'];
$states=['not_issued'=>'Não emitida','issuing'=>'Processando','issued'=>'Emitida','paid'=>'Paga','failed'=>'Falhou'];
$splitStates=['prepared'=>'Preparando','submitted'=>'Enviado','failed'=>'Falhou'];
$money=static fn(mixed$value):string=>'R$ '.number_format((float)$value,2,',','.');
?>
<div class="page-header"><div><p class="eyebrow">ADM Central · Rede</p><h1>Financeiro das franquias</h1><p>Mensalidades, comissões, repasses e pendências de toda a rede.</p></div><a class="button button-secondary" href="<?= $escape($basePath) ?>/admin/platform/integrations/asaas"><i class="fa-solid fa-plug"></i> Integração Asaas</a></div>
<?php if(!empty($message)):?><div class="alert alert-success"><?= $escape($message) ?></div><?php endif;?><?php if(!empty($error)):?><div class="alert alert-danger"><?= $escape($error) ?></div><?php endif;?>

<div class="row g-3 mb-4">
 <div class="col-md-6 col-xl"><article class="metric-card h-100"><span><i class="fa-solid fa-sack-dollar"></i> Recebido</span><strong><?= $money($summary['paid_amount']??0) ?></strong><small><?= (int)($summary['paid']??0) ?> cobrança(s) paga(s)</small></article></div>
 <div class="col-md-6 col-xl"><article class="metric-card h-100"><span><i class="fa-solid fa-hourglass-half"></i> Em aberto</span><strong><?= $money($summary['open_amount']??0) ?></strong><small>Cobranças emitidas ou pendentes</small></article></div>
 <div class="col-md-6 col-xl"><article class="metric-card h-100"><span><i class="fa-solid fa-triangle-exclamation"></i> Vencido</span><strong><?= $money($summary['overdue_amount']??0) ?></strong><small><?= (int)($summary['overdue']??0) ?> mensalidade(s)</small></article></div>
 <div class="col-md-6 col-xl"><article class="metric-card h-100"><span><i class="fa-solid fa-percent"></i> Comissão Mundo Inter</span><strong><?= $money($summary['central_commission_amount']??0) ?></strong><small>Splits enviados no período</small></article></div>
 <div class="col-md-6 col-xl"><article class="metric-card h-100"><span><i class="fa-solid fa-money-bill-transfer"></i> Repasses</span><strong><?= $money($summary['franchise_transfer_amount']??0) ?></strong><small><?= (int)($summary['split_submitted']??0) ?> split(s) enviado(s)</small></article></div>
</div>

<form class="card p-3 mb-4" method="get" action="<?= $escape($basePath) ?>/admin/franchise-billing"><div class="row g-3 align-items-end">
 <div class="col-md-4"><label>Franquia<select name="organization"><option value="0">Todas as franquias</option><?php foreach($organizations as$organization):?><option value="<?= (int)$organization['id'] ?>" <?= (int)$filters['organization_id']===(int)$organization['id']?'selected':'' ?>><?= $escape((string)$organization['display_name']) ?></option><?php endforeach;?></select></label></div>
 <div class="col-md-3"><label>Situação<select name="status"><option value="">Todas as situações</option><option value="pending" <?= $filters['status']==='pending'?'selected':'' ?>>Pendências</option><option value="active" <?= $filters['status']==='active'?'selected':'' ?>>Operação ativa</option><option value="paid" <?= $filters['status']==='paid'?'selected':'' ?>>Pagas</option><option value="overdue" <?= $filters['status']==='overdue'?'selected':'' ?>>Vencidas</option><option value="failed" <?= $filters['status']==='failed'?'selected':'' ?>>Com falha</option></select></label></div>
 <div class="col-md-2"><label>De<input type="date" name="from" value="<?= $escape((string)$filters['from']) ?>"></label></div>
 <div class="col-md-2"><label>Até<input type="date" name="to" value="<?= $escape((string)$filters['to']) ?>"></label></div>
 <div class="col-md-1"><button class="button button-primary w-100" type="submit" title="Filtrar"><i class="fa-solid fa-filter"></i></button></div>
 </div><?php if((int)$filters['organization_id']>0||$filters['status']!==''||$filters['from']!==''||$filters['to']!==''):?><div class="mt-3"><a href="<?= $escape($basePath) ?>/admin/franchise-billing">Limpar filtros</a></div><?php endif;?></form>

<?php $pendingTotal=(int)($summary['pending_activation']??0)+(int)($summary['split_pending']??0)+(int)($summary['failures']??0)+(int)($summary['split_failures']??0);?>
<?php if($pendingTotal>0):?><div class="alert alert-warning"><strong><i class="fa-solid fa-bell"></i> <?= $pendingTotal ?> pendência(s) operacional(is).</strong> Revise contratos sem ativação, Wallets e falhas antes das próximas vendas.</div><?php else:?><div class="alert alert-success"><strong><i class="fa-solid fa-circle-check"></i> Operação financeira regular.</strong> Nenhuma pendência encontrada para o filtro atual.</div><?php endif;?>

<section class="card mb-4"><div class="card-header"><div><h2>Contratos e mensalidades</h2><p class="meta">Situação financeira e comercial por franquia.</p></div><span class="badge"><?= count($contracts) ?></span></div>
<div class="table-responsive"><table><thead><tr><th>Franquia</th><th>Contrato</th><th>Modelo</th><th>Mensalidade</th><th>Comissão</th><th>Wallet</th><th>Cobrança</th><th>Operação</th><th>Ações</th></tr></thead><tbody><?php foreach($contracts as$item):$walletRequired=(float)($item['sales_fee_percentage']??0)>0;$walletReady=!$walletRequired||(($item['asaas_wallet_status']??'')==='validated'&&!empty($item['asaas_wallet_id'])&&(int)($item['split_enabled']??0)===1);?><tr>
 <td><strong><?= $escape((string)$item['franchise_name']) ?></strong></td>
 <td><strong>#<?= (int)$item['contract_number'] ?></strong><small class="d-block meta"><?= $escape((string)$item['title']) ?></small></td>
 <td><?= $escape($models[$item['commercial_model']]??'Legado') ?></td>
 <td><?= (float)$item['monthly_fixed_amount']>0?$money($item['monthly_fixed_amount']):'—' ?><?php if(!empty($item['billing_due_date'])):?><small class="d-block meta">Vence <?= $escape(date('d/m/Y',strtotime((string)$item['billing_due_date']))) ?></small><?php endif;?></td>
 <td><?= number_format((float)$item['sales_fee_percentage'],2,',','.') ?>%</td>
 <td><span class="badge <?= $walletReady?'badge-success':'badge-warning' ?>"><?= $walletReady?'Pronta':'Pendente' ?></span></td>
 <td><span class="badge <?= $item['billing_issue_state']==='paid'?'badge-success':($item['billing_issue_state']==='failed'?'badge-danger':'badge-warning') ?>"><?= $escape($states[$item['billing_issue_state']]??$item['billing_issue_state']) ?></span></td>
 <td><span class="badge <?= $item['commercial_flow_status']==='active'?'badge-success':'badge-warning' ?>"><?= $item['commercial_flow_status']==='active'?'Ativa':'Pendente' ?></span></td>
 <td><div class="page-actions"><a class="button button-secondary button-icon" title="Abrir ficha da franquia" href="<?= $escape($basePath) ?>/admin/organizations/<?= (int)$item['organization_id'] ?>"><i class="fa-solid fa-building"></i></a><a class="button button-secondary button-icon" title="Abrir contrato" href="<?= $escape($basePath) ?>/admin/franchise-contracts/<?= (int)$item['id'] ?>"><i class="fa-solid fa-file-signature"></i></a><?php if(!empty($item['asaas_invoice_url'])):?><a class="button button-secondary button-icon" title="Abrir cobrança" href="<?= $escape((string)$item['asaas_invoice_url']) ?>" target="_blank" rel="noopener"><i class="fa-solid fa-arrow-up-right-from-square"></i></a><?php endif;?></div></td>
</tr><?php endforeach;?><?php if($contracts===[]):?><tr><td colspan="9"><div class="empty-state"><i class="fa-solid fa-magnifying-glass"></i><strong>Nenhum contrato encontrado</strong><span>Ajuste os filtros para ampliar a consulta.</span></div></td></tr><?php endif;?></tbody></table></div></section>

<section class="card" id="repasses"><div class="card-header"><div><h2>Histórico de splits e repasses</h2><p class="meta">Últimas divisões de pagamento processadas pelas novas vendas.</p></div><span class="badge"><?= count($splits) ?></span></div>
<div class="table-responsive"><table><thead><tr><th>Data</th><th>Franquia</th><th>Venda</th><th>Mundo Inter</th><th>Franquia</th><th>Situação</th><th>Referência</th></tr></thead><tbody><?php foreach($splits as$split):?><tr><td><?= $escape(date('d/m/Y H:i',strtotime((string)$split['created_at']))) ?></td><td><strong><?= $escape((string)$split['franchise_name']) ?></strong><small class="d-block meta">Contrato #<?= (int)$split['contract_number'] ?></small></td><td><?= $money($split['gross_value']) ?></td><td><?= $money((float)$split['gross_value']*(float)$split['central_percentage']/100) ?><small class="d-block meta"><?= number_format((float)$split['central_percentage'],2,',','.') ?>%</small></td><td><?= $money((float)$split['gross_value']*(float)$split['franchise_percentage']/100) ?><small class="d-block meta"><?= number_format((float)$split['franchise_percentage'],2,',','.') ?>%</small></td><td><span class="badge <?= $split['status']==='submitted'?'badge-success':($split['status']==='failed'?'badge-danger':'badge-warning') ?>"><?= $escape($splitStates[$split['status']]??(string)$split['status']) ?></span><?php if(!empty($split['error_message'])):?><small class="d-block text-danger"><?= $escape((string)$split['error_message']) ?></small><?php endif;?></td><td><small><?= $escape((string)$split['external_reference']) ?></small></td></tr><?php endforeach;?><?php if($splits===[]):?><tr><td colspan="7"><div class="empty-state"><i class="fa-solid fa-money-bill-transfer"></i><strong>Nenhum split processado neste período</strong></div></td></tr><?php endif;?></tbody></table></div></section>
