<?php
declare(strict_types=1);
namespace Interferencia\Modules\Crm;
use PDO;
final readonly class FollowUpRepository{
 public function __construct(private PDO $db){}
 public function allForUnits(array $unitIds,string $status=''):array{if($unitIds===[])return[];$marks=implode(',',array_fill(0,count($unitIds),'?'));$sql="SELECT f.*,c.name contact_name,c.unit_id,un.name unit_name,u.name responsible_name FROM crm_follow_ups f INNER JOIN crm_contacts c ON c.id=f.contact_id INNER JOIN units un ON un.id=c.unit_id INNER JOIN users u ON u.id=f.responsible_user_id WHERE c.unit_id IN ($marks)";$params=$unitIds;if(in_array($status,['pending','completed','cancelled'],true)){$sql.=' AND f.status=?';$params[]=$status;}$sql.=" ORDER BY CASE f.status WHEN 'pending' THEN 0 ELSE 1 END,f.scheduled_at ASC,f.id DESC";$s=$this->db->prepare($sql);$s->execute($params);return$s->fetchAll();}
 public function forContact(int $contactId,int $unitId):array{$s=$this->db->prepare('SELECT f.*,u.name responsible_name FROM crm_follow_ups f INNER JOIN crm_contacts c ON c.id=f.contact_id INNER JOIN users u ON u.id=f.responsible_user_id WHERE f.contact_id=:contact AND c.unit_id=:unit ORDER BY f.scheduled_at DESC,f.id DESC');$s->execute(['contact'=>$contactId,'unit'=>$unitId]);return$s->fetchAll();}
 public function create(int $contactId,int $responsibleId,string $action,string $scheduledAt,string $notes,int $creatorId):int{$s=$this->db->prepare("INSERT INTO crm_follow_ups(contact_id,responsible_user_id,action,scheduled_at,status,notes,created_by) VALUES(:contact,:responsible,:action,:scheduled,'pending',:notes,:creator)");$s->execute(['contact'=>$contactId,'responsible'=>$responsibleId,'action'=>trim($action),'scheduled'=>$scheduledAt,'notes'=>trim($notes),'creator'=>$creatorId]);return(int)$this->db->lastInsertId();}
 public function setStatus(int $id,int $unitId,string $status):bool{$completed=$status==='completed'?date('Y-m-d H:i:s'):null;$s=$this->db->prepare('UPDATE crm_follow_ups f INNER JOIN crm_contacts c ON c.id=f.contact_id SET f.status=:status,f.completed_at=:completed WHERE f.id=:id AND c.unit_id=:unit');$s->execute(['status'=>$status,'completed'=>$completed,'id'=>$id,'unit'=>$unitId]);return$s->rowCount()>0;}
}
