<?php

declare(strict_types=1);

use Interferencia\Kernel\Database\Migration;

return new class implements Migration
{
    public function id(): string{return '20260803_430000_create_finance_foundation';}
    public function up(PDO $db): void
    {
        $db->exec("INSERT IGNORE INTO permissions(code,name) VALUES('finance.view','Visualizar financeiro'),('finance.manage','Gerenciar financeiro'),('finance.legacy_view','Visualizar registros financeiros antigos sem unidade')");
        $db->exec("INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='super_admin' AND p.code IN('finance.view','finance.manage','finance.legacy_view')");
        $db->exec("INSERT IGNORE INTO role_permissions(role_id,permission_id) SELECT r.id,p.id FROM roles r CROSS JOIN permissions p WHERE r.code='manager' AND p.code='finance.view'");
        $db->exec("CREATE TABLE finance_customers(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,asaas_customer_id VARCHAR(80) NOT NULL,unit_id BIGINT UNSIGNED NULL,crm_contact_id BIGINT UNSIGNED NULL,name VARCHAR(200) NOT NULL,email VARCHAR(190) NULL,cpf_cnpj VARCHAR(20) NULL,phone VARCHAR(30) NULL,mobile_phone VARCHAR(30) NULL,external_reference VARCHAR(255) NULL,is_legacy TINYINT(1) NOT NULL DEFAULT 1,is_deleted TINYINT(1) NOT NULL DEFAULT 0,synced_at DATETIME NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY finance_customers_asaas_unique(asaas_customer_id),KEY finance_customers_unit_idx(unit_id),KEY finance_customers_document_idx(cpf_cnpj),CONSTRAINT finance_customers_unit_fk FOREIGN KEY(unit_id) REFERENCES units(id) ON DELETE SET NULL,CONSTRAINT finance_customers_crm_fk FOREIGN KEY(crm_contact_id) REFERENCES crm_contacts(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $db->exec("CREATE TABLE finance_payments(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,asaas_payment_id VARCHAR(80) NOT NULL,finance_customer_id BIGINT UNSIGNED NULL,unit_id BIGINT UNSIGNED NULL,billing_type VARCHAR(30) NULL,status VARCHAR(50) NOT NULL,value DECIMAL(12,2) NOT NULL DEFAULT 0,net_value DECIMAL(12,2) NULL,due_date DATE NULL,payment_date DATE NULL,description VARCHAR(500) NULL,external_reference VARCHAR(255) NULL,invoice_url VARCHAR(1000) NULL,bank_slip_url VARCHAR(1000) NULL,is_legacy TINYINT(1) NOT NULL DEFAULT 1,is_deleted TINYINT(1) NOT NULL DEFAULT 0,synced_at DATETIME NOT NULL,created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(id),UNIQUE KEY finance_payments_asaas_unique(asaas_payment_id),KEY finance_payments_unit_status_idx(unit_id,status),KEY finance_payments_due_idx(due_date),CONSTRAINT finance_payments_customer_fk FOREIGN KEY(finance_customer_id) REFERENCES finance_customers(id) ON DELETE SET NULL,CONSTRAINT finance_payments_unit_fk FOREIGN KEY(unit_id) REFERENCES units(id) ON DELETE SET NULL) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $db->exec("CREATE TABLE finance_unit_settings(unit_id BIGINT UNSIGNED NOT NULL,wallet_id VARCHAR(120) NULL,commission_type VARCHAR(20) NULL,commission_percent DECIMAL(7,4) NULL,commission_fixed DECIMAL(12,2) NULL,is_active TINYINT(1) NOT NULL DEFAULT 1,updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,PRIMARY KEY(unit_id),CONSTRAINT finance_unit_settings_unit_fk FOREIGN KEY(unit_id) REFERENCES units(id) ON DELETE CASCADE) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
        $db->exec("CREATE TABLE finance_webhook_events(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,asaas_event_id VARCHAR(100) NOT NULL,event_type VARCHAR(100) NOT NULL,resource_id VARCHAR(100) NULL,received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,processed_at DATETIME NULL,error_message VARCHAR(500) NULL,PRIMARY KEY(id),UNIQUE KEY finance_webhook_event_unique(asaas_event_id)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci");
    }
    public function down(PDO $db): void{$db->exec('DROP TABLE IF EXISTS finance_webhook_events');$db->exec('DROP TABLE IF EXISTS finance_unit_settings');$db->exec('DROP TABLE IF EXISTS finance_payments');$db->exec('DROP TABLE IF EXISTS finance_customers');$db->exec("DELETE rp FROM role_permissions rp INNER JOIN permissions p ON p.id=rp.permission_id WHERE p.code IN('finance.view','finance.manage','finance.legacy_view')");$db->exec("DELETE FROM permissions WHERE code IN('finance.view','finance.manage','finance.legacy_view')");}
};
