<?php $selectedStudentId=(int)($selectedStudentId??0); ?>
<div class="page-heading">
  <div><p class="eyebrow">Alunos</p><h1>Nova matrícula</h1><p class="meta">Defina aluno, curso, condição comercial, unidade e atendente.</p></div>
  <a class="button-secondary" href="<?= $escape($basePath) ?>/students/enrollments">Cancelar</a>
</div>
<?php if($error):?><p class="alert alert-danger"><?= $escape($error) ?></p><?php endif;?>
<section class="card"><div class="card-body"><form method="post" action="<?= $escape($basePath) ?>/students/enrollments"><?= $csrfField ?><div class="form-grid">
  <div class="form-field form-field-full"><label>1. Aluno <span class="required">*</span></label><select name="finance_customer_id" required><option value="">Selecione o aluno</option><?php foreach($students as$student):?><option value="<?= (int)$student['id'] ?>"<?= (int)$student['id']===$selectedStudentId?' selected':'' ?>><?= $escape($student['name'].' · '.$student['unit_name']) ?></option><?php endforeach;?></select></div>
  <div class="form-field form-field-full"><label>2. Curso contratado <span class="required">*</span></label><select name="contracted_item" required data-enrollment-product><option value="">Selecione o Curso individual ou a Trilha</option><?php if($products!==[]):?><optgroup label="Cursos individuais da franquia"><?php foreach($products as$product):$key='course:'.(int)$product['id'];?><option value="<?= $escape($key) ?>"<?= ($avaDestinations[$key]??[])===[]?' disabled':'' ?>><?= $escape($product['name'].' · R$ '.number_format((float)$product['value'],2,',','.').' · até '.(int)$product['max_installments'].'x'.(($avaDestinations[$key]??[])===[]?' · sem AVA disponível':'')) ?></option><?php endforeach;?></optgroup><?php endif;?><?php if(($providerCourses??[])!==[]):?><optgroup label="Cursos individuais das Formações"><?php foreach($providerCourses as$course):$key='provider_course:'.(int)$course['offer_id'];$automatic=(string)($course['provisioning_status']??'')==='automatic';?><option value="<?= $escape($key) ?>"<?= ($avaDestinations[$key]??[])===[]?' disabled':'' ?>><?= $escape($course['name'].' · '.(string)$course['formation_name'].' · R$ '.number_format((float)$course['price'],2,',','.').' · até '.(int)$course['max_installments'].'x'.($automatic?' · criação automática no AVA':'').(($avaDestinations[$key]??[])===[]?' · AVA indisponível':'')) ?></option><?php endforeach;?></optgroup><?php endif;?><?php if(($trails??[])!==[]):?><optgroup label="Trilhas publicadas"><?php foreach($trails as$trail):$key='trail:'.(int)$trail['id'];?><option value="<?= $escape($key) ?>"><?= $escape($trail['name'].' · Trilha com '.(int)$trail['item_count'].' Cursos individuais · R$ '.number_format((float)$trail['price'],2,',','.').' · até '.(int)$trail['max_installments'].'x') ?></option><?php endforeach;?></optgroup><?php endif;?></select><small>Se um Curso individual MASTER ainda não existir no AVA, o robô cria, organiza e confere o curso antes de registrar a matrícula.</small></div>
  <div class="form-field form-field-full"><label>AVA de destino <span class="required">*</span></label><select name="ava_connection_id" required data-enrollment-ava disabled><option value="">Escolha primeiro o curso contratado</option></select><small>Para cursos ainda não publicados, o AVA Cursos aparece como destino de preparação automática.</small></div>
  <div class="form-field"><label>3. Campanha</label><select name="campaign_id"><option value="">Sem desconto</option><?php foreach($campaigns as$campaign):?><option value="<?= (int)$campaign['id'] ?>"><?= $escape($campaign['name'].' · '.number_format((float)$campaign['discount_percent'],2,',','.').'% · até '.date('d/m/Y',strtotime((string)$campaign['valid_until']))) ?></option><?php endforeach;?></select></div>
  <div class="form-field"><label>4. Unidade <span class="required">*</span></label><select name="unit_id" required><option value="">Selecione a unidade</option><?php foreach($units as$unit):?><option value="<?= (int)$unit['id'] ?>"><?= $escape($unit['name']) ?></option><?php endforeach;?></select></div>
  <div class="form-field form-field-full"><label>5. Atendente <span class="required">*</span></label><select name="attendant_user_id" required><?php foreach($attendants as$attendant):?><option value="<?= (int)$attendant['id'] ?>"<?= (int)$attendant['id']===$selectedAttendantId?' selected':'' ?>><?= $escape($attendant['name'].' · '.$attendant['email']) ?></option><?php endforeach;?></select><small>O usuário conectado vem selecionado automaticamente e pode ser alterado.</small></div>
</div><div class="alert alert-warning"><strong>Próxima etapa:</strong> o robô verifica e prepara o curso quando necessário. Depois, valor, desconto e limite de parcelas são registrados na matrícula e o acesso é liberado somente após a confirmação do pagamento.</div><button class="button-primary" type="submit"<?= $products===[]&&($providerCourses??[])===[]&&($trails??[])===[]?' disabled':'' ?>><i class="fa-solid fa-robot"></i> Preparar matrícula</button></form></div></section>
<script type="application/json" data-enrollment-ava-options><?= json_encode($avaDestinations??[],JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES|JSON_HEX_TAG|JSON_HEX_AMP|JSON_HEX_APOS|JSON_HEX_QUOT) ?></script>
