<?php $ava=$avaSettings??[];$mode=(string)($ava['access_mode']??'shared');$primary=(string)($ava['primary_ava']??'shared');$shared=$ava['shared']??[];$own=$ava['own']??[]; ?>
<section class="card organization-section" id="ava" data-organization-panel="ava" hidden>
 <header class="organization-section-header"><span class="organization-section-icon"><i class="fa-solid fa-graduation-cap"></i></span><div><h2>Ambientes Virtuais de Aprendizagem</h2><p class="meta">Defina onde os alunos desta franquia estudam. As credenciais permanecem protegidas no ADM Central.</p></div></header>
 <form class="organization-ava-form" method="post" action="<?= $escape($basePath) ?>/admin/organizations/<?= (int)$organization['id'] ?>/ava"><?= $csrfField ?>
  <div class="ava-communication-card">
   <div class="ava-organization-title"><span><i class="fa-solid fa-id-card"></i></span><div><h3>Identidade e suporte no AVA</h3><p class="meta">Defina como esta franquia será identificada no Moodle e quais informações aparecerão na experiência personalizada do aluno.</p></div></div>
   <div class="organization-fields">
    <label>Título do login<input maxlength="160" name="login_title" value="<?= $escape($organization['login_title']??'') ?>" placeholder="Ex.: Portal da Franquia"></label>
    <label class="field-full">Mensagem de boas-vindas<input maxlength="500" name="login_welcome_text" value="<?= $escape($organization['login_welcome_text']??'') ?>" placeholder="Use suas credenciais para continuar."></label>
    <label>E-mail de suporte<input type="email" maxlength="190" name="support_email" value="<?= $escape($organization['support_email']??'') ?>" placeholder="suporte@franquia.com.br"></label>
    <label>Telefone de suporte<input maxlength="30" name="support_phone" inputmode="tel" data-mask="phone" value="<?= $escape($organization['support_phone']??'') ?>" placeholder="(00) 00000-0000"></label>
   </div>
  </div>
  <div class="organization-fields">
   <label>Modelo de uso *<select required name="access_mode"><option value="shared" <?= $mode==='shared'?'selected':'' ?>>Somente nosso AVA (AVA Cursos)</option><option value="own" <?= $mode==='own'?'selected':'' ?>>Somente AVA próprio</option><option value="both" <?= $mode==='both'?'selected':'' ?>>AVA Cursos + AVA próprio</option></select></label>
   <label>AVA principal *<select required name="primary_ava"><option value="shared" <?= $primary==='shared'?'selected':'' ?>>AVA Cursos</option><option value="own" <?= $primary==='own'?'selected':'' ?>>AVA próprio da franquia</option></select><small>Usado como padrão nas novas matrículas; poderá ser alterado por curso.</small></label>
  </div>
  <div class="ava-organization-cards">
   <article><div class="ava-organization-title"><span><i class="fa-solid fa-earth-americas"></i></span><div><h3>AVA Cursos</h3><p class="meta"><?= $escape((string)($shared['base_url']?:'avacursos.com.br')) ?></p></div><strong class="connection-badge <?= !empty($shared['configured'])&&!empty($shared['is_active'])?'connection-approved':'connection-pending' ?>"><?= !empty($shared['configured'])&&!empty($shared['is_active'])?'Disponível':'Configuração pendente' ?></strong></div><p class="meta"><i class="fa-solid fa-book-open"></i> <?= (int)($shared['mapped_courses']??0) ?> curso(s) do catálogo disponível(is).</p><?php if(!empty($shared['configured'])):?><button class="button button-secondary" type="submit" formaction="<?= $escape($basePath) ?>/admin/organizations/<?= (int)$organization['id'] ?>/ava/test/shared"><i class="fa-solid fa-plug-circle-check"></i> Testar</button><?php else:?><a class="button button-secondary" href="<?= $escape($basePath) ?>/admin/platform/integrations/ava-cursos">Configurar integração</a><?php endif;?></article>
   <article><div class="ava-organization-title"><span><i class="fa-solid fa-school"></i></span><div><h3>AVA próprio</h3><p class="meta">Moodle exclusivo desta franquia</p></div><strong class="connection-badge <?= !empty($own['configured'])&&!empty($own['is_active'])?'connection-approved':'connection-pending' ?>"><?= !empty($own['configured'])&&!empty($own['is_active'])?'Ativo':'Não configurado' ?></strong></div><label>Endereço HTTPS<input type="url" name="own_base_url" value="<?= $escape((string)($own['base_url']??'')) ?>" placeholder="https://ava.franquia.com.br"></label><label>Token do serviço web<input type="password" name="own_token" autocomplete="new-password" placeholder="<?= !empty($own['configured'])?'Deixe vazio para preservar o atual':'Cole o token gerado no Moodle' ?>"></label><label class="checkbox-row"><input type="checkbox" name="own_is_active" value="1" <?= !empty($own['is_active'])?'checked':'' ?>> Ativar conexão própria</label><?php if(!empty($own['configured'])):?><p class="meta"><i class="fa-solid fa-link"></i> <?= (int)($own['mapped_courses']??0) ?> curso(s) correspondente(s). A sincronização compara primeiro o código do curso e depois o nome breve.</p><div class="d-flex gap-2 flex-wrap"><button class="button button-secondary" type="submit" formaction="<?= $escape($basePath) ?>/admin/organizations/<?= (int)$organization['id'] ?>/ava/test/own"><i class="fa-solid fa-plug-circle-check"></i> Testar AVA próprio</button><?php if(!empty($own['is_active'])):?><button class="button button-secondary" type="submit" formaction="<?= $escape($basePath) ?>/admin/organizations/<?= (int)$organization['id'] ?>/ava/sync-courses"><i class="fa-solid fa-rotate"></i> Sincronizar cursos</button><?php endif;?></div><?php endif;?></article>
  </div>
  <div class="organization-savebar ava-savebar"><p class="meta"><i class="fa-solid fa-shield-halved"></i> Tokens criptografados e acessíveis somente ao ADM Central.</p><button class="button button-primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Salvar configuração AVA</button></div>
 </form>
</section>
<style>.organization-ava-form{display:grid;gap:1rem}.ava-communication-card{display:grid;gap:1rem;padding:1.2rem;border:1px solid #dce3e8;border-radius:1rem;background:#fff}.ava-organization-cards{display:grid;grid-template-columns:1fr 1fr;gap:1rem}.ava-organization-cards article{display:grid;align-content:start;gap:1rem;padding:1.2rem;border:1px solid #dce3e8;border-radius:1rem;background:#f9fafb}.ava-organization-cards label{margin:0}.ava-organization-cards input{width:100%}.ava-organization-title{display:flex;align-items:center;gap:.8rem;flex-wrap:wrap}.ava-organization-title>span{display:grid;place-items:center;width:2.5rem;height:2.5rem;border-radius:.75rem;background:#fff0f1;color:var(--inter-accent)}.ava-organization-title h3,.ava-organization-title p{margin:0}.ava-organization-title strong{margin-left:auto}.ava-savebar{position:static}.ava-savebar .button{min-width:15rem}@media(max-width:800px){.ava-organization-cards{grid-template-columns:1fr}}</style>
