<?php $status=(string)($organization['asaas_wallet_status']??'not_configured');$labels=['not_configured'=>'Não configurada','pending'=>'Aguardando validação','validated'=>'Validada','invalid'=>'Inválida']; ?>
<div class="page-header"><div><p class="eyebrow">ADM Central · Financeiro</p><h1>Asaas da franquia</h1><p><?= $escape($organization['display_name']) ?> · configure o destino dos repasses sem expor a chave da API.</p></div><a class="button button-secondary" href="<?= $escape($basePath) ?>/admin/organizations/<?= (int)$organization['id'] ?>/edit"><i class="fa-solid fa-arrow-left"></i> Voltar</a></div>
<?php if(!empty($message)):?><div class="alert alert-success"><?= $escape($message) ?></div><?php endif;?><?php if(!empty($error)):?><div class="alert alert-danger"><?= $escape($error) ?></div><?php endif;?>
<section class="card p-4 mb-4"><div class="row"><div class="col-sm-6"><strong>Situação atual</strong><p class="meta"><?= $escape($labels[$status]??$status) ?></p></div><div class="col-sm-6"><strong>Split</strong><p class="meta"><?= !empty($organization['split_enabled'])?'Ativo':'Desativado' ?></p></div></div></section>
<form class="card form-grid" method="post" action="<?= $escape($basePath) ?>/admin/organizations/<?= (int)$organization['id'] ?>/finance"><?= $csrfField ?>
<div class="form-section form-span-2"><h2>Conta recebedora</h2><p>O Wallet ID identifica a conta Asaas da franquia que receberá o repasse. A chave da API continua protegida no ADM Central.</p></div>
<label class="form-span-2">Wallet ID da franquia<input maxlength="80" name="asaas_wallet_id" value="<?= $escape($organization['asaas_wallet_id']??'') ?>" placeholder="00000000-0000-0000-0000-000000000000"><small>Copie em Asaas &gt; Integrações &gt; Identificadores da conta.</small></label>
<label>Situação da validação<select name="asaas_wallet_status"><option value="not_configured" <?= $status==='not_configured'?'selected':'' ?>>Não configurada</option><option value="pending" <?= $status==='pending'?'selected':'' ?>>Aguardando validação</option><option value="validated" <?= $status==='validated'?'selected':'' ?>>Validada pelo ADM Central</option><option value="invalid" <?= $status==='invalid'?'selected':'' ?>>Inválida</option></select></label>
<label class="checkbox-row"><input type="checkbox" name="split_enabled" value="1" <?= !empty($organization['split_enabled'])?'checked':'' ?>> Ativar split nas novas vendas</label>
<label class="form-span-2">Observações<textarea maxlength="500" rows="4" name="asaas_finance_notes"><?= $escape($organization['asaas_finance_notes']??'') ?></textarea></label>
<div class="alert alert-success form-span-2"><strong>Segurança:</strong> esta configuração não movimenta valores retroativos. O split será aplicado somente às novas cobranças quando o fluxo comercial estiver habilitado.</div>
<div class="form-actions form-span-2"><button class="button button-primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Salvar configuração financeira</button></div></form>
