<?php
$contractLabels=['draft'=>'Rascunho','sent'=>'Enviado','viewed'=>'Visualizado','signed'=>'Assinado','cancelled'=>'Cancelado'];
$billingLabels=['not_issued'=>'Não emitida','issuing'=>'Emitindo','issued'=>'Emitida','paid'=>'Paga','failed'=>'Falhou'];
$models=['fixed_plus_percentage'=>'Mensalidade + percentual','split_only'=>'Somente split'];
$latest=$contracts[0]??null;$site=null;
foreach($domains as$domain){if(($domain['purpose']??'')==='site'&&(int)($domain['is_primary']??0)===1){$site=$domain;break;}}
$contractStatus=$latest===null?'Sem contrato':($contractLabels[$latest['status']]??$latest['status']);
$billingStatus=$latest===null?'Aguardando contrato':($billingLabels[$latest['billing_issue_state']??'not_issued']??'Não configurada');
$nextAction='Vincular o primeiro contrato';
if($latest!==null){
    if($latest['status']==='draft')$nextAction='Revisar e liberar contrato';
    elseif(in_array($latest['status'],['sent','viewed'],true))$nextAction='Acompanhar assinatura';
    elseif(($latest['commercial_flow_status']??'pending')!=='active')$nextAction='Ativar operação comercial';
    else$nextAction='Operação regular';
}
?>
<div class="page-header"><div><p class="eyebrow">ADM Central · Franquia</p><h1><?= $escape((string)$organization['display_name']) ?></h1><p><?= $escape((string)$organization['legal_name']) ?> · <?= $escape((string)$organization['cnpj']) ?></p></div><div class="page-actions"><a class="button button-secondary" href="<?= $escape($basePath) ?>/admin/organizations"><i class="fa-solid fa-arrow-left"></i> Voltar</a><a class="button button-secondary" href="<?= $escape($basePath) ?>/admin/organizations/<?= (int)$organization['id'] ?>/edit"><i class="fa-solid fa-pen"></i> Editar</a></div></div>
<?php if(!empty($message)):?><div class="alert alert-success"><?= $escape($message) ?></div><?php endif;?><?php if(!empty($error)):?><div class="alert alert-danger"><?= $escape($error) ?></div><?php endif;?>

<div class="row g-3 mb-4">
  <div class="col-md-6 col-xl-3"><section class="metric-card h-100"><span><i class="fa-solid fa-building"></i> Cadastro</span><strong><?= $organization['status']==='active'?'Franquia ativa':'Franquia suspensa' ?></strong><small><?= $escape((string)($organization['manager_name']?:'Gestor não informado')) ?></small><a href="<?= $escape($basePath) ?>/admin/organizations/<?= (int)$organization['id'] ?>/edit">Editar cadastro e marca</a></section></div>
  <div class="col-md-6 col-xl-3"><section class="metric-card h-100"><span><i class="fa-solid fa-right-to-bracket"></i> Acesso</span><strong>mundointer.com.br/<?= $escape((string)$organization['panel_slug']) ?></strong><small><?= $site?$escape((string)$site['host']):'Site público não configurado' ?></small><a href="<?= $escape($basePath) ?>/<?= $escape((string)$organization['panel_slug']) ?>" target="_blank" rel="noopener">Abrir login exclusivo</a></section></div>
  <div class="col-md-6 col-xl-3"><section class="metric-card h-100"><span><i class="fa-solid fa-file-signature"></i> Contrato</span><strong><?= $escape($contractStatus) ?></strong><small><?= $latest?'Contrato #'.(int)($latest['contract_number']??1).' · '.($models[$latest['commercial_model']]??'Modelo legado'):'Nenhum contrato vinculado' ?></small><?php if($latest):?><a href="<?= $escape($basePath) ?>/admin/franchise-contracts/<?= (int)$latest['id'] ?>">Abrir contrato atual</a><?php elseif($application):?><a href="<?= $escape($basePath) ?>/admin/franchise-applications/<?= (int)$application['id'] ?>/contracts/create">Criar primeiro contrato</a><?php endif;?></section></div>
  <div class="col-md-6 col-xl-3"><section class="metric-card h-100"><span><i class="fa-solid fa-wallet"></i> Financeiro</span><strong><?= $escape($billingStatus) ?></strong><small><?= ($organization['asaas_wallet_status']??'not_configured')==='validated'?'Wallet validada':((int)($organization['split_enabled']??0)===1?'Split ativo':'Configuração pendente') ?></small><a href="<?= $escape($basePath) ?>/admin/organizations/<?= (int)$organization['id'] ?>/finance">Configurar Asaas e split</a></section></div>
</div>

<section class="card mb-4"><div class="card-header"><div><p class="eyebrow">Próxima ação</p><h2><?= $escape($nextAction) ?></h2><p class="meta"><?= $latest===null?'Defina as condições comerciais antes de ativar cobrança e split.':($latest['status']==='signed'?'Contrato assinado; confira cobrança, wallet e regra comercial.':'O histórico e o link de assinatura ficam centralizados abaixo.') ?></p></div><div class="page-actions"><?php if($latest):?><a class="button button-primary" href="<?= $escape($basePath) ?>/admin/franchise-contracts/<?= (int)$latest['id'] ?>"><i class="fa-solid fa-arrow-right"></i> Continuar processo</a><?php elseif($application):?><a class="button button-primary" href="<?= $escape($basePath) ?>/admin/franchise-applications/<?= (int)$application['id'] ?>/contracts/create"><i class="fa-solid fa-plus"></i> Criar contrato</a><?php endif;?></div></div></section>

<section class="card"><div class="card-header"><div><h2>Histórico contratual</h2><p class="meta">Contratos, renovações, assinatura e situação financeira em uma única linha do tempo.</p></div><span class="badge"><?= count($contracts) ?></span></div>
<?php if($contracts===[]):?><div class="empty-state"><i class="fa-solid fa-file-signature"></i><strong>Nenhum contrato vinculado</strong></div><?php else:?><div class="table-responsive"><table><thead><tr><th>Contrato</th><th>Modelo</th><th>Vigência</th><th>Assinatura</th><th>Financeiro</th><th>Ação</th></tr></thead><tbody><?php foreach($contracts as$c):?><tr><td><strong>#<?= (int)($c['contract_number']??1) ?> · <?= $escape((string)$c['title']) ?></strong><small class="d-block meta"><?= ($c['contract_type']??'new')==='renewal'?'Renovação':'Novo contrato' ?></small></td><td><?= $escape($models[$c['commercial_model']]??'Legado') ?></td><td><?= $c['valid_from']?$escape(date('d/m/Y',strtotime((string)$c['valid_from']))):'Sem início' ?> — <?= $c['valid_until']?$escape(date('d/m/Y',strtotime((string)$c['valid_until']))):'indeterminada' ?></td><td><span class="badge <?= $c['status']==='signed'?'badge-success':'badge-warning' ?>"><?= $escape($contractLabels[$c['status']]??(string)$c['status']) ?></span></td><td><?= $escape($billingLabels[$c['billing_issue_state']??'not_issued']??'Não configurada') ?></td><td><a class="button button-secondary button-icon" title="Abrir contrato" href="<?= $escape($basePath) ?>/admin/franchise-contracts/<?= (int)$c['id'] ?>"><i class="fa-solid fa-eye"></i></a></td></tr><?php endforeach;?></tbody></table></div><?php endif;?></section>
