<?php
$siteSettings=$siteSettings??[];
$siteFallbackUrl=rtrim((string)$basePath,'/').'/'.$escape((string)($organization['panel_slug']??'')).'/site';
$sitePreviewUrl=rtrim((string)$basePath,'/').'/admin/organizations/'.(int)$organization['id'].'/site-preview';
$siteEnabled=(int)($siteSettings['is_enabled']??0)===1;
$sitePublished=($siteSettings['publication_status']??'draft')==='published';
?>
<section class="card organization-section organization-site-governance" id="site" data-organization-panel="site" hidden>
 <header class="organization-section-header"><span class="organization-section-icon"><i class="fa-solid fa-store"></i></span><div><h2>Site Institucional</h2><p class="meta">Governança central do domínio, modelo-base, recursos, segurança e limites da franquia.</p></div></header>
 <div class="organization-site-status-grid">
  <article class="organization-site-status"><i class="fa-solid fa-power-off"></i><div><small>Disponibilidade</small><strong><?= $siteEnabled?'Liberado':'Bloqueado' ?></strong></div><span class="badge <?= $siteEnabled?'badge-success':'badge-warning' ?>"><?= $siteEnabled?'Ativo':'Pendente' ?></span></article>
  <article class="organization-site-status"><i class="fa-solid fa-globe"></i><div><small>Domínio definitivo</small><strong><?= $escape((string)($siteDomain['host']??'Não configurado')) ?></strong></div><span class="badge <?= ($siteDomain['status']??'pending')==='active'?'badge-success':'badge-warning' ?>"><?= ($siteDomain['status']??'pending')==='active'?'Validado':'Pendente' ?></span></article>
  <article class="organization-site-status"><i class="fa-solid fa-eye"></i><div><small>Publicação</small><strong><?= $sitePublished?'Publicado':'Em preparação' ?></strong></div><a class="button button-icon" href="<?= $escape($sitePublished?$siteFallbackUrl:$sitePreviewUrl) ?>" target="_blank" aria-label="Abrir prévia" title="Abrir prévia"><i class="fa-solid fa-arrow-up-right-from-square"></i></a></article>
 </div>
 <form class="site-governance-form" method="post" action="<?= $escape($basePath) ?>/admin/organizations/<?= (int)$organization['id'] ?>/site-governance"><?= $csrfField ?>
  <div class="site-governance-main">
   <div><p class="eyebrow">Modelo e liberação</p><h3>Estrutura controlada pelo ADM Central</h3><p class="meta">A franquia só verá e editará os recursos que forem liberados aqui.</p></div>
   <label>Modelo-base<select name="template_key"><option value="modern" <?= ($siteSettings['template_key']??'modern')==='modern'?'selected':'' ?>>Moderno</option><option value="classic" <?= ($siteSettings['template_key']??'')==='classic'?'selected':'' ?>>Clássico</option><option value="minimal" <?= ($siteSettings['template_key']??'')==='minimal'?'selected':'' ?>>Minimalista</option></select></label>
  </div>
  <div class="site-capabilities">
   <label class="site-capability"><input type="checkbox" name="is_enabled" value="1" <?= $siteEnabled?'checked':'' ?>><span><i class="fa-solid fa-toggle-on"></i><strong>Liberar Site Institucional</strong><small>Habilita o módulo no ADM da franquia e o endereço público.</small></span></label>
   <label class="site-capability"><input type="checkbox" name="allow_catalog" value="1" <?= (int)($siteSettings['allow_catalog']??1)===1?'checked':'' ?>><span><i class="fa-solid fa-table-cells-large"></i><strong>Formato catálogo</strong><small>Apresentação dos cursos com contato comercial.</small></span></label>
   <label class="site-capability"><input type="checkbox" name="allow_store" value="1" <?= (int)($siteSettings['allow_store']??0)===1?'checked':'' ?>><span><i class="fa-solid fa-cart-shopping"></i><strong>Formato loja</strong><small>Prepara venda e checkout direto no site.</small></span></label>
   <label class="site-capability"><input type="checkbox" name="allow_custom_pages" value="1" <?= (int)($siteSettings['allow_custom_pages']??0)===1?'checked':'' ?>><span><i class="fa-solid fa-file-lines"></i><strong>Páginas personalizadas</strong><small>Permite páginas extras além da estrutura padrão.</small></span></label>
  </div>
  <div class="site-limit-grid">
   <label>Máximo de banners<input type="number" min="1" max="10" name="max_banners" value="<?= (int)($siteSettings['max_banners']??3) ?>"></label>
   <label>Máximo de páginas<input type="number" min="1" max="30" name="max_pages" value="<?= (int)($siteSettings['max_pages']??5) ?>"></label>
   <label>Cursos em destaque<input type="number" min="1" max="24" name="max_featured_courses" value="<?= (int)($siteSettings['max_featured_courses']??6) ?>"></label>
   <div class="site-fallback"><small>Endereço provisório</small><strong><?= $escape($siteFallbackUrl) ?></strong></div>
  </div>
  <div class="site-governance-actions"><p class="meta"><i class="fa-solid fa-shield-halved"></i> Domínio e identidade visual continuam na aba Painel. Esta aba governa somente o site público.</p><button class="button button-primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Salvar governança</button></div>
 </form>
</section>
<style>
.organization-site-governance{min-height:0}.organization-site-status-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin-bottom:1rem}.organization-site-status{display:flex;align-items:center;gap:.8rem;min-width:0;padding:1rem;border:1px solid #dfe6ea;border-radius:.9rem;background:#f8fafb}.organization-site-status>i{display:grid;place-items:center;width:2.5rem;height:2.5rem;flex:0 0 2.5rem;border-radius:.7rem;background:#fff0f1;color:var(--inter-accent)}.organization-site-status>div{display:grid;min-width:0;margin-right:auto}.organization-site-status small{color:var(--inter-muted)}.organization-site-status strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.site-governance-form{display:grid;gap:1rem}.site-governance-main{display:grid;grid-template-columns:minmax(0,1fr) minmax(15rem,22rem);align-items:end;gap:1rem;padding:1.1rem;border:1px solid #dfe6ea;border-radius:.9rem}.site-governance-main h3,.site-governance-main p{margin:.15rem 0}.site-governance-main select,.site-limit-grid input{width:100%}.site-capabilities{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.75rem}.site-capability{position:relative;display:block;margin:0}.site-capability>input{position:absolute;opacity:0;pointer-events:none}.site-capability>span{display:grid;gap:.25rem;height:100%;padding:1rem;border:1px solid #dfe6ea;border-radius:.9rem;background:#fff;cursor:pointer}.site-capability i{color:var(--inter-accent)}.site-capability small{color:var(--inter-muted);font-weight:400}.site-capability>input:checked+span{border-color:color-mix(in srgb,var(--inter-accent) 42%,#dfe6ea);background:#fff5f5;box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--inter-accent) 18%,transparent)}.site-limit-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr)) minmax(15rem,1.6fr);align-items:end;gap:1rem}.site-fallback{display:grid;align-content:center;min-height:3.1rem;padding:.55rem .75rem;border-radius:.65rem;background:#f3f6f8}.site-fallback small{color:var(--inter-muted)}.site-fallback strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:.85rem}.site-governance-actions{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding-top:1rem;border-top:1px solid #e3e8ec}.site-governance-actions p{margin:0}@media(max-width:900px){.organization-site-status-grid,.site-capabilities{grid-template-columns:repeat(2,minmax(0,1fr))}.site-limit-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.organization-site-status-grid,.site-capabilities,.site-limit-grid,.site-governance-main{grid-template-columns:1fr}.site-governance-actions{align-items:stretch;flex-direction:column}.site-governance-actions .button{width:100%}}
</style>
