<?php
$siteSettings=$siteSettings??[];
$siteFallbackUrl=rtrim((string)$basePath,'/').'/'.$escape((string)($organization['panel_slug']??'')).'/site';
$sitePreviewUrl=rtrim((string)$basePath,'/').'/admin/organizations/'.(int)$organization['id'].'/site-preview';
$siteEnabled=(int)($siteSettings['is_enabled']??0)===1;
$sitePublished=($siteSettings['publication_status']??'draft')==='published';
$siteDomainStatus=$siteDomainStatus??[];
$siteDnsIpv4=(string)($siteDnsIpv4??'15.204.121.10');
$domainHost=(string)($siteDomain['host']??'');
$domainReady=($siteDomain['status']??'pending')==='active';
?>
<section class="card organization-section organization-site-governance" id="site" data-organization-panel="site" hidden>
 <header class="organization-section-header"><span class="organization-section-icon"><i class="fa-solid fa-store"></i></span><div><h2>Site Institucional</h2><p class="meta">Governança central do domínio, recursos, segurança e limites da franquia.</p></div></header>
 <div class="organization-site-status-grid">
  <article class="organization-site-status"><i class="fa-solid fa-power-off"></i><div><small>Disponibilidade</small><strong><?= $siteEnabled?'Liberado':'Bloqueado' ?></strong></div><span class="badge <?= $siteEnabled?'badge-success':'badge-warning' ?>"><?= $siteEnabled?'Ativo':'Pendente' ?></span></article>
  <article class="organization-site-status"><i class="fa-solid fa-globe"></i><div><small>Domínio definitivo</small><strong><?= $escape((string)($siteDomain['host']??'Não configurado')) ?></strong></div><span class="badge <?= ($siteDomain['status']??'pending')==='active'?'badge-success':'badge-warning' ?>"><?= ($siteDomain['status']??'pending')==='active'?'Validado':'Pendente' ?></span></article>
  <article class="organization-site-status"><i class="fa-solid fa-eye"></i><div><small>Publicação</small><strong><?= $sitePublished?'Publicado':'Em preparação' ?></strong></div><a class="button button-icon" href="<?= $escape($sitePublished?$siteFallbackUrl:$sitePreviewUrl) ?>" target="_blank" aria-label="Abrir prévia" title="Abrir prévia"><i class="fa-solid fa-arrow-up-right-from-square"></i></a></article>
 </div>
 <section class="site-domain-center">
  <div class="site-domain-heading"><div><p class="eyebrow">Endereço público</p><h3>Domínio da franquia e DNS</h3><p class="meta">O site pode usar o domínio que a franquia já possui. O e-mail continua no provedor atual: altere somente o registro indicado abaixo.</p></div><span class="badge <?= $domainReady?'badge-success':'badge-warning' ?>"><?= $domainReady?'Ativo e protegido':'Aguardando validação' ?></span></div>
  <div class="site-domain-layout">
   <form method="post" action="<?= $escape($basePath) ?>/admin/organizations/<?= (int)$organization['id'] ?>/site-domain" class="site-domain-form"><?= $csrfField ?>
    <label>Domínio público<input maxlength="253" name="site_host" value="<?= $escape($domainHost) ?>" placeholder="www.franquiatal.com.br"><small>Digite somente o domínio ou subdomínio, sem https:// e sem caminhos.</small></label>
    <button class="button button-primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Salvar domínio</button>
   </form>
   <div class="dns-guide"><strong>Passo a passo no provedor de DNS</strong><ol><li>Abra a zona DNS do domínio da franquia.</li><li>Crie ou edite um registro <strong>A</strong>.</li><li>Em <strong>Nome</strong>, use <code>www</code> (ou <code>@</code> para o domínio raiz).</li><li>Em <strong>Destino / IPv4</strong>, informe <code><?= $escape($siteDnsIpv4) ?></code>.</li><li>Não altere registros MX, SPF, DKIM ou os servidores de e-mail.</li><li>Aguarde a propagação e clique em <strong>Verificar DNS e HTTPS</strong>.</li></ol></div>
  </div>
  <div class="site-domain-diagnostic"><span><i class="fa-solid fa-network-wired"></i> DNS: <strong><?= (int)($siteDomainStatus['dns_ok']??0)===1?'apontado':'pendente' ?></strong></span><span><i class="fa-solid fa-lock"></i> HTTPS: <strong><?= (int)($siteDomainStatus['ssl_ok']??0)===1?'ativo':'pendente' ?></strong></span><span><i class="fa-solid fa-location-dot"></i> IP encontrado: <strong><?= $escape((string)($siteDomainStatus['resolved_ip']??'—')) ?></strong></span><?php if(!empty($siteDomainStatus['error_message'])):?><small><?= $escape((string)$siteDomainStatus['error_message']) ?></small><?php endif; ?><form method="post" action="<?= $escape($basePath) ?>/admin/organizations/<?= (int)$organization['id'] ?>/site-domain/check"><?= $csrfField ?><button class="button button-secondary" type="submit"><i class="fa-solid fa-rotate"></i> Verificar DNS e HTTPS</button></form></div>
 </section>
 <form class="site-governance-form" method="post" action="<?= $escape($basePath) ?>/admin/organizations/<?= (int)$organization['id'] ?>/site-governance"><?= $csrfField ?>
  <div class="site-governance-main">
   <div><p class="eyebrow">Liberação e limites</p><h3>Estrutura controlada pelo ADM Central</h3><p class="meta">A franquia escolhe o modelo visual e as cores. O ADM Central libera os recursos e define os limites.</p></div>
    <label>Após confirmar o pagamento<select name="checkout_fulfillment_mode"><option value="manual_review" <?= ($siteSettings['checkout_fulfillment_mode']??'manual_review')==='manual_review'?'selected':'' ?>>Revisar antes de liberar no AVA</option><option value="automatic" <?= ($siteSettings['checkout_fulfillment_mode']??'')==='automatic'?'selected':'' ?>>Matricular e liberar automaticamente</option></select></label>
  </div>
  <div class="site-capabilities">
   <label class="site-capability"><input type="checkbox" name="is_enabled" value="1" <?= $siteEnabled?'checked':'' ?>><span><i class="fa-solid fa-toggle-on"></i><strong>Liberar Site Institucional</strong><small>Habilita o módulo no ADM da franquia e o endereço público.</small></span></label>
   <label class="site-capability"><input type="checkbox" name="allow_catalog" value="1" <?= (int)($siteSettings['allow_catalog']??1)===1?'checked':'' ?>><span><i class="fa-solid fa-table-cells-large"></i><strong>Formato catálogo</strong><small>Apresentação dos cursos com contato comercial.</small></span></label>
   <label class="site-capability"><input type="checkbox" name="allow_store" value="1" <?= (int)($siteSettings['allow_store']??0)===1?'checked':'' ?>><span><i class="fa-solid fa-cart-shopping"></i><strong>Formato loja</strong><small>Prepara venda e checkout direto no site.</small></span></label>
   <label class="site-capability"><input type="checkbox" name="allow_custom_pages" value="1" <?= (int)($siteSettings['allow_custom_pages']??0)===1?'checked':'' ?>><span><i class="fa-solid fa-file-lines"></i><strong>Páginas personalizadas</strong><small>Permite páginas extras além da estrutura padrão.</small></span></label>
  </div>
  <div class="site-limit-grid">
   <label>Máximo de banners<input type="number" min="1" max="10" name="max_banners" value="<?= (int)($siteSettings['max_banners']??3) ?>"></label>
   <label>Máximo de páginas<input type="number" min="1" max="30" name="max_pages" value="<?= (int)($siteSettings['max_pages']??5) ?>"></label>
   <label>Cursos em destaque<input type="number" min="1" max="24" name="max_featured_courses" value="<?= (int)($siteSettings['max_featured_courses']??6) ?>"></label>
   <div class="site-fallback"><small>Endereço provisório</small><strong><?= $escape($siteFallbackUrl) ?></strong></div>
  </div>
  <div class="site-governance-actions"><p class="meta"><i class="fa-solid fa-shield-halved"></i> O domínio e os recursos estruturais são protegidos pelo ADM Central.</p><button class="button button-primary" type="submit"><i class="fa-solid fa-floppy-disk"></i> Salvar governança</button></div>
 </form>
</section>
<style>
.organization-site-governance{min-height:0}.organization-site-status-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:1rem;margin-bottom:1rem}.organization-site-status{display:flex;align-items:center;gap:.8rem;min-width:0;padding:1rem;border:1px solid #dfe6ea;border-radius:.9rem;background:#f8fafb}.organization-site-status>i{display:grid;place-items:center;width:2.5rem;height:2.5rem;flex:0 0 2.5rem;border-radius:.7rem;background:#fff0f1;color:var(--inter-accent)}.organization-site-status>div{display:grid;min-width:0;margin-right:auto}.organization-site-status small{color:var(--inter-muted)}.organization-site-status strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.site-governance-form{display:grid;gap:1rem}.site-governance-main{display:grid;grid-template-columns:minmax(0,1fr) minmax(13rem,18rem) minmax(18rem,24rem);align-items:end;gap:1rem;padding:1.1rem;border:1px solid #dfe6ea;border-radius:.9rem}.site-governance-main h3,.site-governance-main p{margin:.15rem 0}.site-governance-main select,.site-limit-grid input{width:100%}.site-capabilities{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:.75rem}.site-capability{position:relative;display:block;margin:0}.site-capability>input{position:absolute;opacity:0;pointer-events:none}.site-capability>span{display:grid;gap:.25rem;height:100%;padding:1rem;border:1px solid #dfe6ea;border-radius:.9rem;background:#fff;cursor:pointer}.site-capability i{color:var(--inter-accent)}.site-capability small{color:var(--inter-muted);font-weight:400}.site-capability>input:checked+span{border-color:color-mix(in srgb,var(--inter-accent) 42%,#dfe6ea);background:#fff5f5;box-shadow:inset 0 0 0 1px color-mix(in srgb,var(--inter-accent) 18%,transparent)}.site-limit-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr)) minmax(15rem,1.6fr);align-items:end;gap:1rem}.site-fallback{display:grid;align-content:center;min-height:3.1rem;padding:.55rem .75rem;border-radius:.65rem;background:#f3f6f8}.site-fallback small{color:var(--inter-muted)}.site-fallback strong{overflow:hidden;text-overflow:ellipsis;white-space:nowrap;font-size:.85rem}.site-governance-actions{display:flex;align-items:center;justify-content:space-between;gap:1rem;padding-top:1rem;border-top:1px solid #e3e8ec}.site-governance-actions p{margin:0}@media(max-width:1100px){.site-governance-main{grid-template-columns:1fr 1fr}.site-governance-main>div{grid-column:1/-1}}@media(max-width:900px){.organization-site-status-grid,.site-capabilities{grid-template-columns:repeat(2,minmax(0,1fr))}.site-limit-grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:650px){.organization-site-status-grid,.site-capabilities,.site-limit-grid,.site-governance-main{grid-template-columns:1fr}.site-governance-main>div{grid-column:auto}.site-governance-actions{align-items:stretch;flex-direction:column}.site-governance-actions .button{width:100%}}
.site-domain-center{display:grid;gap:1rem;margin:0 0 1rem;padding:1.1rem;border:1px solid #dfe6ea;border-radius:.9rem;background:#fff}.site-domain-heading,.site-domain-diagnostic{display:flex;align-items:center;justify-content:space-between;gap:1rem}.site-domain-heading h3,.site-domain-heading p{margin:.15rem 0}.site-domain-layout{display:grid;grid-template-columns:minmax(18rem,.8fr) minmax(24rem,1.2fr);gap:1rem}.site-domain-form{display:grid;align-content:start;gap:.8rem;padding:1rem;border-radius:.75rem;background:#f7f9fb}.site-domain-form input{width:100%}.site-domain-form .button{justify-self:start}.dns-guide{padding:1rem;border:1px solid #e4e9ed;border-radius:.75rem}.dns-guide ol{margin:.65rem 0 0;padding-left:1.25rem}.dns-guide li{margin:.4rem 0;line-height:1.45}.dns-guide code{padding:.15rem .35rem;border-radius:.3rem;background:#edf1f4;font-weight:800}.site-domain-diagnostic{flex-wrap:wrap;padding:.8rem 1rem;border-radius:.75rem;background:#f7f9fb}.site-domain-diagnostic>span{color:var(--inter-muted)}.site-domain-diagnostic>small{flex:1 1 100%;color:#a35b00}@media(max-width:900px){.site-domain-layout{grid-template-columns:1fr}.site-domain-heading{align-items:flex-start;flex-direction:column}.site-domain-diagnostic{align-items:stretch;flex-direction:column}.site-domain-diagnostic .button{width:100%}}
</style>
<style>.site-governance-main{grid-template-columns:minmax(0,1fr) minmax(18rem,24rem)}@media(max-width:650px){.site-governance-main{grid-template-columns:1fr}}</style>
